package app.maximus.core.security

/**
 * Binary envelope for AES-256-GCM ciphertexts:
 *
 *   byte 0        : format version (currently 1)
 *   bytes 1..12   : 96-bit IV, freshly generated by the Keystore for every encryption
 *   bytes 13..end : ciphertext || 128-bit authentication tag
 *
 * Pure Kotlin, no Android dependencies, so it is covered by JVM unit tests.
 */
object AeadEnvelope {
    const val VERSION: Byte = 1
    const val IV_LENGTH = 12
    const val TAG_LENGTH = 16
    const val HEADER_LENGTH = 1 + IV_LENGTH

    class Parts(val iv: ByteArray, val ciphertextWithTag: ByteArray)

    fun encode(iv: ByteArray, ciphertextWithTag: ByteArray): ByteArray {
        require(iv.size == IV_LENGTH) { "IV must be $IV_LENGTH bytes, was ${iv.size}" }
        require(ciphertextWithTag.size >= TAG_LENGTH) { "Ciphertext shorter than the GCM tag" }
        val out = ByteArray(HEADER_LENGTH + ciphertextWithTag.size)
        out[0] = VERSION
        iv.copyInto(out, destinationOffset = 1)
        ciphertextWithTag.copyInto(out, destinationOffset = HEADER_LENGTH)
        return out
    }

    fun decode(envelope: ByteArray): Parts {
        require(envelope.size >= HEADER_LENGTH + TAG_LENGTH) { "Envelope too short: ${envelope.size} bytes" }
        require(envelope[0] == VERSION) { "Unsupported envelope version ${envelope[0]}" }
        return Parts(
            iv = envelope.copyOfRange(1, HEADER_LENGTH),
            ciphertextWithTag = envelope.copyOfRange(HEADER_LENGTH, envelope.size)
        )
    }
}
