package app.maximus.nutrition.domain

enum class FoodCategory { PRODUCE, DAIRY_EGGS, MEAT_FISH, GRAINS, LEGUMES, NUTS_OILS, PANTRY }

/** Nutrients per 100 g edible portion; carbohydrates are available carbohydrate (EU convention), energy by Atwater. */
data class Food(val key: String, val nameDe: String, val nameEn: String, val category: FoodCategory, val per100: Nutrients)

/**
 * Reference values rounded from the German Bundeslebensmittelschlüssel (BLS 3.02) and USDA FoodData Central
 * (SR Legacy); raw weights unless stated. Energy is recomputed from the macronutrients with Atwater factors,
 * so recipe totals are internally consistent (deviation from label energy typically < 5 %).
 */
object Foods {
    private fun f(key: String, de: String, en: String, cat: FoodCategory, p: Double, fat: Double, c: Double, fib: Double) =
        Food(key, de, en, cat, Nutrients.of(p, fat, c, fib))

    val all: List<Food> = listOf(
        // grains, bread, starch
        f("oats", "Haferflocken", "Rolled oats", FoodCategory.GRAINS, 13.5, 7.0, 58.7, 10.0),
        f("rice", "Reis (roh)", "Rice (raw)", FoodCategory.GRAINS, 7.0, 0.6, 78.0, 1.4),
        f("pasta", "Hartweizennudeln (roh)", "Durum pasta (raw)", FoodCategory.GRAINS, 12.5, 1.5, 70.0, 3.0),
        f("couscous", "Couscous (roh)", "Couscous (raw)", FoodCategory.GRAINS, 12.8, 0.6, 72.0, 5.0),
        f("spaetzle", "Spätzle (frisch)", "Spätzle (fresh)", FoodCategory.GRAINS, 8.0, 2.5, 45.0, 2.0),
        f("bread_whole", "Vollkornbrot", "Wholemeal rye bread", FoodCategory.GRAINS, 7.0, 1.2, 39.0, 7.5),
        f("tortilla", "Weizentortilla", "Wheat tortilla", FoodCategory.GRAINS, 8.5, 7.0, 50.0, 3.0),
        f("flour", "Weizenmehl Type 405", "Plain wheat flour", FoodCategory.GRAINS, 10.0, 1.0, 72.0, 3.0),
        f("breadcrumbs", "Paniermehl", "Breadcrumbs", FoodCategory.GRAINS, 13.0, 2.0, 72.0, 4.0),
        f("potato", "Kartoffeln", "Potatoes", FoodCategory.PRODUCE, 2.0, 0.1, 15.0, 2.1),
        f("sweet_potato", "Süßkartoffeln", "Sweet potatoes", FoodCategory.PRODUCE, 1.6, 0.1, 17.0, 3.0),
        // dairy, eggs, protein powder
        f("milk", "Milch 1,5 %", "Milk 1.5 %", FoodCategory.DAIRY_EGGS, 3.4, 1.5, 4.8, 0.0),
        f("skyr", "Skyr natur", "Skyr, plain", FoodCategory.DAIRY_EGGS, 11.0, 0.2, 4.0, 0.0),
        f("quark", "Magerquark", "Low-fat quark", FoodCategory.DAIRY_EGGS, 12.0, 0.3, 4.0, 0.0),
        f("yogurt_greek", "Griechischer Joghurt 2 %", "Greek yoghurt 2 %", FoodCategory.DAIRY_EGGS, 9.0, 2.0, 4.0, 0.0),
        f("cottage", "Hüttenkäse", "Cottage cheese", FoodCategory.DAIRY_EGGS, 12.0, 4.0, 3.0, 0.0),
        f("sour_cream", "Saure Sahne 10 %", "Sour cream 10 %", FoodCategory.DAIRY_EGGS, 3.0, 10.0, 4.0, 0.0),
        f("cheese", "Emmentaler gerieben", "Grated Emmental", FoodCategory.DAIRY_EGGS, 28.0, 30.0, 0.0, 0.0),
        f("feta", "Feta", "Feta", FoodCategory.DAIRY_EGGS, 17.0, 21.0, 1.0, 0.0),
        f("parmesan", "Parmesan", "Parmesan", FoodCategory.DAIRY_EGGS, 35.0, 29.0, 0.0, 0.0),
        f("butter", "Butter", "Butter", FoodCategory.DAIRY_EGGS, 0.7, 83.0, 0.6, 0.0),
        f("egg", "Eier (ganz)", "Whole eggs", FoodCategory.DAIRY_EGGS, 12.6, 9.5, 0.7, 0.0),
        f("egg_white", "Eiklar", "Egg whites", FoodCategory.DAIRY_EGGS, 10.9, 0.2, 0.7, 0.0),
        f("whey", "Molkenprotein neutral", "Whey protein, unflavoured", FoodCategory.PANTRY, 78.0, 6.0, 7.0, 0.0),
        // meat and fish (raw)
        f("chicken", "Hähnchenbrust", "Chicken breast", FoodCategory.MEAT_FISH, 23.0, 1.5, 0.0, 0.0),
        f("chicken_thigh", "Hähnchenoberkeule ohne Haut", "Chicken thigh, skinless", FoodCategory.MEAT_FISH, 19.0, 6.0, 0.0, 0.0),
        f("turkey", "Putenbrust", "Turkey breast", FoodCategory.MEAT_FISH, 24.0, 1.0, 0.0, 0.0),
        f("beef_mince", "Rinderhack 5 %", "Lean beef mince 5 %", FoodCategory.MEAT_FISH, 21.0, 5.0, 0.0, 0.0),
        f("beef_chuck", "Rindergulasch", "Beef chuck", FoodCategory.MEAT_FISH, 20.0, 8.0, 0.0, 0.0),
        f("steak", "Rinderhüftsteak", "Beef rump steak", FoodCategory.MEAT_FISH, 22.0, 4.0, 0.0, 0.0),
        f("pork_loin", "Schweinelende / Schnitzelfleisch", "Pork loin", FoodCategory.MEAT_FISH, 22.0, 2.0, 0.0, 0.0),
        f("ham", "Kochschinken", "Cooked ham", FoodCategory.MEAT_FISH, 20.0, 3.0, 1.0, 0.0),
        f("salmon", "Lachsfilet", "Salmon fillet", FoodCategory.MEAT_FISH, 20.0, 13.0, 0.0, 0.0),
        f("cod", "Kabeljaufilet", "Cod fillet", FoodCategory.MEAT_FISH, 18.0, 0.7, 0.0, 0.0),
        f("tuna", "Thunfisch im eigenen Saft", "Tuna in brine, drained", FoodCategory.MEAT_FISH, 26.0, 1.0, 0.0, 0.0),
        f("tofu", "Tofu natur", "Firm tofu", FoodCategory.LEGUMES, 15.0, 8.0, 1.5, 1.0),
        // legumes (dry or canned, drained)
        f("lentils", "Linsen (trocken)", "Lentils (dry)", FoodCategory.LEGUMES, 24.6, 1.5, 50.0, 11.0),
        f("chickpeas", "Kichererbsen (Dose, abgetropft)", "Chickpeas (canned, drained)", FoodCategory.LEGUMES, 7.0, 2.4, 14.0, 7.0),
        f("kidney", "Kidneybohnen (Dose, abgetropft)", "Kidney beans (canned, drained)", FoodCategory.LEGUMES, 7.5, 0.5, 13.0, 6.0),
        f("peas", "Erbsen (TK)", "Peas (frozen)", FoodCategory.PRODUCE, 5.4, 0.4, 9.0, 5.0),
        // vegetables and fruit
        f("tomato_canned", "Tomaten gehackt (Dose)", "Chopped tomatoes (canned)", FoodCategory.PANTRY, 1.2, 0.2, 4.0, 1.2),
        f("tomato", "Tomaten", "Tomatoes", FoodCategory.PRODUCE, 0.9, 0.2, 2.6, 1.2),
        f("onion", "Zwiebeln", "Onions", FoodCategory.PRODUCE, 1.2, 0.2, 5.0, 1.8),
        f("garlic", "Knoblauch", "Garlic", FoodCategory.PRODUCE, 6.0, 0.5, 28.0, 2.0),
        f("pepper", "Paprika", "Bell pepper", FoodCategory.PRODUCE, 1.0, 0.3, 5.0, 2.0),
        f("broccoli", "Brokkoli", "Broccoli", FoodCategory.PRODUCE, 3.0, 0.4, 2.7, 3.0),
        f("spinach", "Blattspinat", "Spinach", FoodCategory.PRODUCE, 2.9, 0.4, 0.6, 2.2),
        f("zucchini", "Zucchini", "Courgette", FoodCategory.PRODUCE, 1.6, 0.4, 2.1, 1.1),
        f("carrot", "Karotten", "Carrots", FoodCategory.PRODUCE, 0.9, 0.2, 6.8, 2.8),
        f("mushroom", "Champignons", "Mushrooms", FoodCategory.PRODUCE, 3.1, 0.3, 0.6, 1.0),
        f("cucumber", "Gurke", "Cucumber", FoodCategory.PRODUCE, 0.6, 0.1, 2.0, 0.5),
        f("lettuce", "Blattsalat", "Mixed salad leaves", FoodCategory.PRODUCE, 1.4, 0.2, 1.5, 1.5),
        f("green_beans", "Grüne Bohnen", "Green beans", FoodCategory.PRODUCE, 2.0, 0.2, 5.0, 2.5),
        f("sauerkraut", "Sauerkraut", "Sauerkraut", FoodCategory.PRODUCE, 1.5, 0.3, 0.8, 2.1),
        f("corn", "Mais (Dose)", "Sweetcorn (canned)", FoodCategory.PANTRY, 2.9, 1.2, 15.0, 2.5),
        f("avocado", "Avocado", "Avocado", FoodCategory.PRODUCE, 2.0, 15.0, 1.9, 6.7),
        f("banana", "Banane", "Banana", FoodCategory.PRODUCE, 1.1, 0.3, 20.0, 2.0),
        f("apple", "Apfel", "Apple", FoodCategory.PRODUCE, 0.3, 0.2, 11.4, 2.4),
        f("berries", "Beerenmischung (TK)", "Mixed berries (frozen)", FoodCategory.PRODUCE, 1.0, 0.4, 7.0, 4.5),
        f("mango", "Mango (TK)", "Mango (frozen)", FoodCategory.PRODUCE, 0.8, 0.4, 13.0, 1.7),
        f("lemon", "Zitronensaft", "Lemon juice", FoodCategory.PRODUCE, 0.4, 0.1, 2.4, 0.0),
        // nuts, fats, pantry
        f("peanut_butter", "Erdnussmus", "Peanut butter", FoodCategory.NUTS_OILS, 25.0, 50.0, 12.0, 8.0),
        f("walnuts", "Walnüsse", "Walnuts", FoodCategory.NUTS_OILS, 15.0, 65.0, 7.0, 6.5),
        f("almonds", "Mandeln", "Almonds", FoodCategory.NUTS_OILS, 21.0, 50.0, 6.0, 12.0),
        f("chia", "Chiasamen", "Chia seeds", FoodCategory.NUTS_OILS, 17.0, 31.0, 8.0, 34.0),
        f("olive_oil", "Olivenöl", "Olive oil", FoodCategory.NUTS_OILS, 0.0, 100.0, 0.0, 0.0),
        f("coconut_milk", "Kokosmilch", "Coconut milk", FoodCategory.PANTRY, 1.8, 18.0, 3.0, 0.0),
        f("honey", "Honig", "Honey", FoodCategory.PANTRY, 0.4, 0.0, 80.0, 0.0),
        f("soy_sauce", "Sojasauce", "Soy sauce", FoodCategory.PANTRY, 8.0, 0.1, 5.0, 0.8),
        f("cocoa", "Kakaopulver entölt", "Cocoa powder", FoodCategory.PANTRY, 20.0, 11.0, 11.0, 33.0),
        f("dark_chocolate", "Zartbitterschokolade 70 %", "Dark chocolate 70 %", FoodCategory.PANTRY, 8.0, 42.0, 30.0, 11.0),
        f("lamb", "Lammkeule", "Leg of lamb", FoodCategory.MEAT_FISH, 20.0, 9.0, 0.0, 0.0),
        f("pork_belly", "Schweinebauch", "Pork belly", FoodCategory.MEAT_FISH, 17.0, 21.0, 0.0, 0.0),
        f("bacon", "Frühstücksspeck", "Bacon", FoodCategory.MEAT_FISH, 13.0, 39.0, 1.0, 0.0),
        f("sausage", "Bratwurst", "Bratwurst", FoodCategory.MEAT_FISH, 13.0, 25.0, 1.0, 0.0),
        f("liver", "Rinderleber", "Beef liver", FoodCategory.MEAT_FISH, 20.0, 4.0, 4.0, 0.0),
        f("shrimp", "Garnelen", "Prawns", FoodCategory.MEAT_FISH, 20.0, 1.0, 0.0, 0.0),
        f("mackerel", "Makrele", "Mackerel", FoodCategory.MEAT_FISH, 19.0, 14.0, 0.0, 0.0),
        f("herring", "Hering", "Herring", FoodCategory.MEAT_FISH, 18.0, 15.0, 0.0, 0.0),
        f("pollock", "Seelachsfilet", "Pollock fillet", FoodCategory.MEAT_FISH, 18.0, 1.0, 0.0, 0.0),
        f("chicken_mince", "Hähnchenhack", "Chicken mince", FoodCategory.MEAT_FISH, 20.0, 8.0, 0.0, 0.0),
        f("seitan", "Seitan", "Seitan", FoodCategory.LEGUMES, 25.0, 2.0, 8.0, 1.0),
        f("tempeh", "Tempeh", "Tempeh", FoodCategory.LEGUMES, 19.0, 11.0, 9.0, 6.0),
        f("white_beans", "Weiße Bohnen (Dose)", "White beans (canned)", FoodCategory.LEGUMES, 7.0, 0.5, 12.0, 6.0),
        f("split_peas", "Gelbe Erbsen (trocken)", "Yellow split peas (dry)", FoodCategory.LEGUMES, 23.0, 1.5, 48.0, 15.0),
        f("soy_mince", "Sojaschnetzel (trocken)", "Soy mince (dry)", FoodCategory.LEGUMES, 50.0, 1.0, 20.0, 18.0),
        f("quinoa", "Quinoa (roh)", "Quinoa (raw)", FoodCategory.GRAINS, 14.0, 6.0, 58.0, 7.0),
        f("bulgur", "Bulgur (roh)", "Bulgur (raw)", FoodCategory.GRAINS, 12.0, 1.3, 64.0, 12.0),
        f("barley", "Graupen (roh)", "Pearl barley (raw)", FoodCategory.GRAINS, 10.0, 2.0, 63.0, 10.0),
        f("rye_flakes", "Roggenflocken", "Rye flakes", FoodCategory.GRAINS, 11.0, 2.0, 60.0, 14.0),
        f("rice_basmati", "Basmatireis (roh)", "Basmati rice (raw)", FoodCategory.GRAINS, 8.0, 0.8, 77.0, 1.5),
        f("gnocchi", "Gnocchi", "Gnocchi", FoodCategory.GRAINS, 4.0, 1.0, 32.0, 2.0),
        f("pita", "Pitabrot", "Pita bread", FoodCategory.GRAINS, 9.0, 1.5, 53.0, 3.0),
        f("rice_paper", "Reispapier", "Rice paper", FoodCategory.GRAINS, 1.0, 0.1, 83.0, 1.0),
        f("polenta", "Polenta (roh)", "Polenta (dry)", FoodCategory.GRAINS, 8.0, 1.5, 73.0, 4.0),
        f("mozzarella", "Mozzarella", "Mozzarella", FoodCategory.DAIRY_EGGS, 19.0, 17.0, 2.0, 0.0),
        f("ricotta", "Ricotta", "Ricotta", FoodCategory.DAIRY_EGGS, 9.0, 11.0, 3.0, 0.0),
        f("cream_cheese", "Frischkäse", "Cream cheese", FoodCategory.DAIRY_EGGS, 6.0, 24.0, 3.0, 0.0),
        f("gouda", "Gouda gerieben", "Grated gouda", FoodCategory.DAIRY_EGGS, 25.0, 27.0, 2.0, 0.0),
        f("cream", "Schlagsahne", "Whipping cream", FoodCategory.DAIRY_EGGS, 2.4, 32.0, 3.0, 0.0),
        f("buttermilk", "Buttermilch", "Buttermilk", FoodCategory.DAIRY_EGGS, 3.5, 0.5, 4.0, 0.0),
        f("casein", "Caseinprotein neutral", "Casein protein, unflavoured", FoodCategory.PANTRY, 76.0, 2.0, 7.0, 0.0),
        f("cabbage", "Weißkohl", "White cabbage", FoodCategory.PRODUCE, 1.3, 0.2, 4.0, 2.5),
        f("kale", "Grünkohl", "Kale", FoodCategory.PRODUCE, 4.3, 0.9, 2.5, 4.2),
        f("cauliflower", "Blumenkohl", "Cauliflower", FoodCategory.PRODUCE, 2.5, 0.3, 2.3, 2.9),
        f("brussels_sprouts", "Rosenkohl", "Brussels sprouts", FoodCategory.PRODUCE, 4.5, 0.3, 3.3, 4.4),
        f("leek", "Lauch", "Leek", FoodCategory.PRODUCE, 2.1, 0.3, 3.3, 2.3),
        f("celeriac", "Knollensellerie", "Celeriac", FoodCategory.PRODUCE, 1.6, 0.3, 2.3, 4.2),
        f("beetroot", "Rote Bete", "Beetroot", FoodCategory.PRODUCE, 1.5, 0.1, 8.0, 2.5),
        f("pumpkin", "Kürbis (Hokkaido)", "Pumpkin (Hokkaido)", FoodCategory.PRODUCE, 1.1, 0.1, 6.0, 2.0),
        f("asparagus", "Spargel", "Asparagus", FoodCategory.PRODUCE, 2.2, 0.1, 2.0, 2.1),
        f("aubergine", "Aubergine", "Aubergine", FoodCategory.PRODUCE, 1.0, 0.2, 2.5, 3.0),
        f("radish", "Radieschen", "Radishes", FoodCategory.PRODUCE, 0.8, 0.1, 2.0, 1.6),
        f("ginger", "Ingwer", "Ginger", FoodCategory.PRODUCE, 1.8, 0.8, 16.0, 2.0),
        f("orange", "Orange", "Orange", FoodCategory.PRODUCE, 1.0, 0.2, 9.0, 2.2),
        f("pear", "Birne", "Pear", FoodCategory.PRODUCE, 0.5, 0.3, 12.0, 3.1),
        f("grapes", "Weintrauben", "Grapes", FoodCategory.PRODUCE, 0.7, 0.3, 16.0, 1.0),
        f("pineapple", "Ananas", "Pineapple", FoodCategory.PRODUCE, 0.5, 0.2, 12.0, 1.4),
        f("dates", "Datteln", "Dates", FoodCategory.PRODUCE, 2.5, 0.5, 65.0, 8.0),
        f("raisins", "Rosinen", "Raisins", FoodCategory.PRODUCE, 3.0, 0.5, 68.0, 5.0),
        f("cashews", "Cashewkerne", "Cashews", FoodCategory.NUTS_OILS, 18.0, 44.0, 26.0, 3.0),
        f("hazelnuts", "Haselnüsse", "Hazelnuts", FoodCategory.NUTS_OILS, 15.0, 61.0, 7.0, 10.0),
        f("sunflower_seeds", "Sonnenblumenkerne", "Sunflower seeds", FoodCategory.NUTS_OILS, 21.0, 49.0, 12.0, 9.0),
        f("pumpkin_seeds", "Kürbiskerne", "Pumpkin seeds", FoodCategory.NUTS_OILS, 24.0, 46.0, 10.0, 6.0),
        f("flaxseed", "Leinsamen geschrotet", "Ground flaxseed", FoodCategory.NUTS_OILS, 18.0, 42.0, 2.0, 27.0),
        f("tahini", "Sesammus", "Tahini", FoodCategory.NUTS_OILS, 17.0, 54.0, 10.0, 9.0),
        f("rapeseed_oil", "Rapsöl", "Rapeseed oil", FoodCategory.NUTS_OILS, 0.0, 100.0, 0.0, 0.0),
        f("mustard", "Senf", "Mustard", FoodCategory.PANTRY, 5.0, 4.0, 5.0, 3.0),
        f("tomato_paste", "Tomatenmark", "Tomato paste", FoodCategory.PANTRY, 4.5, 0.5, 14.0, 4.0),
        f("stock_cube", "Gemüsebrühe (Pulver)", "Vegetable stock powder", FoodCategory.PANTRY, 10.0, 10.0, 30.0, 2.0),
        f("vinegar", "Essig", "Vinegar", FoodCategory.PANTRY, 0.0, 0.0, 0.5, 0.0),
        f("maple_syrup", "Ahornsirup", "Maple syrup", FoodCategory.PANTRY, 0.0, 0.1, 67.0, 0.0),
        f("protein_bar", "Proteinriegel", "Protein bar", FoodCategory.PANTRY, 32.0, 12.0, 30.0, 10.0),
        f("rice_cakes", "Reiswaffeln", "Rice cakes", FoodCategory.PANTRY, 8.0, 3.0, 78.0, 3.0),
        f("olives", "Oliven", "Olives", FoodCategory.PANTRY, 1.0, 15.0, 1.0, 3.0)
    )

    val byKey: Map<String, Food> = all.associateBy { it.key }
}
