package app.maximus.nutrition.domain

enum class MealType { BREAKFAST, MAIN, SNACK }

enum class RecipeTag { HIGH_PROTEIN, VEGETARIAN, MEAL_PREP, QUICK, CLASSIC_GERMAN, MASS_GAIN }

data class Recipe(
    val key: String,
    val nameDe: String,
    val nameEn: String,
    val type: MealType,
    val minutes: Int,
    val tags: Set<RecipeTag>,
    /** Ingredient grams for ONE serving. */
    val items: List<Pair<String, Double>>,
    val stepsDe: List<String>,
    val stepsEn: List<String>
) {
    val vegetarian: Boolean get() = RecipeTag.VEGETARIAN in tags
    val nutrients: Nutrients by lazy {
        items.fold(Nutrients.ZERO) { acc, (k, g) -> acc + Foods.byKey.getValue(k).per100 * (g / 100.0) }
    }
}

/** 82 recipes, one serving each; salt, pepper, herbs and spices are free and not listed as ingredients. */
object Recipes {
    private fun r(
        key: String, de: String, en: String, type: MealType, min: Int, tags: Set<RecipeTag>,
        items: String, stepsDe: List<String>, stepsEn: List<String>
    ) = Recipe(
        key, de, en, type, min, tags,
        items.split(',').map { it.trim().split(':').let { (k, g) -> k to g.toDouble() } },
        stepsDe, stepsEn
    )

    private val HP = RecipeTag.HIGH_PROTEIN
    private val VEG = RecipeTag.VEGETARIAN
    private val PREP = RecipeTag.MEAL_PREP
    private val QUICK = RecipeTag.QUICK
    private val DE = RecipeTag.CLASSIC_GERMAN
    private val MASS = RecipeTag.MASS_GAIN

    val all: List<Recipe> = listOf(
        // ---------- breakfast ----------
        r("overnight_oats", "Protein-Overnight-Oats mit Beeren", "Protein overnight oats with berries", MealType.BREAKFAST, 5, setOf(HP, VEG, PREP, QUICK),
            "oats:80, milk:200, skyr:150, berries:100, chia:10, honey:10",
            listOf("Haferflocken, Chiasamen, Milch und Skyr in einem Glas verrühren.", "Honig unterziehen, die Beeren obenauf geben.", "Abgedeckt über Nacht in den Kühlschrank stellen."),
            listOf("Stir oats, chia, milk and skyr together in a jar.", "Fold in the honey and top with berries.", "Cover and refrigerate overnight.")),
        r("scrambled_eggs", "Rührei mit Spinat auf Vollkornbrot", "Scrambled eggs with spinach on rye", MealType.BREAKFAST, 10, setOf(HP, VEG, QUICK),
            "egg:180, egg_white:100, spinach:60, butter:5, bread_whole:90, tomato:100",
            listOf("Eier und Eiklar verquirlen, salzen und pfeffern.", "Spinat in Butter zusammenfallen lassen.", "Eimasse zugeben und bei mittlerer Hitze stocken lassen.", "Mit Brot und Tomatenscheiben servieren."),
            listOf("Whisk eggs and whites with salt and pepper.", "Wilt the spinach in butter.", "Add the eggs and set over medium heat.", "Serve with bread and sliced tomato.")),
        r("quark_bowl", "Quark-Bowl mit Beeren und Walnüssen", "Quark bowl with berries and walnuts", MealType.BREAKFAST, 5, setOf(HP, VEG, QUICK),
            "quark:250, milk:50, berries:125, oats:40, walnuts:15, honey:10",
            listOf("Quark mit Milch glatt rühren.", "Haferflocken und Beeren darübergeben.", "Mit gehackten Walnüssen und Honig abschließen."),
            listOf("Stir quark and milk until smooth.", "Top with oats and berries.", "Finish with chopped walnuts and honey.")),
        r("protein_pancakes", "Protein-Pfannkuchen mit Banane", "Protein pancakes with banana", MealType.BREAKFAST, 20, setOf(HP, VEG),
            "oats:60, egg:120, whey:30, banana:100, milk:80, berries:80, butter:5",
            listOf("Haferflocken fein mahlen, mit Eiern, Whey, halber Banane und Milch pürieren.", "In wenig Butter kleine Pfannkuchen von beiden Seiten backen.", "Mit restlicher Banane und Beeren servieren."),
            listOf("Blitz oats, then blend with eggs, whey, half the banana and milk.", "Cook small pancakes in a little butter on both sides.", "Serve with the rest of the banana and berries.")),
        r("skyr_apple", "Skyr mit Apfel, Zimt und Mandeln", "Skyr with apple, cinnamon and almonds", MealType.BREAKFAST, 5, setOf(HP, VEG, QUICK),
            "skyr:300, apple:150, oats:30, almonds:15",
            listOf("Apfel würfeln und mit Zimt mischen.", "Skyr in eine Schüssel geben, Apfel und Haferflocken darüber.", "Mit gehackten Mandeln bestreuen."),
            listOf("Dice the apple and toss with cinnamon.", "Spoon skyr into a bowl, add apple and oats.", "Sprinkle with chopped almonds.")),
        r("breakfast_burrito", "Frühstücks-Burrito", "Breakfast burrito", MealType.BREAKFAST, 15, setOf(HP, VEG),
            "tortilla:120, egg:120, egg_white:100, kidney:80, cheese:30, pepper:80, tomato_canned:60",
            listOf("Paprika anbraten, Bohnen und Tomaten zugeben und einkochen.", "Eier mit Eiklar als Rührei stocken lassen.", "Tortillas füllen, Käse darüber, einrollen und kurz in der Pfanne anrösten."),
            listOf("Sauté pepper, add beans and tomatoes and reduce.", "Scramble eggs with the whites.", "Fill the tortillas, add cheese, roll and toast briefly in the pan.")),
        r("pb_porridge", "Porridge mit Erdnussmus und Banane", "Peanut butter banana porridge", MealType.BREAKFAST, 10, setOf(VEG, MASS),
            "oats:90, milk:300, whey:25, banana:120, peanut_butter:20",
            listOf("Haferflocken in Milch 4–5 Minuten köcheln.", "Vom Herd nehmen und Whey einrühren (nicht mehr kochen).", "Mit Bananenscheiben und Erdnussmus toppen."),
            listOf("Simmer oats in milk for 4–5 minutes.", "Remove from heat and stir in whey (do not boil again).", "Top with sliced banana and peanut butter.")),
        r("bauernfruehstueck", "Bauernfrühstück", "German farmer's breakfast", MealType.BREAKFAST, 25, setOf(HP, DE),
            "potato:250, egg:180, ham:60, onion:50, butter:10, cucumber:100",
            listOf("Kartoffeln kochen, abkühlen lassen und in Scheiben schneiden (ideal: vom Vortag).", "Zwiebel und Schinkenwürfel in Butter anbraten, Kartoffeln goldbraun mitbraten.", "Verquirlte Eier darübergießen und stocken lassen.", "Mit Gurke und Schnittlauch servieren."),
            listOf("Boil, cool and slice the potatoes (day-old is best).", "Fry onion and diced ham in butter, then brown the potatoes.", "Pour the beaten eggs over and let them set.", "Serve with cucumber and chives.")),

        // ---------- main meals ----------
        r("chicken_rice_broccoli", "Hähnchen, Reis und Brokkoli", "Chicken, rice and broccoli", MealType.MAIN, 25, setOf(HP, PREP),
            "chicken:200, rice:90, broccoli:200, olive_oil:10, soy_sauce:15, garlic:5",
            listOf("Reis nach Packung garen.", "Hähnchen würfeln und im Öl mit Knoblauch scharf anbraten.", "Brokkoli 4 Minuten dämpfen.", "Alles mit Sojasauce abschmecken; hält 4 Tage im Kühlschrank."),
            listOf("Cook the rice as per the packet.", "Dice the chicken and sear in oil with garlic.", "Steam the broccoli for 4 minutes.", "Season with soy sauce; keeps 4 days refrigerated.")),
        r("chili_con_carne", "Chili con Carne", "Chili con carne", MealType.MAIN, 40, setOf(HP, PREP),
            "beef_mince:180, kidney:120, tomato_canned:200, onion:70, pepper:100, corn:60, rice:70, olive_oil:5, garlic:5",
            listOf("Zwiebel, Knoblauch und Hack krümelig anbraten, mit Kreuzkümmel, Paprika und Chili würzen.", "Paprika, Tomaten und Bohnen zugeben, 25 Minuten köcheln.", "Mais kurz mitziehen lassen.", "Mit Reis servieren."),
            listOf("Brown onion, garlic and mince; season with cumin, paprika and chilli.", "Add pepper, tomatoes and beans; simmer 25 minutes.", "Stir in the corn to warm through.", "Serve with rice.")),
        r("goulash", "Rindergulasch mit Kartoffeln", "Beef goulash with potatoes", MealType.MAIN, 120, setOf(HP, DE, PREP),
            "beef_chuck:200, onion:150, pepper:80, tomato_canned:60, potato:300, olive_oil:8, flour:5",
            listOf("Fleisch würfeln und portionsweise scharf anbraten.", "Zwiebeln (gleiche Menge wie Fleisch ist klassisch) goldbraun rösten, edelsüßes Paprikapulver und Mehl anschwitzen.", "Tomaten und Wasser zugeben, 90 Minuten schmoren; Paprika die letzten 20 Minuten.", "Mit Salzkartoffeln servieren."),
            listOf("Dice and sear the beef in batches.", "Brown the onions, toast sweet paprika and flour.", "Add tomatoes and water, braise 90 minutes; add pepper for the last 20.", "Serve with boiled potatoes.")),
        r("lentil_stew", "Linseneintopf mit Schinken", "Lentil stew with ham", MealType.MAIN, 45, setOf(DE, PREP),
            "lentils:90, carrot:100, potato:150, onion:60, ham:60, olive_oil:5",
            listOf("Zwiebel, Karotten und Schinkenwürfel in Öl anschwitzen.", "Linsen, Kartoffelwürfel und 600 ml Wasser zugeben.", "35 Minuten köcheln, mit Essig, Salz und Majoran abschmecken."),
            listOf("Sweat onion, carrots and diced ham in oil.", "Add lentils, diced potatoes and 600 ml water.", "Simmer 35 minutes; season with vinegar, salt and marjoram.")),
        r("kaesespaetzle", "Allgäuer Käsespätzle mit Röstzwiebeln", "Cheese spätzle with fried onions", MealType.MAIN, 25, setOf(VEG, DE, MASS),
            "spaetzle:250, cheese:60, onion:100, butter:10, lettuce:80",
            listOf("Zwiebeln in Ringe schneiden und in Butter langsam goldbraun rösten.", "Spätzle in einer Pfanne erhitzen, Käse schichtweise unterheben bis er zieht.", "Röstzwiebeln darüber, mit Salat servieren."),
            listOf("Slice the onions into rings and slowly brown them in butter.", "Heat the spätzle in a pan, fold in cheese in layers until stringy.", "Top with the onions, serve with salad.")),
        r("salmon_potatoes", "Lachs mit Kartoffeln und grünen Bohnen", "Salmon with potatoes and green beans", MealType.MAIN, 30, setOf(HP),
            "salmon:180, potato:300, green_beans:200, butter:8, lemon:10",
            listOf("Kartoffeln 20 Minuten kochen.", "Bohnen 6 Minuten blanchieren und in Butter schwenken.", "Lachs auf der Hautseite 4 Minuten braten, wenden, 2 Minuten.", "Mit Zitrone beträufeln."),
            listOf("Boil the potatoes for 20 minutes.", "Blanch the beans 6 minutes and toss in butter.", "Fry salmon skin-side 4 minutes, turn for 2 more.", "Drizzle with lemon.")),
        r("bolognese", "Spaghetti Bolognese", "Spaghetti Bolognese", MealType.MAIN, 40, setOf(HP, PREP),
            "pasta:110, beef_mince:170, tomato_canned:250, onion:60, carrot:60, parmesan:15, olive_oil:5, garlic:5",
            listOf("Zwiebel, Karotte und Knoblauch fein würfeln und in Öl anschwitzen.", "Hack zugeben und krümelig braten.", "Tomaten zugeben und 25 Minuten einkochen.", "Mit Nudeln und Parmesan servieren."),
            listOf("Finely dice onion, carrot and garlic; sweat in oil.", "Add the mince and brown.", "Add tomatoes and reduce 25 minutes.", "Serve with pasta and parmesan.")),
        r("schnitzel", "Schnitzel mit Kartoffel-Gurken-Salat", "Schnitzel with potato-cucumber salad", MealType.MAIN, 40, setOf(HP, DE),
            "pork_loin:200, flour:15, egg:30, breadcrumbs:35, olive_oil:15, potato:250, cucumber:80, onion:30, sour_cream:40",
            listOf("Kartoffeln kochen, pellen, in Scheiben schneiden; mit Zwiebel, Gurke, saurer Sahne, Essig und Salz mischen.", "Fleisch dünn klopfen, salzen, in Mehl, Ei und Paniermehl wenden.", "In heißem Öl je Seite 2–3 Minuten goldbraun backen.", "Mit Zitrone servieren."),
            listOf("Boil, peel and slice the potatoes; mix with onion, cucumber, sour cream, vinegar and salt.", "Pound the meat thin, season, coat in flour, egg and breadcrumbs.", "Fry in hot oil 2–3 minutes per side until golden.", "Serve with lemon.")),
        r("turkey_curry", "Puten-Curry mit Spinat", "Turkey curry with spinach", MealType.MAIN, 30, setOf(HP, PREP),
            "turkey:200, coconut_milk:80, tomato_canned:100, onion:60, pepper:100, spinach:60, rice:80",
            listOf("Reis garen.", "Pute in Streifen anbraten, herausnehmen.", "Zwiebel und Paprika mit Currypulver anschwitzen, Tomaten und Kokosmilch zugeben.", "Fleisch und Spinat 5 Minuten darin ziehen lassen."),
            listOf("Cook the rice.", "Sear turkey strips and set aside.", "Sweat onion and pepper with curry powder; add tomatoes and coconut milk.", "Return the turkey with spinach for 5 minutes.")),
        r("cod_couscous", "Kabeljau mit Gemüse-Couscous und Feta", "Cod with vegetable couscous and feta", MealType.MAIN, 25, setOf(HP, QUICK),
            "cod:220, couscous:80, zucchini:150, pepper:100, tomato:100, olive_oil:10, feta:30, lemon:10",
            listOf("Couscous mit kochendem Wasser übergießen und 5 Minuten quellen lassen.", "Zucchini und Paprika würfeln und in Öl braten, Tomaten zugeben.", "Kabeljau salzen und 3 Minuten je Seite braten.", "Gemüse unter den Couscous heben, Feta darüberbröseln, mit Zitrone servieren."),
            listOf("Pour boiling water over the couscous and rest 5 minutes.", "Dice and fry courgette and pepper, add tomatoes.", "Season the cod and fry 3 minutes per side.", "Fold vegetables into the couscous, crumble feta over, serve with lemon.")),
        r("chicken_wrap", "Hähnchen-Wraps mit Joghurtsauce", "Chicken wraps with yoghurt sauce", MealType.MAIN, 20, setOf(HP, QUICK),
            "tortilla:120, chicken:150, lettuce:50, tomato:80, cucumber:60, yogurt_greek:60, cheese:20",
            listOf("Hähnchen in Streifen mit Paprikapulver braten.", "Joghurt mit Knoblauch, Salz und Zitrone verrühren.", "Wraps mit Salat, Gemüse, Hähnchen, Sauce und Käse füllen und rollen."),
            listOf("Fry chicken strips with paprika.", "Stir yoghurt with garlic, salt and lemon.", "Fill wraps with leaves, vegetables, chicken, sauce and cheese; roll.")),
        r("tuna_pasta_salad", "Thunfisch-Nudelsalat", "Tuna pasta salad", MealType.MAIN, 20, setOf(HP, PREP, QUICK),
            "pasta:90, tuna:130, corn:60, pepper:80, yogurt_greek:80, cucumber:80, peas:50",
            listOf("Nudeln bissfest kochen, Erbsen die letzte Minute mitgaren, abschrecken.", "Paprika und Gurke würfeln.", "Alles mit Thunfisch, Mais und Joghurt mischen, abschmecken."),
            listOf("Cook pasta al dente, add peas for the last minute, rinse cold.", "Dice pepper and cucumber.", "Mix everything with tuna, corn and yoghurt; season.")),
        r("steak_sweet_potato", "Hüftsteak mit Süßkartoffel und Brokkoli", "Rump steak with sweet potato and broccoli", MealType.MAIN, 40, setOf(HP),
            "steak:220, sweet_potato:300, broccoli:200, butter:10",
            listOf("Süßkartoffel in Spalten bei 200 °C 30 Minuten backen.", "Steak trocken tupfen, sehr heiß je Seite 2–3 Minuten braten, 5 Minuten ruhen lassen.", "Brokkoli dämpfen und mit Butter servieren."),
            listOf("Roast sweet potato wedges at 200 °C for 30 minutes.", "Pat the steak dry, sear very hot 2–3 minutes per side, rest 5 minutes.", "Steam the broccoli and serve with butter.")),
        r("tofu_stirfry", "Tofu-Gemüse-Pfanne mit Erdnusssauce", "Tofu stir-fry with peanut sauce", MealType.MAIN, 25, setOf(VEG, HP),
            "tofu:200, rice:80, broccoli:150, pepper:100, carrot:60, soy_sauce:20, olive_oil:10, peanut_butter:15",
            listOf("Reis garen; Tofu würfeln und knusprig braten.", "Gemüse im Wok 4 Minuten pfannenrühren.", "Erdnussmus mit Sojasauce und etwas Wasser glatt rühren, alles darin schwenken."),
            listOf("Cook the rice; cube and crisp the tofu.", "Stir-fry the vegetables 4 minutes.", "Whisk peanut butter, soy sauce and a little water; toss everything in it.")),
        r("chickpea_curry", "Kichererbsen-Spinat-Curry", "Chickpea and spinach curry", MealType.MAIN, 30, setOf(VEG, PREP),
            "chickpeas:200, spinach:100, tomato_canned:200, coconut_milk:60, onion:60, rice:80, yogurt_greek:80",
            listOf("Zwiebel mit Garam Masala und Ingwer anschwitzen.", "Tomaten, Kokosmilch und Kichererbsen 15 Minuten köcheln.", "Spinat unterheben; mit Reis und Joghurt servieren."),
            listOf("Sweat onion with garam masala and ginger.", "Simmer tomatoes, coconut milk and chickpeas for 15 minutes.", "Fold in spinach; serve with rice and yoghurt.")),
        r("mince_rice_pan", "Hack-Reis-Pfanne mit Paprika", "Beef, rice and pepper skillet", MealType.MAIN, 30, setOf(HP, PREP),
            "beef_mince:180, rice:90, pepper:100, zucchini:100, onion:50, tomato_canned:100, olive_oil:5",
            listOf("Reis garen.", "Hack mit Zwiebel anbraten, Paprika und Zucchini mitbraten.", "Tomaten und Reis zugeben, 5 Minuten durchziehen lassen; portioniert 4 Tage haltbar."),
            listOf("Cook the rice.", "Brown the mince with onion, add pepper and courgette.", "Add tomatoes and rice, heat 5 minutes; keeps 4 days in portions.")),
        r("geschnetzeltes", "Hähnchen-Geschnetzeltes mit Champignons", "Chicken with creamy mushrooms", MealType.MAIN, 25, setOf(HP, DE),
            "chicken:200, mushroom:150, onion:50, sour_cream:60, rice:80, olive_oil:8",
            listOf("Reis garen.", "Hähnchen in Streifen scharf anbraten, herausnehmen.", "Zwiebel und Champignons braten, mit wenig Wasser ablöschen.", "Saure Sahne einrühren (nicht kochen), Fleisch zurückgeben, mit Petersilie servieren."),
            listOf("Cook the rice.", "Sear chicken strips, set aside.", "Fry onion and mushrooms, deglaze with a little water.", "Stir in sour cream (do not boil), return the chicken, serve with parsley.")),
        r("salmon_bowl", "Lachs-Reis-Bowl", "Salmon rice bowl", MealType.MAIN, 20, setOf(HP, QUICK),
            "salmon:150, rice:80, avocado:60, cucumber:80, peas:50, soy_sauce:15, carrot:50",
            listOf("Reis garen und leicht mit Reisessig würzen.", "Lachs würfeln und kurz braten oder im Ofen garen.", "Mit Gurke, geraspelter Karotte, Erbsen und Avocado anrichten, Sojasauce darüber."),
            listOf("Cook the rice and season lightly with rice vinegar.", "Cube and sear or bake the salmon.", "Arrange with cucumber, grated carrot, peas and avocado; drizzle soy sauce.")),
        r("veggie_omelette", "Gemüse-Omelett mit Feta", "Vegetable omelette with feta", MealType.MAIN, 15, setOf(HP, VEG, QUICK),
            "egg:180, egg_white:150, mushroom:100, spinach:80, feta:40, bread_whole:60",
            listOf("Champignons braten, Spinat zusammenfallen lassen.", "Eier mit Eiklar verquirlen und darübergießen.", "Feta darüberbröseln, bei geringer Hitze abgedeckt stocken lassen; mit Brot servieren."),
            listOf("Fry mushrooms, wilt spinach.", "Whisk eggs and whites and pour over.", "Crumble feta over, cover and set on low heat; serve with bread.")),
        r("pork_sauerkraut", "Schweinelende mit Sauerkraut und Kartoffeln", "Pork loin with sauerkraut and potatoes", MealType.MAIN, 35, setOf(HP, DE),
            "pork_loin:200, potato:300, sauerkraut:200, onion:30, butter:8",
            listOf("Kartoffeln kochen.", "Sauerkraut mit Zwiebel, Lorbeer und Wacholder 20 Minuten köcheln.", "Lende in Medaillons schneiden, 3 Minuten je Seite braten, kurz ruhen lassen."),
            listOf("Boil the potatoes.", "Simmer sauerkraut with onion, bay and juniper for 20 minutes.", "Slice the loin into medallions, fry 3 minutes per side, rest briefly.")),
        r("meatballs_pasta", "Hackbällchen in Tomatensauce mit Pasta", "Meatballs in tomato sauce with pasta", MealType.MAIN, 35, setOf(HP, PREP),
            "beef_mince:170, egg:30, breadcrumbs:20, pasta:90, tomato_canned:250, parmesan:10, olive_oil:5",
            listOf("Hack mit Ei, Paniermehl, Salz und Oregano verkneten, walnussgroße Bällchen formen.", "Bällchen rundum anbraten.", "Tomaten zugeben, 15 Minuten köcheln.", "Mit Nudeln und Parmesan servieren."),
            listOf("Mix mince with egg, breadcrumbs, salt and oregano; roll walnut-sized balls.", "Brown the meatballs all over.", "Add tomatoes and simmer 15 minutes.", "Serve with pasta and parmesan.")),
        r("chicken_traybake", "Hähnchen-Süßkartoffel-Blech", "Chicken and sweet potato traybake", MealType.MAIN, 45, setOf(HP, PREP),
            "chicken_thigh:220, sweet_potato:250, pepper:100, onion:60, olive_oil:10",
            listOf("Ofen auf 210 °C vorheizen.", "Süßkartoffel, Paprika und Zwiebel grob schneiden, mit Öl und Paprikapulver mischen.", "Hähnchenkeulen darauflegen und 35–40 Minuten backen (Kerntemperatur ≥ 75 °C)."),
            listOf("Preheat the oven to 210 °C.", "Chop sweet potato, pepper and onion; toss with oil and paprika.", "Lay the thighs on top and roast 35–40 minutes (core ≥ 75 °C).")),
        r("shakshuka", "Shakshuka mit Feta und Brot", "Shakshuka with feta and bread", MealType.MAIN, 25, setOf(VEG, HP),
            "egg:180, tomato_canned:250, pepper:120, onion:60, feta:30, bread_whole:80, olive_oil:8",
            listOf("Zwiebel und Paprika in Öl weich braten, Kreuzkümmel zugeben.", "Tomaten 10 Minuten einkochen.", "Mulden formen, Eier hineinschlagen und abgedeckt 6–8 Minuten stocken lassen.", "Feta darüber, mit Brot servieren."),
            listOf("Soften onion and pepper in oil, add cumin.", "Reduce the tomatoes for 10 minutes.", "Make wells, crack in the eggs, cover and set 6–8 minutes.", "Top with feta, serve with bread.")),

        // ---------- snacks ----------
        r("protein_shake", "Bananen-Hafer-Proteinshake", "Banana oat protein shake", MealType.SNACK, 3, setOf(HP, VEG, QUICK),
            "milk:300, whey:35, banana:120, oats:30, peanut_butter:15",
            listOf("Alle Zutaten 30 Sekunden im Mixer pürieren."),
            listOf("Blend everything for 30 seconds.")),
        r("mass_shake", "Masse-Shake für Aufbauphasen", "Mass-gainer shake", MealType.SNACK, 3, setOf(VEG, MASS, QUICK),
            "milk:500, oats:80, whey:40, peanut_butter:30, banana:120, honey:15",
            listOf("Haferflocken im Mixer fein mahlen.", "Übrige Zutaten zugeben und cremig pürieren."),
            listOf("Blitz the oats fine in the blender.", "Add the rest and blend until creamy.")),
        r("cottage_mango", "Hüttenkäse mit Mango", "Cottage cheese with mango", MealType.SNACK, 3, setOf(HP, VEG, QUICK),
            "cottage:250, mango:120, almonds:10",
            listOf("Mango antauen lassen, mit Hüttenkäse mischen, Mandeln darüber."),
            listOf("Thaw the mango slightly, mix with cottage cheese, top with almonds.")),
        r("skyr_berries", "Skyr mit Beeren und Honig", "Skyr with berries and honey", MealType.SNACK, 3, setOf(HP, VEG, QUICK),
            "skyr:250, berries:100, honey:10",
            listOf("Skyr mit Beeren anrichten, mit Honig beträufeln."),
            listOf("Top skyr with berries and drizzle with honey.")),
        r("tuna_bread", "Thunfisch-Brot mit Gurke", "Tuna on rye with cucumber", MealType.SNACK, 5, setOf(HP, QUICK),
            "bread_whole:90, tuna:100, yogurt_greek:40, cucumber:60",
            listOf("Thunfisch mit Joghurt, Pfeffer und Zitrone verrühren.", "Auf das Brot streichen und mit Gurkenscheiben belegen."),
            listOf("Mix tuna with yoghurt, pepper and lemon.", "Spread on the bread and top with cucumber.")),
        r("apple_nuts", "Apfel mit Walnüssen und Mandeln", "Apple with walnuts and almonds", MealType.SNACK, 1, setOf(VEG, QUICK),
            "apple:150, walnuts:20, almonds:15",
            listOf("Apfel in Spalten schneiden und mit den Nüssen essen."),
            listOf("Slice the apple and eat with the nuts.")),
        r("chocolate_pudding", "Schoko-Protein-Pudding", "Chocolate protein pudding", MealType.SNACK, 5, setOf(HP, VEG, QUICK),
            "quark:250, cocoa:10, whey:20, milk:60, banana:60, dark_chocolate:10",
            listOf("Quark, Kakao, Whey, Milch und Banane glatt pürieren.", "Mit gehackter Schokolade bestreuen; kalt noch cremiger."),
            listOf("Blend quark, cocoa, whey, milk and banana until smooth.", "Sprinkle with chopped chocolate; creamier when chilled.")),
        r("egg_ham_bread", "Eier und Schinken auf Vollkornbrot", "Eggs and ham on rye", MealType.SNACK, 12, setOf(HP, DE),
            "egg:120, ham:50, bread_whole:60, cucumber:60",
            listOf("Eier 9 Minuten hart kochen, abschrecken.", "Brot mit Schinken, Eischeiben und Gurke belegen."),
            listOf("Hard-boil the eggs 9 minutes, cool in water.", "Top the bread with ham, sliced egg and cucumber.")),
        r("greek_yogurt_chia", "Joghurt mit Chia und Beeren", "Greek yoghurt with chia and berries", MealType.SNACK, 5, setOf(HP, VEG, QUICK),
            "yogurt_greek:250, chia:15, berries:100, honey:10",
            listOf("Joghurt mit Chiasamen verrühren, 10 Minuten quellen lassen.", "Beeren und Honig darübergeben."),
            listOf("Stir chia into the yoghurt and let it swell for 10 minutes.", "Top with berries and honey.")),
        r("rice_pudding", "Protein-Milchreis mit Zimt", "Protein rice pudding with cinnamon", MealType.SNACK, 35, setOf(VEG, PREP),
            "rice:50, milk:250, whey:20, apple:100, honey:10",
            listOf("Reis in Milch bei kleiner Hitze 30 Minuten quellen lassen, dabei rühren.", "Etwas abkühlen lassen, Whey einrühren.", "Mit Apfelkompott, Zimt und Honig servieren."),
            listOf("Simmer rice in milk on low heat for 30 minutes, stirring.", "Cool slightly and stir in whey.", "Serve with stewed apple, cinnamon and honey.")),
        // ---------- P4: further recipes ----------
        r("quark_pancakes", "Quarkkeulchen mit Apfelmus", "Quark fritters with apple sauce", MealType.BREAKFAST, 20, setOf(HP, VEG, DE),
            "quark:250, egg:60, oats:50, apple:150, butter:8, honey:10",
            listOf("Quark, Ei, Haferflocken und etwas Zimt zu einem Teig verrühren, 10 Minuten quellen lassen.", "Kleine Taler formen und in Butter von beiden Seiten goldbraun braten.", "Apfel klein schneiden, kurz weich dünsten und mit Honig servieren."),
            listOf("Mix quark, egg, oats and a little cinnamon into a batter and rest 10 minutes.", "Shape small patties and fry golden on both sides in butter.", "Dice the apple, soften briefly and serve with honey.")),
        r("egg_muffins", "Eier-Muffins mit Gemüse", "Egg muffins with vegetables", MealType.BREAKFAST, 30, setOf(HP, VEG, PREP),
            "egg:180, egg_white:120, pepper:80, spinach:60, gouda:40, tomato:60",
            listOf("Ofen auf 180 °C vorheizen, Muffinform fetten.", "Gemüse klein würfeln und auf die Mulden verteilen.", "Eier mit Eiklar verquirlen, würzen, darübergießen und mit Käse bestreuen.", "20 Minuten backen; hält drei Tage im Kühlschrank."),
            listOf("Preheat the oven to 180 °C and grease a muffin tin.", "Dice the vegetables and spread them into the cups.", "Whisk eggs with the whites, season, pour over and top with cheese.", "Bake 20 minutes; keeps three days refrigerated.")),
        r("bircher", "Bircher-Müsli mit Birne", "Bircher muesli with pear", MealType.BREAKFAST, 10, setOf(VEG, PREP, QUICK),
            "oats:70, buttermilk:150, skyr:120, pear:150, hazelnuts:15, raisins:20",
            listOf("Haferflocken mit Buttermilch und Skyr verrühren.", "Birne grob raspeln und unterheben, Rosinen zugeben.", "Mindestens 30 Minuten quellen lassen, mit Haselnüssen bestreuen."),
            listOf("Stir oats with buttermilk and skyr.", "Coarsely grate the pear, fold it in and add the raisins.", "Rest at least 30 minutes and scatter hazelnuts on top.")),
        r("tofu_scramble", "Tofu-Rührei mit Kurkuma", "Turmeric tofu scramble", MealType.BREAKFAST, 15, setOf(VEG, HP, QUICK),
            "tofu:200, pepper:80, spinach:60, rapeseed_oil:10, bread_whole:80, tomato:80",
            listOf("Tofu mit der Gabel zerbröseln und mit Kurkuma, Paprikapulver und Salz würzen.", "Paprika in Öl anbraten, Tofu zugeben und 5 Minuten braten.", "Spinat unterheben und mit Brot und Tomaten servieren."),
            listOf("Crumble the tofu with a fork and season with turmeric, paprika and salt.", "Fry the pepper in oil, add the tofu and cook 5 minutes.", "Fold in the spinach and serve with bread and tomatoes.")),
        r("rouladen", "Rinderrouladen mit Rotkohl", "Beef roulades with red cabbage", MealType.MAIN, 110, setOf(HP, DE),
            "steak:200, bacon:25, onion:60, mustard:10, cabbage:200, potato:250, rapeseed_oil:8, tomato_paste:10",
            listOf("Fleisch flach klopfen, mit Senf bestreichen, mit Speck, Zwiebel und Gurke belegen, aufrollen und feststecken.", "Rouladen rundum scharf anbraten, Tomatenmark kurz mitrösten, mit Wasser ablöschen.", "90 Minuten schmoren.", "Kohl mit Apfel und Essig weich dünsten, dazu Salzkartoffeln."),
            listOf("Flatten the meat, spread mustard, lay on bacon, onion and gherkin, roll up and pin.", "Sear the roulades, toast the tomato paste, deglaze with water.", "Braise for 90 minutes.", "Soften the cabbage with apple and vinegar; serve with boiled potatoes.")),
        r("koenigsberger", "Königsberger Klopse", "Königsberger Klopse", MealType.MAIN, 45, setOf(HP, DE),
            "beef_mince:180, egg:25, breadcrumbs:20, onion:50, sour_cream:60, flour:10, potato:250, lemon:10",
            listOf("Hack mit Ei, Paniermehl, Zwiebel und Salz verkneten, Klöße formen.", "In leicht siedender Brühe 15 Minuten ziehen lassen.", "Aus Mehl, Brühe und saurer Sahne eine Sauce rühren, mit Kapern und Zitrone abschmecken.", "Mit Salzkartoffeln servieren."),
            listOf("Mix mince with egg, breadcrumbs, onion and salt; shape dumplings.", "Poach 15 minutes in gently simmering stock.", "Make a sauce from flour, stock and sour cream; season with capers and lemon.", "Serve with boiled potatoes.")),
        r("gulaschsuppe", "Gulaschsuppe", "Goulash soup", MealType.MAIN, 70, setOf(HP, DE, PREP),
            "beef_chuck:160, potato:200, pepper:100, onion:100, tomato_paste:20, rapeseed_oil:8, carrot:60",
            listOf("Fleisch würfeln und scharf anbraten, Zwiebeln mitrösten.", "Paprikapulver und Tomatenmark kurz anschwitzen, mit 700 ml Wasser auffüllen.", "45 Minuten köcheln, dann Kartoffeln, Karotten und Paprika 20 Minuten mitgaren."),
            listOf("Dice and sear the beef, then brown the onions.", "Toast paprika and tomato paste, add 700 ml water.", "Simmer 45 minutes, then add potatoes, carrots and pepper for 20 minutes.")),
        r("maultaschen", "Maultaschen in der Brühe", "Maultaschen in broth", MealType.MAIN, 25, setOf(DE, QUICK),
            "flour:120, egg:60, pork_loin:120, spinach:80, onion:40, stock_cube:8",
            listOf("Aus Mehl und Ei einen Nudelteig kneten, 20 Minuten ruhen lassen und dünn ausrollen.", "Fleisch, blanchierten Spinat und Zwiebel fein hacken, würzen und als Füllung aufsetzen.", "Teig falten, Taschen schneiden und 8 Minuten in Brühe ziehen lassen."),
            listOf("Knead a pasta dough from flour and egg, rest 20 minutes and roll thin.", "Finely chop meat, blanched spinach and onion; season and place as filling.", "Fold, cut the parcels and poach 8 minutes in broth.")),
        r("kohlrouladen", "Kohlrouladen", "Stuffed cabbage rolls", MealType.MAIN, 70, setOf(HP, DE, PREP),
            "cabbage:250, beef_mince:170, rice:40, onion:50, egg:25, tomato_canned:150, rapeseed_oil:8",
            listOf("Kohlblätter 3 Minuten blanchieren.", "Hack mit vorgekochtem Reis, Zwiebel, Ei und Gewürzen mischen.", "Füllung einrollen, Röllchen anbraten, Tomaten zugeben und 40 Minuten schmoren."),
            listOf("Blanch the cabbage leaves for 3 minutes.", "Mix mince with pre-cooked rice, onion, egg and seasoning.", "Roll up, sear the parcels, add tomatoes and braise 40 minutes.")),
        r("linsen_spaetzle", "Linsen mit Spätzle", "Lentils with spätzle", MealType.MAIN, 45, setOf(DE, PREP),
            "lentils:90, spaetzle:180, carrot:80, onion:50, sausage:60, vinegar:10",
            listOf("Zwiebel und Karotte anschwitzen, Linsen und 600 ml Wasser zugeben.", "35 Minuten köcheln, mit Essig, Salz und Lorbeer abschmecken.", "Spätzle erhitzen, Wurst in Scheiben kurz anbraten und alles zusammen anrichten."),
            listOf("Sweat onion and carrot, add lentils and 600 ml water.", "Simmer 35 minutes; season with vinegar, salt and bay.", "Heat the spätzle, fry the sliced sausage and serve together.")),
        r("fish_curry", "Fischcurry mit Kokosmilch", "Fish curry with coconut milk", MealType.MAIN, 25, setOf(HP, QUICK),
            "pollock:220, coconut_milk:100, tomato_canned:120, onion:60, ginger:8, rice:80, spinach:60",
            listOf("Reis garen.", "Zwiebel und Ingwer mit Currypulver anschwitzen.", "Tomaten und Kokosmilch zugeben, 10 Minuten einkochen.", "Fisch würfeln, 5 Minuten darin gar ziehen lassen, Spinat unterheben."),
            listOf("Cook the rice.", "Sweat onion and ginger with curry powder.", "Add tomatoes and coconut milk and reduce 10 minutes.", "Cube the fish, poach 5 minutes and fold in the spinach.")),
        r("seitan_stirfry", "Seitan-Pfanne mit Brokkoli", "Seitan stir-fry with broccoli", MealType.MAIN, 20, setOf(VEG, HP, QUICK),
            "seitan:180, broccoli:200, pepper:80, soy_sauce:20, rapeseed_oil:10, rice:80, ginger:8",
            listOf("Reis garen.", "Seitan in Streifen scharf anbraten und herausnehmen.", "Gemüse mit Ingwer 4 Minuten pfannenrühren, Seitan zurückgeben, mit Sojasauce ablöschen."),
            listOf("Cook the rice.", "Sear seitan strips and set aside.", "Stir-fry the vegetables with ginger for 4 minutes, return the seitan and deglaze with soy sauce.")),
        r("tempeh_bowl", "Tempeh-Bowl mit Quinoa", "Tempeh bowl with quinoa", MealType.MAIN, 25, setOf(VEG, HP, PREP),
            "tempeh:150, quinoa:80, beetroot:100, carrot:80, kale:60, tahini:20, lemon:10",
            listOf("Quinoa 15 Minuten garen.", "Tempeh in Scheiben mit Sojasauce braten.", "Rote Bete und Karotte raspeln, Grünkohl kurz dünsten.", "Tahini mit Zitrone und Wasser zu einer Sauce rühren und darübergeben."),
            listOf("Cook the quinoa for 15 minutes.", "Fry sliced tempeh with soy sauce.", "Grate beetroot and carrot, briefly steam the kale.", "Whisk tahini with lemon and water into a dressing and pour over.")),
        r("lamb_couscous", "Lamm mit Couscous und Ofengemüse", "Lamb with couscous and roast vegetables", MealType.MAIN, 40, setOf(HP),
            "lamb:200, couscous:80, aubergine:150, pepper:100, olive_oil:12, yogurt_greek:60",
            listOf("Gemüse mit Öl und Kreuzkümmel bei 210 °C 25 Minuten rösten.", "Couscous mit kochendem Wasser übergießen und quellen lassen.", "Lamm 3 Minuten je Seite braten, ruhen lassen und aufschneiden.", "Mit Joghurt und Minze servieren."),
            listOf("Roast the vegetables with oil and cumin at 210 °C for 25 minutes.", "Pour boiling water over the couscous and let it swell.", "Fry the lamb 3 minutes per side, rest and slice.", "Serve with yoghurt and mint.")),
        r("pork_stirfry_noodles", "Schweinefleisch-Nudel-Pfanne", "Pork and noodle stir-fry", MealType.MAIN, 25, setOf(HP, QUICK),
            "pork_loin:180, pasta:100, cabbage:120, carrot:80, soy_sauce:20, rapeseed_oil:10, garlic:6",
            listOf("Nudeln bissfest kochen.", "Fleisch in Streifen scharf anbraten, herausnehmen.", "Kohl, Karotte und Knoblauch 4 Minuten braten, Nudeln und Fleisch zugeben, mit Sojasauce abschmecken."),
            listOf("Cook the pasta al dente.", "Sear pork strips and set aside.", "Fry cabbage, carrot and garlic 4 minutes, add pasta and pork and season with soy sauce.")),
        r("chicken_soup", "Hühnersuppe mit Gemüse", "Chicken soup with vegetables", MealType.MAIN, 50, setOf(HP, PREP),
            "chicken_thigh:200, carrot:100, leek:80, celeriac:80, barley:50, stock_cube:8",
            listOf("Hähnchen in 1 l Wasser mit Brühe 30 Minuten simmern lassen.", "Fleisch herausnehmen, zerpflücken.", "Gemüsewürfel und Graupen 20 Minuten mitgaren, Fleisch zurückgeben."),
            listOf("Simmer the chicken in 1 l of stock for 30 minutes.", "Remove and shred the meat.", "Cook diced vegetables and barley for 20 minutes, then return the meat.")),
        r("pumpkin_soup", "Kürbissuppe mit Kernen", "Pumpkin soup with seeds", MealType.MAIN, 30, setOf(VEG, PREP),
            "pumpkin:400, potato:120, onion:60, coconut_milk:60, stock_cube:8, pumpkin_seeds:20, ginger:8",
            listOf("Kürbis, Kartoffel, Zwiebel und Ingwer würfeln und anschwitzen.", "Mit 600 ml Brühe aufgießen und 20 Minuten kochen.", "Fein pürieren, Kokosmilch einrühren, mit gerösteten Kernen bestreuen."),
            listOf("Dice and sweat pumpkin, potato, onion and ginger.", "Add 600 ml stock and boil 20 minutes.", "Blend smooth, stir in coconut milk and scatter toasted seeds.")),
        r("beef_stew_barley", "Rindergeschnetzeltes mit Graupen", "Beef and barley stew", MealType.MAIN, 80, setOf(HP, PREP),
            "beef_chuck:180, barley:70, carrot:100, mushroom:120, onion:60, tomato_paste:15, rapeseed_oil:8",
            listOf("Fleisch anbraten, Zwiebeln und Pilze mitrösten.", "Tomatenmark anschwitzen, 700 ml Wasser zugeben, 45 Minuten schmoren.", "Graupen und Karotten zugeben und 25 Minuten fertig garen."),
            listOf("Sear the beef, then brown onions and mushrooms.", "Toast the tomato paste, add 700 ml water and braise 45 minutes.", "Add barley and carrots and cook for a further 25 minutes.")),
        r("salmon_pasta", "Lachs-Pasta mit Spinat", "Salmon pasta with spinach", MealType.MAIN, 20, setOf(HP, QUICK),
            "salmon:160, pasta:100, spinach:100, cream:40, parmesan:15, lemon:10, garlic:5",
            listOf("Nudeln kochen und etwas Nudelwasser aufheben.", "Lachs würfeln und 3 Minuten braten, Knoblauch zugeben.", "Spinat, Sahne und Nudelwasser zugeben, Nudeln unterheben, mit Zitrone und Parmesan abschmecken."),
            listOf("Cook the pasta and reserve some cooking water.", "Cube and fry the salmon 3 minutes, add garlic.", "Add spinach, cream and pasta water, fold in the pasta and finish with lemon and parmesan.")),
        r("shrimp_rice", "Garnelen mit Reis und Gemüse", "Prawns with rice and vegetables", MealType.MAIN, 20, setOf(HP, QUICK),
            "shrimp:200, rice:80, pepper:100, peas:60, garlic:6, olive_oil:10, lemon:10",
            listOf("Reis garen.", "Garnelen mit Knoblauch 3 Minuten braten und herausnehmen.", "Paprika und Erbsen 4 Minuten braten, alles mischen und mit Zitrone abschmecken."),
            listOf("Cook the rice.", "Fry the prawns with garlic for 3 minutes and set aside.", "Fry pepper and peas 4 minutes, combine everything and finish with lemon.")),
        r("liver_onions", "Leber mit Zwiebeln und Kartoffelpüree", "Liver with onions and mash", MealType.MAIN, 30, setOf(HP, DE),
            "liver:180, onion:120, potato:300, milk:60, butter:10, flour:10, apple:80",
            listOf("Kartoffeln kochen und mit Milch und Butter stampfen.", "Zwiebeln und Apfelspalten goldbraun braten.", "Leber in Mehl wenden und je Seite 2 Minuten braten; erst danach salzen."),
            listOf("Boil the potatoes and mash with milk and butter.", "Fry onions and apple wedges until golden.", "Dust the liver in flour and fry 2 minutes per side; salt only afterwards.")),
        r("chili_sin_carne", "Chili sin Carne", "Chilli sin carne", MealType.MAIN, 35, setOf(VEG, PREP),
            "soy_mince:50, kidney:150, white_beans:100, tomato_canned:250, pepper:100, corn:60, onion:60, rice:70",
            listOf("Sojaschnetzel in heißem Wasser 10 Minuten quellen lassen und abtropfen.", "Zwiebel und Paprika anbraten, Schnetzel mit Kreuzkümmel und Chili zugeben.", "Tomaten und Bohnen 20 Minuten köcheln, Mais zuletzt zugeben.", "Mit Reis servieren."),
            listOf("Soak the soy mince in hot water for 10 minutes and drain.", "Fry onion and pepper, add the mince with cumin and chilli.", "Simmer tomatoes and beans 20 minutes, add corn at the end.", "Serve with rice.")),
        r("pizza_protein", "Protein-Pizza mit Thunfisch", "Protein pizza with tuna", MealType.MAIN, 30, setOf(HP),
            "flour:90, quark:80, egg:25, tomato_paste:30, mozzarella:60, tuna:100, onion:40",
            listOf("Mehl, Quark, Ei, Backpulver und Salz zu einem Teig kneten und ausrollen.", "Mit Tomatenmark bestreichen, belegen und mit Mozzarella bestreuen.", "Bei 220 °C 15 Minuten backen."),
            listOf("Knead flour, quark, egg, baking powder and salt into a dough and roll out.", "Spread tomato paste, add the toppings and scatter mozzarella.", "Bake at 220 °C for 15 minutes.")),
        r("stuffed_peppers", "Gefüllte Paprika", "Stuffed peppers", MealType.MAIN, 50, setOf(HP, PREP),
            "pepper:250, chicken_mince:180, rice:60, tomato_canned:150, onion:50, feta:30",
            listOf("Reis vorgaren. Paprika halbieren und entkernen.", "Hack mit Zwiebel anbraten, Reis und Kräuter untermischen.", "Paprika füllen, Tomaten angießen und bei 200 °C 30 Minuten backen, Feta zuletzt."),
            listOf("Pre-cook the rice. Halve and deseed the peppers.", "Brown the mince with onion, mix in rice and herbs.", "Fill the peppers, pour tomatoes around and bake at 200 °C for 30 minutes; add feta at the end.")),
        r("gnocchi_pan", "Gnocchi-Pfanne mit Hähnchen", "Gnocchi pan with chicken", MealType.MAIN, 20, setOf(HP, QUICK),
            "gnocchi:250, chicken:180, zucchini:120, tomato:120, cream_cheese:40, olive_oil:10",
            listOf("Gnocchi in der Pfanne mit Öl knusprig braten und herausnehmen.", "Hähnchen würfeln und anbraten, Zucchini und Tomaten zugeben.", "Frischkäse mit etwas Wasser einrühren und die Gnocchi unterheben."),
            listOf("Crisp the gnocchi in oil and set aside.", "Dice and fry the chicken, add courgette and tomatoes.", "Stir in cream cheese with a little water and fold the gnocchi back in.")),
        r("lentil_salad", "Linsensalat mit Feta", "Lentil salad with feta", MealType.MAIN, 35, setOf(VEG, PREP),
            "lentils:80, cucumber:100, tomato:120, onion:40, feta:50, olive_oil:12, lemon:15",
            listOf("Linsen 25 Minuten garen und abkühlen lassen.", "Gemüse würfeln, mit Öl, Zitrone, Salz und Petersilie mischen.", "Feta darüberbröseln."),
            listOf("Cook the lentils for 25 minutes and let them cool.", "Dice the vegetables and toss with oil, lemon, salt and parsley.", "Crumble the feta over.")),
        r("herring_potatoes", "Matjes mit Kartoffeln und Apfel", "Herring with potatoes and apple", MealType.MAIN, 30, setOf(HP, DE),
            "herring:150, potato:300, apple:100, onion:50, sour_cream:60, cucumber:80",
            listOf("Kartoffeln kochen.", "Apfel, Zwiebel und Gurke würfeln und mit saurer Sahne mischen.", "Hering darauf anrichten und mit Dill bestreuen."),
            listOf("Boil the potatoes.", "Dice apple, onion and cucumber and mix with sour cream.", "Arrange the herring on top and scatter dill.")),
        r("mackerel_salad", "Makrelensalat auf Brot", "Mackerel salad on bread", MealType.MAIN, 10, setOf(HP, QUICK),
            "mackerel:150, bread_whole:90, yogurt_greek:50, onion:30, lemon:10, lettuce:60",
            listOf("Makrele zerpflücken und mit Joghurt, Zwiebel und Zitrone mischen.", "Auf Brot mit Salatblättern anrichten."),
            listOf("Flake the mackerel and mix with yoghurt, onion and lemon.", "Serve on bread with salad leaves.")),
        r("beef_rice_bowl", "Rindfleisch-Reis-Bowl", "Beef rice bowl", MealType.MAIN, 25, setOf(HP, PREP),
            "steak:200, rice_basmati:85, cabbage:100, carrot:80, soy_sauce:20, rapeseed_oil:10, egg:50",
            listOf("Reis garen und Ei als Spiegelei braten.", "Rind in Streifen sehr heiß 2 Minuten braten.", "Kohl und Karotte kurz anbraten, alles mit Sojasauce in einer Schüssel anrichten."),
            listOf("Cook the rice and fry an egg.", "Sear the beef strips very hot for 2 minutes.", "Briefly fry cabbage and carrot and assemble the bowl with soy sauce.")),
        r("bulgur_pan", "Bulgur-Pfanne mit Kichererbsen", "Bulgur pan with chickpeas", MealType.MAIN, 25, setOf(VEG, PREP, QUICK),
            "bulgur:90, chickpeas:150, tomato_paste:25, pepper:100, onion:60, olive_oil:12, lemon:10",
            listOf("Zwiebel und Paprika in Öl anbraten, Tomatenmark kurz mitrösten.", "Bulgur, Kichererbsen und 250 ml Wasser zugeben.", "Zugedeckt 12 Minuten quellen lassen, mit Zitrone abschmecken."),
            listOf("Fry onion and pepper in oil and toast the tomato paste.", "Add bulgur, chickpeas and 250 ml water.", "Cover and let it swell for 12 minutes; finish with lemon.")),
        r("polenta_mushroom", "Polenta mit Pilzragout", "Polenta with mushroom ragout", MealType.MAIN, 30, setOf(VEG),
            "polenta:80, milk:150, parmesan:25, mushroom:250, onion:50, cream:40, olive_oil:10",
            listOf("Polenta in Milch und Wasser unter Rühren 10 Minuten quellen lassen, Parmesan einrühren.", "Pilze und Zwiebel scharf anbraten, mit Sahne ablöschen.", "Ragout auf die Polenta geben."),
            listOf("Simmer the polenta in milk and water for 10 minutes, stirring; add parmesan.", "Sear mushrooms and onion, deglaze with cream.", "Spoon the ragout over the polenta.")),
        r("turkey_meatballs", "Putenbällchen mit Ofengemüse", "Turkey meatballs with roast vegetables", MealType.MAIN, 40, setOf(HP, PREP),
            "turkey:200, egg:25, breadcrumbs:20, zucchini:150, pepper:100, sweet_potato:200, olive_oil:12",
            listOf("Gemüse mit Öl bei 210 °C 25 Minuten rösten.", "Pute mit Ei, Paniermehl und Kräutern mischen, Bällchen formen.", "Bällchen die letzten 15 Minuten mitbacken."),
            listOf("Roast the vegetables with oil at 210 °C for 25 minutes.", "Mix turkey with egg, breadcrumbs and herbs; shape balls.", "Bake the balls alongside for the last 15 minutes.")),
        r("spinach_dal", "Spinat-Dal mit Reis", "Spinach dal with rice", MealType.MAIN, 35, setOf(VEG, PREP),
            "split_peas:90, spinach:120, tomato_canned:150, onion:60, ginger:8, rapeseed_oil:10, rice:70",
            listOf("Erbsen mit 600 ml Wasser 25 Minuten weich kochen.", "Zwiebel, Ingwer und Gewürze in Öl anbraten, Tomaten zugeben.", "Alles mischen, Spinat unterheben und mit Reis servieren."),
            listOf("Simmer the split peas in 600 ml water for 25 minutes.", "Fry onion, ginger and spices in oil; add tomatoes.", "Combine, fold in the spinach and serve with rice.")),
        r("cod_potato_gratin", "Kabeljau-Kartoffel-Gratin", "Cod and potato gratin", MealType.MAIN, 50, setOf(HP),
            "cod:200, potato:300, leek:100, cream:50, milk:100, gouda:40",
            listOf("Kartoffeln in dünne Scheiben schneiden, Lauch in Ringe.", "Alles schichten, Fisch dazwischen legen.", "Milch und Sahne angießen, Käse darüber, bei 190 °C 35 Minuten backen."),
            listOf("Slice the potatoes thinly and the leek into rings.", "Layer everything with the fish in between.", "Pour over milk and cream, top with cheese and bake at 190 °C for 35 minutes.")),
        r("protein_waffles", "Protein-Waffeln", "Protein waffles", MealType.BREAKFAST, 20, setOf(HP, VEG),
            "oats:60, quark:120, egg:120, whey:25, milk:60, berries:100",
            listOf("Alle Zutaten außer den Beeren fein pürieren.", "Im heißen Waffeleisen 4 Minuten je Waffel backen.", "Mit Beeren servieren."),
            listOf("Blend everything except the berries until smooth.", "Bake 4 minutes per waffle in a hot waffle iron.", "Serve with berries.")),
        r("casein_pudding", "Casein-Pudding mit Beeren", "Casein pudding with berries", MealType.SNACK, 5, setOf(HP, VEG, QUICK),
            "casein:35, milk:250, berries:100, almonds:10",
            listOf("Casein mit Milch kräftig verrühren, bis es eindickt.", "Beeren und Mandeln darübergeben; über Nacht wird es noch fester."),
            listOf("Whisk the casein into the milk until it thickens.", "Top with berries and almonds; it firms up further overnight.")),
        r("cottage_crackers", "Hüttenkäse auf Reiswaffeln", "Cottage cheese on rice cakes", MealType.SNACK, 5, setOf(HP, VEG, QUICK),
            "cottage:200, rice_cakes:40, tomato:100, cucumber:60",
            listOf("Hüttenkäse auf die Reiswaffeln streichen.", "Mit Tomaten- und Gurkenscheiben belegen und pfeffern."),
            listOf("Spread the cottage cheese on the rice cakes.", "Top with tomato and cucumber slices and add pepper.")),
        r("trail_mix", "Studentenfutter selbst gemischt", "Home-made trail mix", MealType.SNACK, 3, setOf(VEG, MASS, QUICK),
            "cashews:30, almonds:20, raisins:30, dark_chocolate:15, pumpkin_seeds:15",
            listOf("Alles mischen und portionsweise abfüllen."),
            listOf("Mix everything and portion it out.")),
        r("date_balls", "Dattel-Hafer-Kugeln", "Date and oat balls", MealType.SNACK, 15, setOf(VEG, PREP),
            "dates:80, oats:50, peanut_butter:25, whey:20, cocoa:8",
            listOf("Datteln fein hacken und mit den übrigen Zutaten zu einer Masse kneten.", "Kugeln formen und mindestens eine Stunde kühlen."),
            listOf("Finely chop the dates and knead with the remaining ingredients.", "Roll into balls and chill at least one hour.")),
        r("skyr_dip", "Skyr-Dip mit Gemüsesticks", "Skyr dip with vegetable sticks", MealType.SNACK, 8, setOf(HP, VEG, QUICK),
            "skyr:200, carrot:120, pepper:100, cucumber:100, lemon:10, garlic:4",
            listOf("Skyr mit Knoblauch, Zitrone, Salz und Kräutern verrühren.", "Gemüse in Sticks schneiden und dazu servieren."),
            listOf("Stir skyr with garlic, lemon, salt and herbs.", "Cut the vegetables into sticks and serve alongside.")),
        r("egg_salad_pita", "Eiersalat im Pitabrot", "Egg salad in pita", MealType.SNACK, 15, setOf(HP, VEG),
            "egg:150, yogurt_greek:50, mustard:8, pita:80, lettuce:40, onion:20",
            listOf("Eier 9 Minuten kochen, abschrecken und würfeln.", "Mit Joghurt, Senf, Zwiebel, Salz und Pfeffer mischen.", "Pitabrot öffnen und mit Salat und Eiersalat füllen."),
            listOf("Boil the eggs 9 minutes, cool and dice.", "Mix with yoghurt, mustard, onion, salt and pepper.", "Open the pita and fill with leaves and the egg salad."))
    )

    val byKey: Map<String, Recipe> = all.associateBy { it.key }
}
