package app.maximus.lab.domain

/** Multiple-choice concept questions. The first option is always the correct one; the engine shuffles. */
internal object QuizBank {
    private var n = 0
    private fun mc(topic: Topic, diff: Int, chapter: String, prompt: String, correct: String, vararg wrong: String, why: String) =
        Question("mc-${topic.short}-${++n}", topic, diff, prompt, why, listOf(correct) + wrong, 0, chapterKey = chapter)

    private val T = Topic.THERMO
    private val E = Topic.ELECTRO
    private val Q = Topic.QUANTUM
    private val S = Topic.SEMICONDUCTOR
    private val C = Topic.CALORIC
    private val F = Topic.QFT
    private val M = Topic.MATH
    private val K = Topic.MECHANICS

    val all: List<Question> = listOf(
        // ---------------- Thermodynamik ----------------
        mc(T, 1, "th_laws", "Welche Größe ist eine Zustandsgröße?", "Entropie S", "Wärme Q", "Arbeit W", "Wärmestrom Q̇",
            why = "Zustandsgrößen hängen nur vom Zustand ab; Q und W hängen vom Weg ab (unvollständige Differentiale δQ, δW)."),
        mc(T, 1, "th_laws", "Was besagt der zweite Hauptsatz in der Formulierung von Clausius?", "Wärme fließt nie von selbst von kalt nach warm.",
            "Energie bleibt erhalten.", "Die Entropie am absoluten Nullpunkt ist null.", "Zwei Systeme im Gleichgewicht mit einem dritten sind im Gleichgewicht miteinander.",
            why = "Energieerhaltung ist der 1., Nernst der 3., die Transitivität des Gleichgewichts der 0. Hauptsatz."),
        mc(T, 1, "th_gas", "Wie viele Freiheitsgrade hat ein zweiatomiges ideales Gas bei Raumtemperatur?", "5", "3", "6", "7",
            why = "3 Translationen + 2 Rotationen; die Schwingung ist eingefroren, weil ħω ≫ k_BT. Daher γ = 7/5."),
        mc(T, 2, "th_gas", "Bei einer reversiblen adiabatischen Expansion eines idealen Gases …", "… sinkt die Temperatur.", "… bleibt die Temperatur konstant.",
            "… steigt die Entropie.", "… wird Wärme zugeführt.",
            why = "Q = 0, das Gas verrichtet Arbeit auf Kosten der inneren Energie: ΔU = W < 0, also sinkt T; S bleibt konstant."),
        mc(T, 2, "th_cycles", "Warum kann kein Motor den Carnot-Wirkungsgrad übertreffen?", "Sonst ließe sich Wärme ohne Arbeit von kalt nach warm pumpen.",
            "Weil Reibung unvermeidbar ist.", "Weil ideale Gase nicht existieren.", "Weil die Energie sonst nicht erhalten wäre.",
            why = "Koppelt man eine bessere Maschine mit einer rückwärts laufenden Carnot-Maschine, entsteht ein Widerspruch zum 2. Hauptsatz — unabhängig von Reibung oder Medium."),
        mc(T, 2, "th_potentials", "Welches Potential ist im Gleichgewicht bei festem T und p minimal?", "Gibbs-Energie G", "Innere Energie U", "Enthalpie H", "Freie Energie F",
            why = "G = H − TS mit dG = −S dT + V dp; deshalb bestimmt G Phasengleichgewichte und chemische Reaktionen bei Laborbedingungen."),
        mc(T, 2, "th_potentials", "Welche Maxwell-Relation folgt aus der Gibbs-Energie?", "(∂S/∂p)_T = −(∂V/∂T)_p", "(∂S/∂V)_T = (∂p/∂T)_V",
            "(∂T/∂V)_S = −(∂p/∂S)_V", "(∂T/∂p)_S = (∂V/∂S)_p",
            why = "Aus dG = −S dT + V dp und der Symmetrie der zweiten Ableitungen. Die anderen stammen aus F, U und H."),
        mc(T, 3, "th_phase", "Welche kritischen Exponenten sagt die Landau-Theorie voraus?", "β = 1/2, γ = 1, δ = 3", "β = 1/8, γ = 7/4, δ = 15",
            "β = 0,326, γ = 1,24, δ = 4,8", "β = 1, γ = 1/2, δ = 2",
            why = "Molekularfeldwerte. 1/8, 7/4, 15 sind die exakten 2D-Ising-Exponenten, 0,326/1,24/4,8 die 3D-Ising-Werte."),
        mc(T, 3, "th_stat", "Was ist die Zustandssumme Z im kanonischen Ensemble?", "Σ e^{−Eᵢ/k_BT}", "Σ Eᵢ e^{−Eᵢ/k_BT}", "k_B ln Ω", "Σ pᵢ ln pᵢ",
            why = "Z normiert die Boltzmann-Gewichte; F = −k_BT ln Z. k_B ln Ω ist die mikrokanonische Entropie."),
        mc(T, 2, "th_stat", "Warum trägt das Elektronengas eines Metalls kaum zur Wärmekapazität bei?", "Nur Elektronen innerhalb ≈ k_BT um die Fermi-Energie können angeregt werden.",
            "Elektronen haben keine kinetische Energie.", "Elektronen sind Bosonen.", "Das Gitter absorbiert die Energie.",
            why = "Pauli-Prinzip: Tiefere Zustände sind besetzt. Der Anteil ~k_BT/E_F ≈ 1 % ergibt C_el = γT."),
        mc(T, 1, "th_transport", "Wie hängt die abgestrahlte Leistung eines schwarzen Körpers von T ab?", "∝ T⁴", "∝ T", "∝ T²", "∝ e^{−1/T}",
            why = "Stefan-Boltzmann: Integration des Planck-Spektrums über alle Frequenzen ergibt σT⁴."),
        mc(T, 2, "th_transport", "Wie skaliert die Eindringtiefe einer Temperaturstörung mit der Zeit?", "∝ √t", "∝ t", "∝ t²", "∝ ln t",
            why = "Diffusion: ℓ ~ √(at). Doppelte Tiefe braucht die vierfache Zeit."),

        // ---------------- Elektrodynamik ----------------
        mc(E, 1, "el_static", "Wie fällt das Feld einer unendlich ausgedehnten, homogen geladenen Ebene mit dem Abstand ab?", "Gar nicht, es ist konstant.", "∝ 1/r", "∝ 1/r²", "∝ 1/r³",
            why = "Gauß mit Pillendose: E = σ/(2ε₀), unabhängig vom Abstand. Draht: 1/r, Punktladung: 1/r², Dipol: 1/r³."),
        mc(E, 1, "el_static", "Ein Dielektrikum (ε_r > 1) wird bei fester Ladung zwischen die Platten geschoben. Was passiert mit der Spannung?", "Sie sinkt.", "Sie steigt.", "Sie bleibt gleich.", "Sie wird null.",
            why = "C wächst um ε_r, Q bleibt: U = Q/C sinkt. Die Polarisation schwächt das Feld im Inneren."),
        mc(E, 2, "el_static", "Warum gibt es keine stabile Ruhelage einer Ladung in einem elektrostatischen Feld (Earnshaw)?", "Lösungen der Laplace-Gleichung haben keine lokalen Extrema.",
            "Weil Ladungen sich immer abstoßen.", "Weil das Feld zeitabhängig ist.", "Wegen der Unschärferelation.",
            why = "Im ladungsfreien Raum gilt ∇²φ = 0; das Potential kann dort weder Minimum noch Maximum haben. Ionenfallen nutzen daher Wechselfelder."),
        mc(E, 1, "el_circuits", "Wie groß ist die Impedanz einer Spule bei der Kreisfrequenz ω?", "iωL", "1/(iωL)", "ωL²", "−iωL",
            why = "u = L di/dt; mit i ∝ e^{iωt} wird die Ableitung zur Multiplikation mit iω. Kondensator: 1/(iωC)."),
        mc(E, 2, "el_circuits", "Ein RLC-Kreis hat R < 2√(L/C). Wie verhält er sich nach einem Stoß?", "Gedämpfte Schwingung", "Kriechfall ohne Überschwingen",
            "Ungedämpfte Schwingung", "Exponentielles Anwachsen",
            why = "δ = R/2L < ω₀ = 1/√(LC) ⇔ R < 2√(L/C): Schwingfall mit ω_d = √(ω₀² − δ²)."),
        mc(E, 1, "el_magneto", "Welche Arbeit verrichtet die magnetische Lorentzkraft an einer Ladung?", "Keine", "qvB", "qvB·t", "Hängt von der Masse ab",
            why = "F = qv × B steht immer senkrecht auf v; sie ändert nur die Richtung, nicht den Betrag der Geschwindigkeit."),
        mc(E, 2, "el_magneto", "Warum gilt ∇ · B = 0?", "Es gibt keine magnetischen Monopole.", "Weil B immer konstant ist.", "Wegen der Ladungserhaltung.",
            "Weil Magnetfelder nur in Leitern existieren.",
            why = "Feldlinien von B sind geschlossen; jeder Fluss in ein Volumen fließt auch wieder hinaus."),
        mc(E, 1, "el_induction", "Wofür steht das Minuszeichen in U_ind = −dΦ/dt?", "Lenzsche Regel: Die Induktion wirkt ihrer Ursache entgegen.",
            "Elektronen sind negativ geladen.", "Die Spannung ist immer negativ.", "Es ist eine Konvention ohne physikalische Bedeutung.",
            why = "Mit Pluszeichen würde ein Strom seinen eigenen Fluss verstärken — Energie aus dem Nichts."),
        mc(E, 2, "el_maxwell", "Welche Ergänzung Maxwells machte Licht als elektromagnetische Welle möglich?", "Der Verschiebungsstrom ε₀∂E/∂t", "Die Lorentzkraft",
            "Das Coulomb-Gesetz", "Die Quellenfreiheit von B",
            why = "Erst mit ihm koppeln ∇ × B und ∂E/∂t; daraus folgt die Wellengleichung mit c = 1/√(μ₀ε₀)."),
        mc(E, 2, "el_maxwell", "In welche Richtung zeigt der Poynting-Vektor einer ebenen Welle?", "In Ausbreitungsrichtung", "Parallel zu E", "Parallel zu B", "Entgegen der Ausbreitung",
            why = "S = E × B/μ₀ und E, B, k bilden ein Rechtssystem."),
        mc(E, 3, "el_maxwell", "Welche Größe ist in der Elektrodynamik eichinvariant?", "Das Feld E", "Das Potential φ", "Das Vektorpotential A", "Die Kombination φ + |A|",
            why = "A → A + ∇χ, φ → φ − ∂χ/∂t ändert die Potentiale, aber E = −∇φ − ∂A/∂t und B = ∇ × A bleiben gleich."),

        // ---------------- Quantenphysik ----------------
        mc(Q, 1, "qm_origins", "Was beobachtet man beim Photoeffekt, wenn man die Lichtintensität (bei fester Frequenz) verdoppelt?",
            "Doppelt so viele Elektronen, gleiche maximale Energie", "Doppelte Elektronenenergie", "Keine Änderung", "Erst dann setzt der Effekt ein",
            why = "Die Energie pro Photon hν bleibt, die Zahl der Photonen verdoppelt sich."),
        mc(Q, 1, "qm_formalism", "Was ist |ψ(x)|²?", "Die Aufenthaltswahrscheinlichkeitsdichte", "Die Energie", "Der Impuls", "Die Ladungsdichte des Teilchens",
            why = "Bornsche Regel; ψ selbst ist eine komplexe Amplitude ohne direkte Messbedeutung."),
        mc(Q, 1, "qm_formalism", "Wie lautet der kanonische Kommutator?", "[x̂, p̂] = iħ", "[x̂, p̂] = 0", "[x̂, p̂] = ħ", "[x̂, p̂] = −i",
            why = "Mit p̂ = −iħ d/dx: [x̂, p̂]ψ = iħψ. Daraus folgt σ_xσ_p ≥ ħ/2."),
        mc(Q, 2, "qm_formalism", "Was garantiert, dass Messwerte reell sind?", "Observablen sind hermitesch.", "Wellenfunktionen sind normiert.",
            "Die Zeitentwicklung ist unitär.", "Der Hamilton-Operator ist positiv.",
            why = "Hermitesche Operatoren haben reelle Eigenwerte und orthogonale Eigenvektoren (Spektralsatz)."),
        mc(Q, 1, "qm_1d", "Wie hängen die Energien im unendlich tiefen Kastenpotential von n ab?", "∝ n²", "∝ n", "∝ 1/n²", "∝ n + ½",
            why = "Eₙ = n²π²ħ²/(2mL²). n + ½: Oszillator, −1/n²: Wasserstoff."),
        mc(Q, 2, "qm_1d", "Wie ändert sich die Tunnelwahrscheinlichkeit grob, wenn man eine dicke Barriere doppelt so breit macht?", "Sie wird etwa quadriert (exponentiell kleiner).",
            "Sie halbiert sich.", "Sie bleibt gleich.", "Sie verdoppelt sich.",
            why = "T ∝ e^{−2κa}; aus e^{−2κa} wird e^{−4κa} = (e^{−2κa})². Darauf beruht die Auflösung des Rastertunnelmikroskops."),
        mc(Q, 2, "qm_1d", "Welche Energie hat der Grundzustand des harmonischen Oszillators?", "ħω/2", "0", "ħω", "k_BT",
            why = "Nullpunktsenergie; ein Zustand mit E = 0 würde σ_x = σ_p = 0 verlangen und die Unschärferelation verletzen."),
        mc(Q, 2, "qm_hydrogen", "Wie groß ist der Entartungsgrad des Niveaus n im Wasserstoffatom (ohne Spin)?", "n²", "n", "2n + 1", "2l + 1",
            why = "Σ_{l=0}^{n−1} (2l + 1) = n². Mit Spin: 2n²."),
        mc(Q, 2, "qm_spin", "Was passiert mit einem Spin-½-Zustand bei einer Drehung um 360°?", "Er erhält den Faktor −1.", "Er bleibt unverändert.",
            "Er wird zu |↓⟩.", "Er wird null.",
            why = "Spinoren transformieren mit e^{−iθσ·n/2}; erst nach 720° kehrt der Zustand zurück (Neutroneninterferometrie bestätigt das)."),
        mc(Q, 2, "qm_spin", "Welches Prinzip erklärt den Aufbau des Periodensystems?", "Pauli-Prinzip", "Unschärferelation", "Korrespondenzprinzip", "Superpositionsprinzip",
            why = "Keine zwei Elektronen im selben Zustand: Schalen füllen sich nacheinander."),
        mc(Q, 3, "qm_approx", "Wie wirkt die Störungstheorie zweiter Ordnung auf die Grundzustandsenergie?", "Sie senkt sie immer ab (oder lässt sie gleich).",
            "Sie erhöht sie immer.", "Sie ist immer null.", "Das Vorzeichen ist zufällig.",
            why = "E₀⁽²⁾ = Σ |V_k0|²/(E₀ − E_k) und E₀ < E_k für alle k."),
        mc(Q, 3, "qm_info", "Welchen Maximalwert kann die CHSH-Größe in der Quantenmechanik erreichen?", "2√2", "2", "4", "√2",
            why = "Tsirelson-Grenze. Lokal-realistische Theorien erlauben höchstens 2, algebraisch denkbar wären 4."),

        // ---------------- Halbleiter ----------------
        mc(S, 1, "sc_bands", "Warum leuchten Silizium-LEDs praktisch nicht?", "Silizium hat eine indirekte Bandlücke.", "Die Bandlücke ist zu groß.",
            "Silizium hat keine Löcher.", "Silizium ist ein Metall.",
            why = "Bei indirekten Halbleitern braucht strahlende Rekombination zusätzlich ein Phonon; nichtstrahlende Prozesse gewinnen."),
        mc(S, 1, "sc_carriers", "Was besagt das Massenwirkungsgesetz im Halbleiter?", "np = nᵢ², unabhängig von der Dotierung", "n = p immer",
            "n + p = nᵢ", "n/p = N_D/N_A",
            why = "Gilt im thermischen Gleichgewicht und nicht entartet; Dotierung verschiebt nur das Verhältnis."),
        mc(S, 1, "sc_carriers", "Welche Dotierung macht Silizium n-leitend?", "Phosphor", "Bor", "Gallium", "Aluminium",
            why = "Phosphor (5. Hauptgruppe) gibt ein Elektron ab; Bor, Ga, Al (3. Hauptgruppe) sind Akzeptoren."),
        mc(S, 2, "sc_carriers", "Was passiert mit einem n-dotierten Halbleiter bei sehr hoher Temperatur?", "Er wird intrinsisch (nᵢ ≫ N_D).",
            "Er wird p-leitend.", "Die Bandlücke verschwindet.", "Er wird supraleitend.",
            why = "nᵢ wächst exponentiell; über einer Grenztemperatur dominieren thermisch erzeugte Paare — Grund für die maximale Betriebstemperatur von Si-Bauteilen."),
        mc(S, 2, "sc_transport", "Wie lautet die Einstein-Relation?", "D = μk_BT/e", "D = μ/(k_BT)", "D = e/(μk_BT)", "D = μk_BT",
            why = "Gleichgewicht von Drift und Diffusion mit Boltzmann-Verteilung."),
        mc(S, 2, "sc_transport", "Warum sinkt die Beweglichkeit in Si bei steigender Temperatur?", "Mehr Phononenstreuung", "Weniger Ladungsträger",
            "Die Bandlücke wächst", "Die Dotieratome verdampfen",
            why = "Gitterstreuung skaliert etwa mit T^{−3/2}; bei tiefen T dominiert dagegen Störstellenstreuung (∝ T^{3/2})."),
        mc(S, 1, "sc_pn", "Was liegt im pn-Übergang ohne äußere Spannung im ganzen Bauteil auf konstanter Höhe?", "Das Fermi-Niveau", "Die Leitungsbandkante",
            "Das elektrostatische Potential", "Die Elektronendichte",
            why = "Im thermischen Gleichgewicht ist das elektrochemische Potential konstant; die Bänder verbiegen sich um eV_bi."),
        mc(S, 2, "sc_pn", "Wie ändert sich die Sperrschichtkapazität mit wachsender Sperrspannung?", "Sie sinkt (∝ (V_bi + |V|)^{−1/2}).", "Sie steigt.",
            "Sie bleibt konstant.", "Sie wird negativ.",
            why = "Die RLZ wird breiter, C = εA/W kleiner — genutzt in Kapazitätsdioden (Varaktoren)."),
        mc(S, 2, "sc_opto", "Was begrenzt den Wirkungsgrad einer Einfach-Solarzelle (Shockley-Queisser)?", "Thermalisierung und nicht absorbierte Photonen unter E_g",
            "Der Ohmsche Widerstand der Drähte", "Die Lichtgeschwindigkeit", "Das Pauli-Prinzip",
            why = "Photonen unter E_g gehen verloren, Überschussenergie über E_g wird zu Wärme; dazu strahlende Rekombination. Optimum ≈ 33 % bei E_g ≈ 1,34 eV."),
        mc(S, 3, "sc_transistor", "Warum kann ein klassischer MOSFET bei 300 K nicht steiler als 60 mV/Dekade schalten?", "Boltzmann-Statistik der Ladungsträger über der Barriere",
            "Lichtgeschwindigkeit im Kanal", "Quantisierung des Gates", "Zu dicke Oxide",
            why = "Der Subthreshold-Strom ∝ e^{eψ_s/k_BT}; ln10·k_BT/e = 60 mV. Tunnel-FETs und negative Kapazität versuchen das zu umgehen."),
        mc(S, 2, "sc_transistor", "Was passiert beim MOSFET im Sättigungsbereich (V_DS > V_GS − V_th)?", "Der Kanal schnürt am Drain ab; I_D hängt kaum noch von V_DS ab.",
            "Der Strom wird null.", "Der Transistor brennt durch.", "Der Strom wächst linear mit V_DS.",
            why = "Pinch-off; nur die Kanallängenmodulation λ erzeugt eine schwache Restabhängigkeit."),

        // ---------------- Kalorik ----------------
        mc(C, 1, "ca_thermo", "Was ist ein kalorischer Effekt?", "Eine reversible Temperaturänderung beim Anlegen eines äußeren Feldes",
            "Die Erwärmung durch elektrischen Strom (Joule)", "Die Wärmeabgabe bei Reibung", "Die Verbrennungswärme eines Brennstoffs",
            why = "Feld ordnet einen Freiheitsgrad, Entropie sinkt; adiabatisch steigt T, beim Entfernen sinkt sie wieder. Joule-Wärme ist irreversibel."),
        mc(C, 2, "ca_thermo", "Welche Maxwell-Relation liegt der Elektrokalorik zugrunde?", "(∂S/∂E)_T = (∂P/∂T)_E", "(∂S/∂H)_T = μ₀(∂M/∂T)_H",
            "(∂S/∂p)_T = −(∂V/∂T)_p", "(∂S/∂σ)_T = (∂ε/∂T)_σ",
            why = "Aus dG = −S dT − P dE. Die anderen gelten für Magneto-, Baro- bzw. Elastokalorik."),
        mc(C, 2, "ca_thermo", "Wann ist ein kalorischer Effekt typischerweise am größten?", "Nahe einem Phasenübergang", "Bei sehr tiefen Temperaturen fern jedes Übergangs",
            "Bei sehr hohen Temperaturen", "Unabhängig von der Temperatur",
            why = "Dort ändert sich der Ordnungsparameter stark mit T (große ∂P/∂T, ∂M/∂T) und latente Wärme kann genutzt werden."),
        mc(C, 1, "ca_electro", "Warum erzielen ferroelektrische Dünnschichten größere elektrokalorische Effekte als Volumenkeramik?", "Sie halten viel höhere Feldstärken aus.",
            "Sie haben eine höhere Dichte.", "Sie sind magnetisch.", "Sie haben keine Polarisation.",
            why = "Durchschlagsfestigkeit; bei gleicher Spannung ist das Feld in dünnen Schichten enorm (PZT-Film: 480 kV/cm, ΔT ≈ 12 K)."),
        mc(C, 2, "ca_electro", "In der einfachsten Landau-Beschreibung ist die elektrokalorische Entropieänderung proportional zu …", "… der Änderung von P².",
            "… der Änderung von E.", "… P⁴.", "… der Temperatur.",
            why = "S = −∂G/∂T = −aP²/2 + const, wenn nur α₁ = a(T − T₀) von T abhängt."),
        mc(C, 1, "ca_elasto", "Was passiert, wenn man einen superelastischen NiTi-Draht schnell dehnt?", "Er erwärmt sich deutlich (Martensitbildung setzt latente Wärme frei).",
            "Er kühlt sich ab.", "Er schmilzt.", "Nichts.",
            why = "Spannungsinduzierte Umwandlung Austenit → Martensit ist exotherm; beim Entlasten kühlt er sich ab (ΔT bis ≈ 25 K)."),
        mc(C, 2, "ca_elasto", "Warum erwärmt sich Gummi beim schnellen Dehnen?", "Seine Elastizität ist entropisch: Gestreckte Ketten haben weniger Konformationen.",
            "Wegen Reibung zwischen Molekülen allein.", "Weil Gummi sich bei Erwärmung ausdehnt.", "Weil Gummi ferroelektrisch ist.",
            why = "Adiabatisch muss die verlorene Konformationsentropie als Wärme auftauchen. Metalle kühlen sich dagegen beim Dehnen leicht ab."),
        mc(C, 2, "ca_elasto", "Welche Steigung hat die Umwandlungsspannung von NiTi über der Temperatur ungefähr?", "≈ 6–7 MPa/K", "≈ 0,01 MPa/K", "≈ 500 MPa/K", "Sie ist temperaturunabhängig",
            why = "Clausius-Clapeyron dσ/dT = −ρΔs/ε_tr mit Δs ≈ −50…−70 J/(kg K), ε_tr ≈ 0,05."),
        mc(C, 1, "ca_magneto_baro", "Welches Element ist das klassische Raumtemperatur-Magnetokalorikum?", "Gadolinium", "Eisen", "Kupfer", "Silizium",
            why = "Gd hat T_C ≈ 294 K und das große 4f-Moment J = 7/2."),
        mc(C, 2, "ca_magneto_baro", "Was ist die maximale magnetische Entropie pro Mol für Momente mit Drehimpuls J?", "R ln(2J + 1)", "R J", "R/(2J + 1)", "3R",
            why = "2J + 1 gleich wahrscheinliche Einstellungen; ln der Zahl der Zustände mal R."),
        mc(C, 3, "ca_multi", "Was beschreibt der Kreuzterm d′Eσ im multikalorischen ΔS?", "Die Temperaturabhängigkeit der Kopplung zwischen elektrischem Feld und Spannung",
            "Die Hysterese", "Joule-Wärme", "Wärmeleitung zwischen den Feldern",
            why = "Aus G ⊃ −dEσ folgt S ⊃ (∂d/∂T)Eσ; er kann den Effekt verstärken oder abschwächen."),
        mc(C, 2, "ca_multi", "Wozu dient ein aktiver Regenerator (AMR) in kalorischen Kühlgeräten?", "Eine Temperaturspanne zu erreichen, die viel größer als ΔT_ad ist",
            "Das Feld zu verstärken", "Die Hysterese zu messen", "Den Strom gleichzurichten",
            why = "Ein Fluid pendelt durch ein Bett aus kalorischem Material; es bildet sich ein Gradient, der viele kleine Zyklen kaskadiert."),

        mc(C, 1, "ca_calorimetry", "Warum steigt die Temperatur von Eiswasser beim Erwärmen nicht, solange noch Eis vorhanden ist?", "Die Wärme wird als Schmelzwärme verbraucht.",
            "Eis isoliert das Wasser.", "Wasser hat bei 0 °C keine Wärmekapazität.", "Das Thermometer reagiert zu langsam.",
            why = "Am Phasenübergang erster Ordnung fließt latente Wärme ohne Temperaturänderung: 334 J pro Gramm Eis."),
        mc(C, 2, "ca_calorimetry", "Was misst eine DSC (Dynamische Differenzkalorimetrie)?", "Die Differenz der Wärmeströme in Probe und Referenz beim Heizen",
            "Die elektrische Polarisation", "Die Dichte der Probe", "Die Schallgeschwindigkeit",
            why = "Daraus folgen c_p(T), Übergangstemperaturen und latente Wärmen — Standard für kalorische Materialien."),
        mc(T, 2, "th_phase", "Was gibt die Clausius-Clapeyron-Gleichung an?", "Die Steigung der Koexistenzkurve dp/dT = L/(TΔv)",
            "Den Wirkungsgrad eines Motors", "Die Wärmeleitfähigkeit", "Die mittlere freie Weglänge",
            why = "Sie folgt aus der Gleichheit der chemischen Potentiale beider Phasen entlang der Kurve."),
        mc(E, 2, "el_induction", "Wovon hängt die Skin-Tiefe eines Leiters ab?", "Von Frequenz, Leitfähigkeit und Permeabilität: δ = √(2/(ωμσ))",
            "Nur von der Spannung", "Nur vom Drahtdurchmesser", "Von der Temperatur allein",
            why = "Höhere Frequenz, bessere Leitfähigkeit oder größere Permeabilität drängen den Strom an die Oberfläche."),
        mc(S, 1, "sc_bands", "Was ist ein Loch im Halbleiter?", "Ein fehlendes Elektron im Valenzband, das sich wie eine positive Ladung bewegt",
            "Ein Gitterfehler", "Ein Positron", "Ein freies Proton",
            why = "Die kollektive Bewegung des fast vollen Bandes lässt sich als Quasiteilchen mit +e und positiver effektiver Masse beschreiben."),
        mc(M, 1, "ma_ode", "Welche allgemeine Lösung hat y'' + ω²y = 0?", "y = A cos ωx + B sin ωx", "y = A e^{ωx}", "y = Ax + B", "y = A e^{−ωx²}",
            why = "Charakteristisches Polynom λ² + ω² = 0, λ = ±iω — harmonische Schwingung."),

        // ---------------- QFT ----------------
        mc(F, 1, "qft_relativity", "Welche Dimension hat eine Länge in natürlichen Einheiten (ħ = c = 1)?", "Energie⁻¹", "Energie", "Energie²", "dimensionslos",
            why = "L = ħc/E; 1 GeV⁻¹ ≈ 0,197 fm."),
        mc(F, 1, "qft_relativity", "Welche Größe ist lorentzinvariant?", "Die invariante Masse p² = E² − p²", "Die Energie E", "Der Impuls |p|", "Die Zeitdauer Δt",
            why = "Skalarprodukte von Vierervektoren sind invariant; E, |p| und Δt hängen vom Bezugssystem ab."),
        mc(F, 1, "qft_classical", "Was liefert das Noether-Theorem für Invarianz unter Zeittranslationen?", "Energieerhaltung", "Impulserhaltung", "Ladungserhaltung", "Drehimpulserhaltung",
            why = "Zeit ↔ Energie, Raum ↔ Impuls, Drehungen ↔ Drehimpuls, Phase ↔ Ladung."),
        mc(F, 2, "qft_classical", "Warum ist das Photon in der QED masselos?", "Ein Massenterm m²A_μA^μ wäre nicht eichinvariant.", "Weil Licht schnell ist.",
            "Weil Photonen Fermionen sind.", "Weil die Ladung null ist.",
            why = "Eichinvarianz verbietet den Term. Massive Eichbosonen (W, Z) brauchen den Higgs-Mechanismus."),
        mc(F, 2, "qft_scalar", "Wofür sorgt die iε-Vorschrift im Feynman-Propagator?", "Positive Energien laufen vorwärts, negative rückwärts in der Zeit.",
            "Sie macht Integrale endlich.", "Sie bricht die Lorentz-Invarianz.", "Sie entfernt die Antiteilchen.",
            why = "Sie legt die Umlaufrichtung um die Pole fest; daraus folgt die Feynman-Stückelberg-Interpretation der Antiteilchen."),
        mc(F, 2, "qft_dirac", "Was ist die Clifford-Algebra der γ-Matrizen?", "{γ^μ, γ^ν} = 2g^μν", "[γ^μ, γ^ν] = 2g^μν", "γ^μγ^ν = g^μν", "{γ^μ, γ^ν} = 0",
            why = "Sie garantiert, dass (iγ^μ∂_μ − m)ψ = 0 die Klein-Gordon-Gleichung impliziert."),
        mc(F, 2, "qft_dirac", "Warum wird das Dirac-Feld mit Antikommutatoren quantisiert?", "Sonst ist die Energie nicht nach unten beschränkt (und Kausalität verletzt).",
            "Weil Elektronen geladen sind.", "Aus historischer Konvention.", "Weil Kommutatoren nicht definiert sind.",
            why = "Spin-Statistik-Theorem: halbzahliger Spin ⇒ Fermi-Statistik."),
        mc(F, 1, "qft_feynman", "Welcher Faktor gehört in der QED zu einem Vertex?", "−ieγ^μ", "i/(p² − m²)", "−ig_μν/q²", "u(p)",
            why = "Die übrigen sind Fermion- bzw. Photon-Propagator und ein äußerer Spinor."),
        mc(F, 2, "qft_feynman", "Wie hängt σ(e⁺e⁻ → μ⁺μ⁻) für √s ≫ m_μ von s ab?", "∝ 1/s", "∝ s", "∝ ln s", "konstant",
            why = "Dimensionsanalyse: [σ] = E⁻², und die einzige Skala ist s: σ = 4πα²/(3s)."),
        mc(F, 2, "qft_feynman", "Was misst das R-Verhältnis σ(e⁺e⁻ → Hadronen)/σ(e⁺e⁻ → μ⁺μ⁻)?", "Farbzahl mal Summe der Quarkladungsquadrate",
            "Die Masse des Top-Quarks", "Die Feinstrukturkonstante", "Die Lebensdauer des Myons",
            why = "R = N_c Σ Q_q²; der Wert 2 (u, d, s) statt 2/3 bewies N_c = 3."),
        mc(F, 3, "qft_renorm", "Was bedeutet asymptotische Freiheit in der QCD?", "Die starke Kopplung wird bei hohen Energien klein.",
            "Quarks sind bei niedrigen Energien frei.", "Gluonen sind masselos.", "Die Kopplung ist konstant.",
            why = "β-Funktion negativ (b₀ = 11 − 2n_f/3 > 0); bei kleinen Energien wächst α_s — Confinement."),
        mc(F, 3, "qft_renorm", "Wie lautet der führende QED-Beitrag zum anomalen magnetischen Moment des Elektrons?", "α/(2π)", "α", "α²", "2α/π",
            why = "Schwinger 1948: a = α/2π ≈ 0,00116."),
        mc(F, 3, "qft_sm", "Wie viele Gluonen gibt es in der QCD?", "8", "3", "9", "1",
            why = "Generatoren von SU(3): N² − 1 = 8."),
        mc(F, 3, "qft_sm", "Wie viele der vier reellen Freiheitsgrade des Higgs-Dubletts werden zu longitudinalen Moden von W± und Z?", "3", "1", "4", "0",
            why = "Drei Goldstone-Bosonen werden „gefressen“, einer bleibt als physikalisches Higgs-Boson."),

        // ---------------- Mathematik ----------------
        mc(M, 1, "ma_analysis", "Was besagt der Hauptsatz der Differential- und Integralrechnung?", "∫ₐᵇ f dx = F(b) − F(a) mit F' = f",
            "Jede stetige Funktion ist differenzierbar.", "Jede Funktion hat eine Taylor-Reihe.", "∫ f g = ∫ f ∫ g",
            why = "Integration und Differentiation sind zueinander invers. Stetigkeit impliziert nicht Differenzierbarkeit (|x| bei 0)."),
        mc(M, 2, "ma_analysis", "Warum hat die Taylor-Reihe von 1/(1 + x²) um 0 nur den Konvergenzradius 1?", "Wegen der Pole bei x = ±i in der komplexen Ebene",
            "Weil die Funktion bei x = 1 unstetig ist.", "Weil die Ableitungen null werden.", "Das stimmt nicht, sie konvergiert überall.",
            why = "Der Konvergenzradius ist der Abstand zur nächsten komplexen Singularität."),
        mc(M, 1, "ma_vector", "Welche Identität gilt für jedes glatte Skalarfeld f?", "∇ × (∇f) = 0", "∇ · (∇f) = 0", "∇(∇ · f) = 0", "∇ × f = ∇f",
            why = "Rotation eines Gradienten verschwindet (Satz von Schwarz). ∇·∇f = ∇²f ist im Allgemeinen nicht null."),
        mc(M, 2, "ma_vector", "Der Gaußsche Integralsatz verknüpft …", "… das Volumenintegral der Divergenz mit dem Fluss durch die Oberfläche.",
            "… die Rotation mit der Zirkulation.", "… Gradient und Laplace-Operator.", "… Real- und Imaginärteil.",
            why = "Die Zirkulation gehört zu Stokes."),
        mc(M, 1, "ma_linalg", "Eine 3×3-Matrix hat die Eigenwerte 1, 2 und 3. Wie groß ist ihre Determinante?", "6", "1", "3", "0",
            why = "Die Determinante ist das Produkt der Eigenwerte: 1·2·3 = 6. (Die Spur, ihre Summe, ist hier zufällig auch 6.)"),
        mc(M, 2, "ma_linalg", "Was garantiert der Spektralsatz für reelle symmetrische Matrizen?", "Reelle Eigenwerte und eine Orthonormalbasis aus Eigenvektoren",
            "Alle Eigenwerte sind positiv.", "Die Matrix ist invertierbar.", "Die Determinante ist 1.",
            why = "Positiv definit wäre eine Zusatzannahme; invertierbar nur ohne Eigenwert 0."),
        mc(M, 2, "ma_ode", "Das lineare System ẋ = Ax ist asymptotisch stabil, wenn …", "… alle Eigenwerte negativen Realteil haben.", "… det A > 0.",
            "… alle Eigenwerte reell sind.", "… A symmetrisch ist.",
            why = "Lösungen ∝ e^{λt}; nur Re λ < 0 lässt alle Moden abklingen."),
        mc(M, 2, "ma_ode", "Welche Ordnung hat das klassische Runge-Kutta-Verfahren?", "4", "1", "2", "8",
            why = "Globaler Fehler O(h⁴): Halbe Schrittweite reduziert den Fehler um den Faktor 16."),
        mc(M, 2, "ma_fourier", "Was macht die Fourier-Transformation aus einer Faltung f * g?", "Das Produkt f̂ · ĝ", "Die Summe f̂ + ĝ", "Die Ableitung", "Nichts",
            why = "Faltungssatz; Grundlage schneller Filter und der Lösung linearer DGL."),
        mc(M, 3, "ma_complex", "Wie groß ist ∫_{−∞}^{∞} dx/(1 + x²)?", "π", "1", "2π", "π/2",
            why = "Residuensatz mit dem Pol bei i: 2πi · 1/(2i) = π (oder elementar: arctan)."),
        mc(M, 1, "ma_prob", "Ein Test erkennt eine Krankheit (Prävalenz 1 %) zu 99 %, mit 1 % falsch positiven Befunden. Wie wahrscheinlich ist man bei positivem Befund krank?",
            "≈ 50 %", "≈ 99 %", "≈ 1 %", "≈ 90 %",
            why = "Bayes: 0,99·0,01 / (0,99·0,01 + 0,01·0,99) = 0,5. Seltene Ereignisse machen falsch Positive häufig."),
        mc(M, 2, "ma_prob", "Wie verringert sich der Standardfehler eines Mittelwerts, wenn man viermal so viele Messungen macht?", "Er halbiert sich.", "Er viertelt sich.",
            "Er bleibt gleich.", "Er verdoppelt sich.",
            why = "σ/√n: √4 = 2."),
        mc(M, 3, "ma_special", "Warum gibt es Teilchen mit halbzahligem Spin?", "SU(2) ist die zweifache Überlagerung von SO(3) und hat Darstellungen mit j = ½, 3/2, …",
            "Weil Elektronen rotieren.", "Wegen der Unschärferelation.", "Aus Konvention.",
            why = "Projektive Darstellungen der Drehgruppe sind echte Darstellungen von SU(2)."),
        mc(M, 2, "ma_special", "Welchen Wert hat Γ(1/2)?", "√π", "1", "π", "1/2",
            why = "Γ(1/2) = ∫₀^∞ t^{−1/2}e^{−t} dt = 2∫₀^∞ e^{−u²} du = √π."),
        // ---------------- Mechanik und Relativität ----------------
        mc(K, 1, "me_newton", "Warum verläuft die Bewegung in einem Zentralkraftfeld in einer Ebene?", "Der Drehimpuls L = r × p ist erhalten.",
            "Die Energie ist erhalten.", "Der Impuls ist erhalten.", "Wegen des dritten Newtonschen Axioms.",
            why = "M = r × F = 0 für F ∥ r ⇒ L konstant; r und p stehen stets senkrecht auf dem festen Vektor L."),
        mc(K, 2, "me_newton", "Welche Potentiale haben laut Satz von Bertrand für alle gebundenen Bahnen geschlossene Orbits?", "V ∝ −1/r und V ∝ r²",
            "Nur V ∝ −1/r", "Alle Zentralpotentiale", "V ∝ ln r und V ∝ r",
            why = "Nur Kepler- und harmonisches Potential; jede Störung (z. B. die ART-Korrektur ∝ 1/r³) führt zu Periheldrehung."),
        mc(K, 2, "me_newton", "Welche Erhaltungsgröße ist für das Kepler-Problem spezifisch und erklärt die Geschlossenheit der Ellipsen?", "Der Runge-Lenz-Vektor",
            "Die Energie", "Der Drehimpuls", "Der Gesamtimpuls",
            why = "A = p × L − μk r̂ zeigt zum Perihel und ist nur für 1/r-Potentiale erhalten (verborgene SO(4)-Symmetrie)."),
        mc(K, 1, "me_lagrange", "Wie lautet die Lagrange-Funktion eines Teilchens im Potential V?", "L = T − V", "L = T + V", "L = V − T", "L = 2T − V",
            why = "Mit L = T − V liefert δ∫L dt = 0 genau mẍ = −∇V."),
        mc(K, 2, "me_lagrange", "Eine Koordinate q kommt in L nicht vor (zyklisch). Was folgt?", "Der konjugierte Impuls ∂L/∂q̇ ist erhalten.",
            "q ist konstant.", "q̇ ist null.", "Die Energie ist nicht erhalten.",
            why = "Euler-Lagrange: d/dt(∂L/∂q̇) = ∂L/∂q = 0 — die einfachste Form des Noether-Theorems."),
        mc(K, 2, "me_lagrange", "Welche Symmetrie liefert nach Noether die Energieerhaltung?", "Invarianz unter Zeittranslation", "Invarianz unter Raumtranslation",
            "Invarianz unter Drehungen", "Invarianz unter Spiegelungen",
            why = "Raumtranslation → Impuls, Drehung → Drehimpuls; Spiegelungen sind diskret und liefern keine Noether-Ladung, sondern Paritätsauswahlregeln."),
        mc(K, 2, "me_hamilton", "Was besagt der Satz von Liouville?", "Der Hamiltonsche Fluss erhält das Phasenraumvolumen.", "Die Energie ist immer erhalten.",
            "Alle Bahnen sind periodisch.", "Die Entropie wächst.",
            why = "Die Divergenz des Hamiltonschen Vektorfeldes verschwindet: ∂q̇/∂q + ∂ṗ/∂p = ∂²H/∂q∂p − ∂²H/∂p∂q = 0."),
        mc(K, 2, "me_hamilton", "Welchen Wert hat die Poisson-Klammer {q, p}?", "1", "0", "−1", "iħ",
            why = "{q, p} = ∂q/∂q ∂p/∂p − ∂q/∂p ∂p/∂q = 1. In der Quantenmechanik wird daraus [q̂, p̂] = iħ."),
        mc(K, 3, "me_hamilton", "Welche Gleichung erfüllt Hamiltons Wirkungsfunktion S(q, t)?", "∂S/∂t + H(q, ∂S/∂q, t) = 0", "∂S/∂t = H",
            "∇²S = 0", "dS/dt = 0",
            why = "Hamilton-Jacobi; ihr kurzwelliger Grenzfall verbindet sie mit der Schrödinger-Gleichung über ψ ≈ A e^{iS/ħ}."),
        mc(K, 2, "me_rigid", "Um welche Hauptachse ist die freie Rotation eines starren Körpers instabil?", "Um die Achse mit dem mittleren Trägheitsmoment",
            "Um die Achse mit dem größten Trägheitsmoment", "Um die Achse mit dem kleinsten Trägheitsmoment", "Um keine",
            why = "Linearisieren der Euler-Gleichungen gibt exponentielles Anwachsen nur für die Zwischenachse (Dschanibekow-Effekt)."),
        mc(K, 1, "me_rigid", "Welche Kugel rollt eine schiefe Ebene schneller hinab?", "Die Vollkugel", "Die Hohlkugel", "Beide gleich schnell", "Hängt von der Masse ab",
            why = "a = g sin α/(1 + I/(mR²)): Vollkugel I/(mR²) = 2/5, Hohlkugel 2/3. Masse und Radius kürzen sich."),
        mc(K, 2, "me_oscillation", "Bei welcher Dämpfung kehrt ein Oszillator am schnellsten ohne Überschwingen in die Ruhelage zurück?", "γ = ω₀ (aperiodischer Grenzfall)",
            "γ = 0", "γ = ω₀/2", "γ ≫ ω₀",
            why = "Beim Kriechfall dominiert die langsame Wurzel −γ + √(γ² − ω₀²) → −ω₀²/(2γ); Stoßdämpfer werden auf den Grenzfall abgestimmt."),
        mc(K, 2, "me_oscillation", "Wie viele Normalmoden hat ein System aus N gekoppelten Massen in einer Dimension?", "N", "2N", "N − 1", "N²",
            why = "Das Eigenwertproblem det(K − ω²M) = 0 ist N-dimensional; freie Ketten haben dabei eine Nullmode (ω = 0, Translation)."),
        mc(K, 2, "me_oscillation", "Wie ändert sich die Phase eines getriebenen Oszillators, wenn ω von weit unter bis weit über ω₀ läuft?", "Von 0 nach π",
            "Von 0 nach π/2", "Sie bleibt 0.", "Von π nach 0",
            why = "Unterhalb folgt der Oszillator dem Antrieb, in Resonanz hinkt er π/2 hinterher, darüber schwingt er gegenphasig."),
        mc(K, 1, "me_sr", "Welche Größe ist lorentzinvariant?", "Das Intervall c²Δt² − Δx²", "Die Zeitdifferenz Δt", "Die Länge Δx", "Die Energie E",
            why = "Zeit, Länge und Energie hängen vom Bezugssystem ab; invariant sind Viererskalare wie s² oder p² = m²c²."),
        mc(K, 2, "me_sr", "Was lässt sich bei Boosts in die gleiche Richtung einfach addieren?", "Die Rapiditäten", "Die Geschwindigkeiten", "Die Lorentz-Faktoren", "Die Impulse",
            why = "Boosts sind hyperbolische Drehungen: tanh(η₁ + η₂) = (β₁ + β₂)/(1 + β₁β₂)."),
        mc(K, 2, "me_sr", "Kann ein einzelnes freies Photon in ein Elektron-Positron-Paar zerfallen?", "Nein, Energie und Impuls können nicht zugleich erhalten sein.",
            "Ja, ab 1,022 MeV.", "Ja, aber nur im Magnetfeld.", "Nur bei Temperaturen über 10¹⁰ K.",
            why = "Das Paar hat im Schwerpunktsystem invariante Masse ≥ 2mₑc², das Photon p² = 0. Paarbildung braucht einen Stoßpartner (Kern)."),
        mc(K, 2, "me_gr", "Welche Aussage macht das Äquivalenzprinzip?", "Lokal ist ein frei fallendes System nicht von einem Inertialsystem zu unterscheiden.",
            "Masse und Energie sind äquivalent.", "Alle Inertialsysteme sind gleichwertig.", "Gravitation ist eine Kraft wie jede andere.",
            why = "Schwere = träge Masse; daher lässt sich Gravitation lokal wegtransformieren — der Kern der geometrischen Deutung."),
        mc(K, 2, "me_gr", "Warum muss GPS die ART berücksichtigen?", "Uhren im höheren Gravitationspotential gehen schneller (≈ +45 μs/Tag).",
            "Weil Satelliten schneller als Licht sind.", "Wegen der Erdrotation allein.", "Wegen der Lichtablenkung.",
            why = "ART +45 μs/Tag, SRT (Bahngeschwindigkeit) −7 μs/Tag, zusammen ≈ +38 μs/Tag ≙ ≈ 11 km Positionsfehler pro Tag."),
        mc(K, 3, "me_gr", "Wie viele Polarisationen hat eine Gravitationswelle in der ART?", "2 (+ und ×)", "1", "3", "4",
            why = "Der symmetrische Tensor h_μν hat 10 Komponenten; Eichfreiheit (4) und Nebenbedingungen (4) lassen 2 physikalische Freiheitsgrade — masseloses Spin-2-Feld."),
        mc(K, 2, "me_continuum", "Was misst die Reynolds-Zahl?", "Das Verhältnis von Trägheits- zu Reibungskräften", "Das Verhältnis von Druck zu Dichte",
            "Die Kompressibilität", "Die Wirbelstärke",
            why = "Re = ρvL/η; kleine Re: zähe, laminare Strömung (Stokes), große Re: Turbulenz."),
        mc(K, 2, "me_continuum", "Unter welchen Voraussetzungen gilt die Bernoulli-Gleichung entlang einer Stromlinie?", "Stationär, reibungsfrei, inkompressibel",
            "Nur für Gase", "Nur bei turbulenter Strömung", "Immer",
            why = "Sie folgt aus der Euler-Gleichung durch Integration entlang der Stromlinie; mit Viskosität geht Energie verloren."),
        // ---------------- Analysis I–III, LA II, Funktionalanalysis ----------------
        mc(M, 1, "ma_basics", "Was ist die Negation von „∀ε > 0 ∃N ∀n ≥ N: |aₙ − a| < ε“?", "∃ε > 0 ∀N ∃n ≥ N: |aₙ − a| ≥ ε",
            "∀ε > 0 ∃N ∀n ≥ N: |aₙ − a| ≥ ε", "∃ε > 0 ∃N ∀n ≥ N: |aₙ − a| ≥ ε", "∀ε > 0 ∀N ∃n ≥ N: |aₙ − a| < ε",
            why = "Quantoren kehren sich um (∀ ↔ ∃), die innere Aussage wird negiert. So beweist man, dass eine Folge nicht gegen a konvergiert."),
        mc(M, 1, "ma_basics", "Welche Aussage ist äquivalent zu A ⇒ B?", "¬B ⇒ ¬A", "B ⇒ A", "¬A ⇒ ¬B", "A ∧ B",
            why = "Kontraposition — Grundlage des indirekten Beweises. B ⇒ A ist die Umkehrung und im Allgemeinen nicht äquivalent."),
        mc(M, 2, "ma_basics", "Welche Menge ist überabzählbar?", "ℝ", "ℚ", "ℤ × ℤ", "Die algebraischen Zahlen",
            why = "Cantors Diagonalargument; ℚ, ℤ² und die algebraischen Zahlen sind abzählbar."),
        mc(M, 1, "ma_basics", "Welche Eigenschaft unterscheidet ℝ von ℚ?", "Vollständigkeit (Supremumsaxiom)", "Archimedisches Axiom", "Körperaxiome", "Anordnung",
            why = "ℚ ist ein archimedisch angeordneter Körper, aber z. B. {x : x² < 2} hat in ℚ kein Supremum."),
        mc(M, 1, "ma_seq", "Welche Folge konvergiert nicht?", "aₙ = (−1)ⁿ", "aₙ = 1/n", "aₙ = (1 + 1/n)ⁿ", "aₙ = n/(n + 1)",
            why = "(−1)ⁿ hat die zwei Häufungspunkte ±1; die anderen konvergieren gegen 0, e und 1."),
        mc(M, 1, "ma_series", "Konvergiert die harmonische Reihe Σ 1/n?", "Nein, sie divergiert (wie ln N).", "Ja, gegen π²/6.", "Ja, gegen e.", "Ja, gegen ln 2.",
            why = "π²/6 ist Σ1/n², ln 2 die alternierende harmonische Reihe. Σ1/n ≥ Σ (Blöcke von 2ᵏ Gliedern ≥ ½) → ∞."),
        mc(M, 2, "ma_series", "Was besagt der Riemannsche Umordnungssatz?", "Bedingt konvergente Reihen lassen sich auf jeden Wert umordnen.",
            "Jede konvergente Reihe ist absolut konvergent.", "Umordnen ändert nie den Wert.", "Potenzreihen konvergieren gleichmäßig.",
            why = "Nur absolut konvergente Reihen sind umordnungsinvariant."),
        mc(M, 2, "ma_continuity", "Welche Funktion ist stetig, aber nicht gleichmäßig stetig auf (0, 1)?", "f(x) = 1/x", "f(x) = x²", "f(x) = sin x", "f(x) = √x",
            why = "Auf (0, 1) bleiben x², sin x und √x gleichmäßig stetig (stetig fortsetzbar auf [0, 1]); 1/x wächst unbeschränkt."),
        mc(M, 2, "ma_taylor", "Welche Funktion ist glatt (C^∞), aber nicht analytisch in 0?", "f(x) = e^{−1/x²}, f(0) = 0", "f(x) = eˣ", "f(x) = sin x", "f(x) = 1/(1 + x²)",
            why = "Alle Ableitungen von e^{−1/x²} verschwinden in 0, die Taylor-Reihe ist 0 ≠ f. 1/(1 + x²) ist analytisch, aber mit Radius 1 (Pole bei ±i)."),
        mc(M, 2, "ma_integral", "Wann darf man Grenzwert und Riemann-Integral vertauschen (kompaktes Intervall)?", "Bei gleichmäßiger Konvergenz",
            "Bei punktweiser Konvergenz", "Immer", "Nur bei monotonen Folgen positiver Funktionen",
            why = "Punktweise reicht nicht (Gegenbeispiel: Zackenfunktionen mit Integral 1). Die monotone Konvergenz ist ein Lebesgue-Satz."),
        mc(M, 2, "ma_topology", "Welche Menge ist kompakt?", "[0, 1] ⊂ ℝ", "(0, 1) ⊂ ℝ", "ℝ", "{1/n : n ∈ ℕ}",
            why = "Heine-Borel: abgeschlossen und beschränkt. {1/n} ist nicht abgeschlossen (0 fehlt); mit 0 wäre sie kompakt."),
        mc(M, 2, "ma_multidiff", "Folgt aus der Existenz aller partiellen Ableitungen die totale Differenzierbarkeit?", "Nein, erst stetige partielle Ableitungen reichen.",
            "Ja, immer.", "Ja, in zwei Dimensionen.", "Nur für Polynome.",
            why = "f = xy/(x² + y²) hat in 0 beide partiellen Ableitungen, ist dort aber nicht einmal stetig."),
        mc(M, 2, "ma_multidiff", "Die Hesse-Matrix im kritischen Punkt hat die Eigenwerte 3 und −1. Was liegt vor?", "Ein Sattelpunkt", "Ein Minimum", "Ein Maximum", "Keine Aussage möglich",
            why = "Indefinit ⇒ Sattel. Semidefinit (ein Eigenwert 0) wäre der Fall „keine Aussage“."),
        mc(M, 2, "ma_implicit", "Welche Bedingung braucht der Satz über implizite Funktionen für F(x, y) = 0 → y = g(x)?", "∂F/∂y ist im Punkt invertierbar.",
            "∂F/∂x = 0", "F ist linear.", "F ist beschränkt.",
            why = "Dann lässt sich lokal nach y auflösen, mit g' = −(∂_yF)⁻¹∂_xF."),
        mc(M, 2, "ma_curves", "Das Feld F = (−y, x)/(x² + y²) auf ℝ² ∖ {0} ist rotationsfrei. Ist es ein Gradientenfeld?", "Nein, das Umlaufintegral um 0 ist 2π.",
            "Ja, weil rot F = 0.", "Ja, mit φ = ln r.", "Nur auf der oberen Halbebene nicht.",
            why = "Das Gebiet ist nicht einfach zusammenhängend; lokal ist F = ∇φ mit φ = Winkel, global ist der Winkel mehrdeutig."),
        mc(M, 2, "ma_measure", "Welches Lebesgue-Maß hat ℚ ∩ [0, 1]?", "0", "1", "½", "nicht messbar",
            why = "Abzählbare Mengen sind Nullmengen: Überdecke den n-ten Punkt mit einem Intervall der Länge ε/2ⁿ."),
        mc(M, 2, "ma_lebesgue", "Ist die Dirichlet-Funktion 1_ℚ auf [0, 1] integrierbar?", "Lebesgue ja (Integral 0), Riemann nein",
            "Riemann ja, Lebesgue nein", "Beide nein", "Beide ja, Integral 1",
            why = "Ober- und Untersummen sind 1 bzw. 0; im Lebesgue-Sinn ist 1_ℚ fast überall 0."),
        mc(M, 3, "ma_lebesgue", "Welcher Satz erlaubt lim ∫ fₙ = ∫ lim fₙ, wenn |fₙ| ≤ g mit integrierbarem g?", "Satz von der majorisierten Konvergenz",
            "Satz von Fubini", "Lemma von Fatou", "Satz von Radon-Nikodym",
            why = "Lebesgue; Fatou liefert nur die Ungleichung ∫ liminf ≤ liminf ∫, monotone Konvergenz braucht 0 ≤ fₙ ↑."),
        mc(M, 2, "ma_fubini", "Welche Funktionaldeterminante gehört zu Kugelkoordinaten (r, θ, φ)?", "r² sin θ", "r", "r sin θ", "r² cos θ",
            why = "dV = r² sin θ dr dθ dφ; Zylinderkoordinaten: ρ dρ dφ dz."),
        mc(M, 3, "ma_fubini", "Was garantiert Tonelli für messbare f ≥ 0?", "Die iterierten Integrale sind gleich (eventuell ∞).",
            "f ist integrierbar.", "f ist stetig.", "Das Integral ist endlich.",
            why = "Für nicht-negative Funktionen ist Vertauschen immer erlaubt; Fubini braucht für Vorzeichenwechsel ∫|f| < ∞."),
        mc(M, 2, "ma_vector", "Welche Identität gilt für glatte Felder?", "div rot A = 0", "rot div A = 0", "div grad φ = 0", "rot rot A = 0",
            why = "Auch rot grad φ = 0. div grad = Δ und rot rot = grad div − Δ verschwinden nicht im Allgemeinen."),
        mc(M, 3, "ma_forms", "Welcher Satz fasst Gauß, Stokes und den Hauptsatz zusammen?", "∫_M dω = ∫_{∂M} ω", "dd = 0", "Poincaré-Lemma", "Satz von de Rham",
            why = "Der allgemeine Satz von Stokes für Differentialformen; dd = 0 entspricht rot grad = 0 und div rot = 0."),
        mc(M, 2, "ma_linalg2", "Wann ist eine Matrix diagonalisierbar?", "Wenn geometrische = algebraische Vielfachheit für jeden Eigenwert gilt",
            "Wenn det A ≠ 0", "Immer über ℂ", "Wenn alle Eigenwerte gleich sind",
            why = "Gegenbeispiel Jordan-Block (1 1; 0 1): invertierbar, Eigenwert 1 doppelt, aber nur ein Eigenvektor."),
        mc(M, 2, "ma_linalg2", "Was liefert die Singulärwertzerlegung A = UΣVᵀ?", "Die beste Approximation niedrigen Rangs (Eckart-Young)",
            "Nur die Eigenwerte", "Die Determinante als Summe", "Eine obere Dreiecksmatrix",
            why = "Abschneiden nach k Singulärwerten minimiert ‖A − A_k‖₂ = σ_{k+1}; Grundlage von PCA und Datenkompression."),
        mc(M, 2, "ma_ode_theory", "Welche Voraussetzung garantiert nach Picard-Lindelöf eindeutige Lösungen von y' = f(t, y)?", "f ist lokal Lipschitz-stetig in y.",
            "f ist stetig.", "f ist beschränkt.", "f ist linear.",
            why = "Nur Stetigkeit (Peano) gibt Existenz ohne Eindeutigkeit: y' = √|y| hat ab y(0) = 0 unendlich viele Lösungen."),
        mc(M, 2, "ma_pde", "Welcher Typ ist die Wärmeleitungsgleichung u_t = Du_xx?", "Parabolisch", "Elliptisch", "Hyperbolisch", "Gemischt",
            why = "Laplace ist elliptisch, die Wellengleichung hyperbolisch; die Diffusion glättet sofort und hat unendliche Ausbreitungsgeschwindigkeit."),
        mc(M, 3, "ma_functional", "Was besagt der Satz von Riesz für Hilbert-Räume?", "Jedes stetige lineare Funktional ist ein Skalarprodukt mit einem festen Vektor.",
            "Jeder Operator ist diagonalisierbar.", "Jede Cauchy-Folge konvergiert.", "Die Einheitskugel ist kompakt.",
            why = "H ≅ H*: Grundlage der Bra-Ket-Notation ⟨φ|. Die Einheitskugel ist in ∞ Dimensionen gerade nicht kompakt."),
        mc(M, 3, "ma_functional", "Warum ist der Ortsoperator x̂ auf L²(ℝ) nicht überall definiert?", "Er ist unbeschränkt; x·ψ liegt nicht für jedes ψ ∈ L² in L².",
            "Er ist nicht linear.", "Er ist nicht hermitesch.", "L² ist nicht vollständig.",
            why = "Hellinger-Toeplitz: Ein überall definierter symmetrischer Operator ist beschränkt. x̂ und p̂ leben auf dichten Teilräumen."),
        mc(M, 2, "ma_variation", "Welche Kurve minimiert die Laufzeit zwischen zwei Punkten im Schwerefeld (Brachistochrone)?", "Eine Zykloide", "Eine Gerade", "Ein Kreisbogen", "Eine Parabel",
            why = "Die Euler-Lagrange-Gleichung für T = ∫√((1 + y'²)/(2gy)) dx (mit Beltrami-Identität) führt auf die Zykloide."),
        mc(M, 2, "ma_tensor", "Wie transformieren die Komponenten eines kovarianten Vektors (1-Form) ωᵢ?", "ω'ᵢ = (∂xʲ/∂x'ⁱ) ωⱼ", "ω'ᵢ = (∂x'ⁱ/∂xʲ) ωⱼ", "Gar nicht", "Wie Skalare",
            why = "Wie der Gradient ∂ᵢφ; kontravariante Komponenten (Tangentialvektoren) transformieren mit ∂x'ⁱ/∂xʲ.")
    )
}
