package app.maximus.lab.domain

/**
 * Concept questions ("Verständnisfragen"): no numbers to compute, no formula to remember by heart —
 * they test whether the physics is understood. The first option is correct; [why] explains the right
 * answer and, where useful, why the tempting wrong options fail.
 */
internal object QuizConcepts {
    private var n = 0
    private fun c(topic: Topic, diff: Int, chapter: String, prompt: String, correct: String, vararg wrong: String, why: String) =
        Question("cq-${topic.short}-${++n}", topic, diff, prompt, why, listOf(correct) + wrong, 0, chapterKey = chapter)

    private val T = Topic.THERMO
    private val E = Topic.ELECTRO
    private val Q = Topic.QUANTUM
    private val S = Topic.SEMICONDUCTOR
    private val C = Topic.CALORIC
    private val F = Topic.QFT
    private val K = Topic.MECHANICS
    private val M = Topic.MATH

    val all: List<Question> = listOf(
        // ---------------- Thermodynamik ----------------
        c(T, 1, "th_laws", "Ein Gas wird in einem Kolben schnell komprimiert. Warum wird es warm, obwohl keine Wärme zugeführt wird?",
            "Die am Gas verrichtete Arbeit erhöht seine innere Energie.", "Durch Reibung der Moleküle an der Wand.",
            "Weil die Entropie sinkt.", "Weil der Druck die Temperatur direkt erzeugt.",
            why = "Erster Hauptsatz: ΔU = Q + W. Bei schneller (adiabatischer) Kompression ist Q ≈ 0, also ΔU = W > 0, und beim idealen Gas ist U ∝ T."),
        c(T, 1, "th_laws", "Was unterscheidet Wärme von innerer Energie?", "Wärme ist Energie im Übergang, innere Energie ist eine Zustandsgröße.",
            "Wärme ist die kinetische, innere Energie die potentielle Energie der Teilchen.", "Es sind zwei Namen für dieselbe Größe.",
            "Wärme ist immer größer als die innere Energie.",
            why = "Ein Körper „enthält“ keine Wärme. Q beschreibt Energie, die wegen eines Temperaturunterschieds fließt, und hängt vom Prozessweg ab (δQ ist kein vollständiges Differential)."),
        c(T, 2, "th_laws", "Warum ist ein Perpetuum mobile zweiter Art unmöglich?",
            "Es würde Wärme aus einem einzigen Reservoir vollständig in Arbeit umwandeln und so die Gesamtentropie senken.",
            "Es würde Energie aus dem Nichts erzeugen.", "Reibung lässt sich nie vollständig vermeiden.", "Die Lichtgeschwindigkeit begrenzt jede Maschine.",
            why = "Energie aus dem Nichts wäre ein Perpetuum mobile erster Art (1. Hauptsatz). Die zweite Art verletzt nur den 2. Hauptsatz (Kelvin-Planck)."),
        c(T, 2, "th_gas", "Warum ist c_p größer als c_V?", "Bei konstantem Druck dehnt sich das Gas aus und verrichtet zusätzlich Arbeit.",
            "Bei konstantem Druck bewegen sich die Moleküle schneller.", "Weil sich bei konstantem Volumen keine Teilchen bewegen.",
            "c_p ist nur bei Festkörpern größer.",
            why = "Die zugeführte Wärme muss bei p = const auch die Ausdehnungsarbeit p dV liefern. Für das ideale Gas: c_p − c_V = R pro Mol."),
        c(T, 2, "th_gas", "Was berücksichtigt die Van-der-Waals-Gleichung gegenüber dem idealen Gas?",
            "Eigenvolumen der Teilchen und ihre gegenseitige Anziehung.", "Quanteneffekte bei tiefen Temperaturen.",
            "Die Gravitation zwischen den Teilchen.", "Die Rotation der Moleküle.",
            why = "b verkleinert das freie Volumen, a/V² senkt den Druck durch Anziehung. Damit beschreibt sie qualitativ auch Kondensation und den kritischen Punkt."),
        c(T, 2, "th_cycles", "Wie steigert man den Wirkungsgrad einer Wärmekraftmaschine prinzipiell am wirksamsten?",
            "Den Temperaturunterschied zwischen heißem und kaltem Reservoir vergrößern.", "Das Arbeitsgas wechseln.",
            "Die Maschine größer bauen.", "Den Kreisprozess schneller durchlaufen.",
            why = "Die Obergrenze ist η_C = 1 − T_k/T_w und hängt nur von den Temperaturen ab. Schnellere Zyklen erhöhen die Leistung, aber durch Irreversibilitäten nicht den Wirkungsgrad."),
        c(T, 2, "th_cycles", "Eine Wärmepumpe liefert mehr Heizwärme, als sie elektrische Energie aufnimmt. Verletzt das den Energiesatz?",
            "Nein, sie holt zusätzlich Wärme aus der kalten Umgebung.", "Ja, deshalb funktionieren nur Pumpen mit Leistungszahl < 1.",
            "Nein, die Energie entsteht durch Kompression aus dem Nichts.", "Ja, aber der 2. Hauptsatz erlaubt das ausnahmsweise.",
            why = "Q_w = W + Q_k. Die Leistungszahl Q_w/W > 1 ist erlaubt; begrenzt wird sie durch T_w/(T_w − T_k)."),
        c(T, 3, "th_potentials", "Warum benutzt man bei Experimenten bei konstantem T und p die Gibbs-Energie statt der inneren Energie?",
            "Sie ist bei festem T und p im Gleichgewicht minimal; ihre natürlichen Variablen sind genau die kontrollierten Größen.",
            "Weil die innere Energie bei konstantem Druck nicht definiert ist.", "Weil G immer kleiner als U ist.", "Aus historischen Gründen.",
            why = "Legendre-Transformation: Jedes Potential ist in seinen natürlichen Variablen extremal. U(S, V) passt zu isolierten Systemen, G(T, p) zum Labor."),
        c(T, 2, "th_phase", "Warum bleibt die Temperatur beim Sieden von Wasser konstant, obwohl man weiter heizt?",
            "Die Energie geht in die latente Wärme, also in das Aufbrechen der Bindungen zwischen den Molekülen.", "Weil das Thermometer träge ist.",
            "Weil der Dampf die Wärme sofort abführt, ohne Energie aufzunehmen.", "Weil Wasser keine Wärmekapazität mehr hat.",
            why = "Bei einem Phasenübergang 1. Ordnung erhöht die zugeführte Wärme die Entropie (ΔS = L/T), nicht die Temperatur, bis die Phase vollständig umgewandelt ist."),
        c(T, 3, "th_phase", "Was charakterisiert einen Phasenübergang 2. Ordnung (z. B. Ferromagnet am Curie-Punkt)?",
            "Keine latente Wärme, aber divergierende Suszeptibilität und Korrelationslänge.", "Eine große latente Wärme.",
            "Ein Sprung in der Dichte.", "Zwei koexistierende Phasen bei derselben Temperatur.",
            why = "Der Ordnungsparameter geht stetig gegen null; zweite Ableitungen von G (Wärmekapazität, Suszeptibilität) zeigen Singularitäten — Grundlage der kritischen Exponenten."),
        c(T, 2, "th_stat", "Was bedeutet die Entropie mikroskopisch (Boltzmann)?",
            "Sie misst die Zahl der Mikrozustände, die mit dem Makrozustand verträglich sind: S = k_B ln Ω.", "Sie misst die mittlere Geschwindigkeit der Teilchen.",
            "Sie ist die Wärme pro Teilchen.", "Sie zählt die Teilchen im System.",
            why = "Mehr zugängliche Mikrozustände heißt höhere Entropie. Der 2. Hauptsatz wird dadurch statistisch: Makrozustände mit überwältigend vielen Mikrozuständen sind fast sicher."),
        c(T, 3, "th_stat", "Warum frieren Freiheitsgrade (z. B. Molekülschwingungen) bei tiefen Temperaturen aus?",
            "Ihre Anregungsenergie ħω ist viel größer als k_BT; der Gleichverteilungssatz gilt nur für k_BT ≫ ħω.", "Weil die Moleküle sich bei Kälte nicht mehr bewegen.",
            "Weil die Schwingungen bei Kälte instabil werden.", "Weil das Volumen schrumpft.",
            why = "Das ist ein Quanteneffekt: Ein Oszillator mit diskreten Niveaus ist für k_BT ≪ ħω fast immer im Grundzustand. Daher hat H₂ bei Raumtemperatur c_V ≈ 5/2 R statt 7/2 R."),
        c(T, 2, "th_transport", "Warum fühlt sich Metall bei gleicher Temperatur kälter an als Holz?",
            "Metall leitet die Wärme viel schneller von der Haut ab.", "Metall ist tatsächlich kälter.", "Holz erzeugt Wärme.",
            "Metall hat eine geringere spezifische Wärmekapazität, deshalb ist es kälter.",
            why = "Die Haut spürt den Wärmestrom, nicht die Temperatur. Entscheidend ist die Wärmeeindringzahl √(λρc), die bei Metallen viel größer ist."),
        c(T, 3, "th_transport", "Warum geht bei Diffusion die mittlere Verschiebung wie √t und nicht wie t?",
            "Die Schritte einer Zufallsbewegung haben zufällige Richtungen; nur die Varianzen addieren sich, ⟨x²⟩ = 2Dt.",
            "Weil die Teilchen mit der Zeit langsamer werden.", "Weil die Reibung mit der Zeit zunimmt.", "Weil die Teilchen zurückgestoßen werden.",
            why = "Bei N unabhängigen Schritten der Länge ℓ ist ⟨x⟩ = 0 und ⟨x²⟩ = Nℓ² ∝ t. Deshalb dauert Diffusion über die doppelte Strecke viermal so lange."),

        // ---------------- Elektrodynamik ----------------
        c(E, 1, "el_static", "Warum ist das elektrische Feld im Inneren eines Leiters im Gleichgewicht null?",
            "Freie Ladungen verschieben sich so lange, bis ihr Feld das äußere Feld im Inneren aufhebt.", "Weil Metalle keine Ladungen enthalten.",
            "Weil das Feld vom Leiter absorbiert und in Wärme umgewandelt wird.", "Das stimmt nur für Supraleiter.",
            why = "Ein Restfeld würde Ströme treiben, also kein Gleichgewicht. Folgen: Ladungen sitzen an der Oberfläche, der Leiter ist äquipotential (Faraday-Käfig)."),
        c(E, 2, "el_static", "Was besagt der Gaußsche Satz der Elektrostatik anschaulich?",
            "Der Fluss des Feldes durch eine geschlossene Fläche ist proportional zur eingeschlossenen Ladung.",
            "Das Feld einer Punktladung ist überall gleich stark.", "Feldlinien sind immer geschlossen.", "Die Spannung um eine geschlossene Kurve ist null.",
            why = "Ladungen sind Quellen der Feldlinien. Die Form der Fläche ist egal; bei Symmetrie folgt daraus sofort das Feld (Kugel, Zylinder, Ebene)."),
        c(E, 2, "el_static", "Was passiert mit der Kapazität, wenn man ein Dielektrikum in einen Plattenkondensator schiebt?",
            "Sie steigt um den Faktor ε_r, weil Polarisationsladungen das Feld teilweise kompensieren.", "Sie sinkt, weil das Dielektrikum isoliert.",
            "Sie bleibt gleich, nur die Spannung ändert sich.", "Sie wird null.",
            why = "Gebundene Ladungen an den Oberflächen des Dielektrikums schwächen das Feld bei gleicher freier Ladung; kleinere Spannung bei gleichem Q bedeutet C = Q/U größer."),
        c(E, 1, "el_circuits", "Zwei gleiche Widerstände werden einmal in Reihe, einmal parallel an dieselbe Spannung gelegt. Wo wird mehr Leistung umgesetzt?",
            "Parallel, viermal so viel wie in Reihe.", "In Reihe, doppelt so viel.", "In beiden Fällen gleich viel.", "Parallel, doppelt so viel.",
            why = "P = U²/R_ges: in Reihe 2R, parallel R/2, Verhältnis 4."),
        c(E, 2, "el_circuits", "Was bestimmt die Zeitkonstante eines RC-Glieds, und was bedeutet sie?",
            "τ = RC; nach τ ist die Spannung auf 1/e (≈ 37 %) ihres Anfangsabstands zum Endwert abgeklungen.",
            "τ = R/C; danach ist der Kondensator voll geladen.", "τ = 1/(RC); die Frequenz des Stroms.", "τ hängt nur von der Spannung ab.",
            why = "Die Kirchhoff-Gleichung RC dU/dt + U = U₀ hat die Lösung mit e^{−t/RC}. Nach 5τ sind 99 % erreicht."),
        c(E, 2, "el_magneto", "Warum verrichtet die Lorentz-Kraft an einer bewegten Ladung keine Arbeit?",
            "Sie steht immer senkrecht zur Geschwindigkeit.", "Weil Magnetfelder keine Energie enthalten.", "Weil die Ladung zu klein ist.",
            "Sie verrichtet Arbeit, aber nur in Supraleitern.",
            why = "F = qv × B ⊥ v, also F · v = 0. Das Magnetfeld ändert nur die Richtung (Kreisbahn im Zyklotron), nicht den Betrag der Geschwindigkeit."),
        c(E, 2, "el_magneto", "Warum gibt es keine magnetischen Monopole in den Maxwell-Gleichungen?",
            "Weil div B = 0: Feldlinien von B haben weder Anfang noch Ende.", "Weil sie zu schwer sind, um gemessen zu werden.",
            "Weil sie sich gegenseitig auslöschen.", "Weil das Erdmagnetfeld sie abschirmt.",
            why = "Jeder Magnet hat Nord- und Südpol; beim Zerbrechen entstehen wieder Dipole. Monopole wären mit der Quantenmechanik vereinbar (Dirac), wurden aber nie gefunden."),
        c(E, 1, "el_induction", "Wann wird in einer Leiterschleife eine Spannung induziert?",
            "Wenn sich der magnetische Fluss durch die Schleife ändert.", "Immer, wenn ein Magnetfeld vorhanden ist.",
            "Nur, wenn die Schleife aus Kupfer ist.", "Wenn ein konstanter Strom durch sie fließt.",
            why = "Faraday: U_ind = −dΦ/dt. Ein starkes, aber konstantes Feld induziert nichts; es kommt auf die Änderung an (Feld, Fläche oder Winkel)."),
        c(E, 2, "el_induction", "Was drückt das Minuszeichen in der Lenzschen Regel aus?",
            "Der induzierte Strom wirkt seiner Ursache entgegen.", "Die induzierte Spannung ist immer negativ.",
            "Die Elektronen fließen rückwärts.", "Es ist reine Konvention ohne physikalische Bedeutung.",
            why = "Es folgt aus der Energieerhaltung: Würde der induzierte Strom die Flussänderung verstärken, entstünde Energie aus dem Nichts. Beispiel: Wirbelstrombremse."),
        c(E, 3, "el_maxwell", "Wozu führte Maxwell den Verschiebungsstrom ε₀ ∂E/∂t ein?",
            "Ohne ihn widerspräche das Ampèresche Gesetz der Ladungserhaltung; mit ihm folgen elektromagnetische Wellen.",
            "Um den Strom in Leitern genauer zu beschreiben.", "Um den Ohmschen Widerstand zu erklären.", "Um die Gravitation einzubauen.",
            why = "div(rot B) = 0 verlangt div j = 0, im Widerspruch zu ∂ρ/∂t ≠ 0 (Kondensator). Der Zusatzterm repariert das und koppelt E und B zu Wellen mit c = 1/√(μ₀ε₀)."),
        c(E, 2, "el_maxwell", "Welche Beziehung haben E, B und Ausbreitungsrichtung in einer ebenen elektromagnetischen Welle im Vakuum?",
            "E und B stehen senkrecht aufeinander und auf der Ausbreitungsrichtung; |E| = c|B|.", "E und B sind parallel zur Ausbreitungsrichtung.",
            "E und B sind parallel zueinander.", "B ist immer null.",
            why = "Die Welle ist transversal; E × B zeigt in Ausbreitungsrichtung (Poynting-Vektor). E und B schwingen in Phase."),
        c(E, 3, "el_maxwell", "Warum ist Licht in einem Medium langsamer als im Vakuum?",
            "Die Felder regen die Ladungen des Mediums zum Mitschwingen an; deren abgestrahlte Felder überlagern sich zu einer phasenverzögerten Welle.",
            "Photonen stoßen an Atome und werden abgebremst.", "Das Medium ist dichter, deshalb ist der Weg länger.", "Weil sich die Lichtgeschwindigkeit im Medium ändert, aber nicht die Phase.",
            why = "Die Phasengeschwindigkeit c/n entsteht aus der kohärenten Überlagerung; einzelne Photonen fliegen zwischen den Atomen mit c. n hängt über die Resonanzen von ω ab (Dispersion)."),

        // ---------------- Quantenphysik ----------------
        c(Q, 1, "qm_origins", "Was zeigte der Photoeffekt, das klassisch nicht erklärbar ist?",
            "Die Elektronenenergie hängt von der Frequenz, nicht von der Intensität des Lichts ab.", "Licht wird an Metallen reflektiert.",
            "Starkes Licht löst mehr Elektronen aus.", "Elektronen haben eine Ladung.",
            why = "Klassisch müsste hohe Intensität jede Frequenz wirksam machen. Einstein: Licht kommt in Quanten E = hf; unter der Grenzfrequenz löst auch helles Licht nichts aus."),
        c(Q, 2, "qm_origins", "Was zeigt das Doppelspaltexperiment mit einzelnen Elektronen?",
            "Jedes Elektron trifft punktförmig auf, das Interferenzmuster baut sich aber statistisch auf.", "Elektronen gehen immer durch einen bestimmten Spalt.",
            "Elektronen erzeugen kein Muster, nur Licht tut das.", "Das Muster entsteht nur, wenn viele Elektronen gleichzeitig fliegen.",
            why = "Die Wahrscheinlichkeitsamplitude geht durch beide Spalte. Misst man den Weg, verschwindet die Interferenz (Komplementarität)."),
        c(Q, 2, "qm_formalism", "Was bedeutet |ψ(x)|²?", "Die Wahrscheinlichkeitsdichte, das Teilchen bei einer Messung am Ort x zu finden.",
            "Die Ladungsdichte des Elektrons.", "Die Energie des Teilchens am Ort x.", "Den Ort, an dem sich das Teilchen tatsächlich befindet.",
            why = "Bornsche Regel. ψ selbst ist eine komplexe Amplitude; nur Betragsquadrate (und relative Phasen über Interferenz) sind messbar."),
        c(Q, 2, "qm_formalism", "Warum müssen Observable durch hermitesche Operatoren dargestellt werden?",
            "Hermitesche Operatoren haben reelle Eigenwerte und orthogonale Eigenvektoren — Messwerte sind reell.",
            "Weil sie immer invertierbar sind.", "Weil sie mit dem Hamilton-Operator kommutieren.", "Damit die Wellenfunktion normiert bleibt.",
            why = "Messergebnisse sind Eigenwerte. Die Normerhaltung der Zeitentwicklung folgt dagegen aus der Hermitizität von Ĥ (unitäre Zeitentwicklung)."),
        c(Q, 2, "qm_formalism", "Was sagt die Unschärferelation Δx Δp ≥ ħ/2 aus?",
            "Ort und Impuls haben in keinem Zustand gleichzeitig beliebig scharfe Werte.", "Messgeräte sind nie genau genug.",
            "Eine Messung stört das Teilchen immer um ħ.", "Teilchen bewegen sich zufällig.",
            why = "Sie folgt aus [x, p] = iħ und gilt für die Streuungen im Zustand selbst, unabhängig von der Messtechnik (Robertson)."),
        c(Q, 2, "qm_1d", "Warum hat ein Teilchen im Kasten eine Nullpunktsenergie > 0?",
            "Ein ruhendes Teilchen mit bekanntem Ort würde die Unschärferelation verletzen; die Randbedingungen lassen nur n ≥ 1 zu.",
            "Weil es sich an den Wänden reibt.", "Weil die Wände Energie abgeben.", "Das stimmt nicht; der Grundzustand hat E = 0.",
            why = "Eingesperrt auf L ist Δp ≳ ħ/L, also E ≳ ħ²/(2mL²). Die Lösung ψ = 0 für n = 0 ist nicht normierbar."),
        c(Q, 2, "qm_1d", "Wovon hängt die Tunnelwahrscheinlichkeit durch eine Barriere am stärksten ab?",
            "Exponentiell von Breite und Wurzel aus (V₀ − E).", "Linear von der Barrierenhöhe.", "Von der Ladung allein.", "Nur von der Teilchenmasse, nicht von der Breite.",
            why = "T ≈ e^{−2κd} mit κ = √(2m(V₀ − E))/ħ. Daher die extreme Empfindlichkeit des Rastertunnelmikroskops auf den Abstand."),
        c(Q, 2, "qm_hydrogen", "Warum strahlt das Elektron im Grundzustand des Wasserstoffatoms nicht und stürzt nicht in den Kern?",
            "Der Grundzustand ist ein stationärer Zustand mit der niedrigsten Energie; es gibt keinen tieferen Zustand.", "Weil das Elektron zu schnell ist.",
            "Weil die Kernkraft es abstößt.", "Es strahlt, aber zu schwach.",
            why = "Stationäre Zustände haben zeitlich konstante Ladungsverteilung, also keinen oszillierenden Dipol. Die Unschärfe verhindert den Kollaps (Ortsenergie gegen Impulsenergie)."),
        c(Q, 3, "qm_hydrogen", "Warum sind im Wasserstoffatom (ohne Feinstruktur) die Zustände mit gleichem n, aber verschiedenem l entartet?",
            "Wegen einer zusätzlichen Symmetrie des 1/r-Potentials (Runge-Lenz-Vektor, SO(4)).", "Weil das Elektron keinen Drehimpuls hat.",
            "Weil l immer null ist.", "Das ist bei jedem Zentralpotential so.",
            why = "Allgemeine Zentralpotentiale liefern nur die m-Entartung (Kugelsymmetrie). Die l-Entartung ist eine Besonderheit des Coulomb-Potentials, so wie die geschlossenen Kepler-Bahnen."),
        c(Q, 2, "qm_spin", "Was zeigte der Stern-Gerlach-Versuch?", "Der Drehimpuls (Spin) ist quantisiert: Der Strahl spaltet sich in diskrete Teilstrahlen.",
            "Silberatome haben keine magnetischen Eigenschaften.", "Die Spinrichtung ist kontinuierlich verteilt.", "Elektronen kreisen um den Kern.",
            why = "Klassisch erwartete man einen verschmierten Fleck. Zwei Teilstrahlen bedeuten s = ½ mit m_s = ±½."),
        c(Q, 3, "qm_spin", "Warum dürfen zwei Elektronen nicht im selben Quantenzustand sein?",
            "Die Gesamtwellenfunktion identischer Fermionen ist antisymmetrisch; für gleiche Zustände wäre sie null.", "Weil sie sich elektrisch abstoßen.",
            "Weil Elektronen verschiedene Massen haben.", "Das gilt nur in Atomen mit vielen Elektronen.",
            why = "Pauli-Prinzip, Folge des Spin-Statistik-Theorems. Es erklärt das Periodensystem, die Stabilität der Materie und den Fermi-Druck in Weißen Zwergen."),
        c(Q, 2, "qm_approx", "Wann ist Störungstheorie erster Ordnung zuverlässig?",
            "Wenn die Matrixelemente der Störung klein gegen die Abstände der ungestörten Niveaus sind.", "Immer, wenn die Störung zeitabhängig ist.",
            "Nur bei entarteten Niveaus.", "Wenn die Störung größer als der ungestörte Hamilton-Operator ist.",
            why = "Die Korrektur 2. Ordnung enthält |V_mn|²/(E_n − E_m). Bei Entartung muss man zuerst in der entarteten Unterbasis diagonalisieren."),
        c(Q, 3, "qm_info", "Was ist bei verschränkten Teilchen mit getrennten Messungen NICHT möglich?",
            "Information schneller als Licht zu übertragen.", "Korrelationen zu messen, die klassisch unmöglich sind.",
            "Bellsche Ungleichungen zu verletzen.", "Quantenteleportation durchzuführen.",
            why = "Die Messergebnisse einer Seite sind lokal zufällig; die Korrelationen zeigen sich erst beim klassischen Vergleich (No-Signaling). Teleportation braucht ebenfalls einen klassischen Kanal."),

        // ---------------- Halbleiter ----------------
        c(S, 1, "sc_bands", "Warum leitet ein Isolator keinen Strom, obwohl er viele Elektronen enthält?",
            "Das Valenzband ist voll; ein volles Band trägt keinen Nettostrom, und die Bandlücke ist zu groß für thermische Anregung.",
            "Seine Elektronen sind fest an den Kernen gebunden und können sich gar nicht bewegen.", "Weil Isolatoren keine freien Atome haben.",
            "Er leitet, aber nur Wechselstrom.",
            why = "Zu jedem Zustand k gibt es −k; im vollen Band heben sich alle Beiträge auf. Leitung braucht teilweise besetzte Bänder."),
        c(S, 2, "sc_bands", "Was ist ein Loch im Halbleiter?",
            "Ein fehlendes Elektron im fast vollen Valenzband, das sich wie ein positives Teilchen mit positiver effektiver Masse verhält.",
            "Ein Proton, das sich im Kristall bewegt.", "Eine Lücke im Kristallgitter.", "Ein freies Positron.",
            why = "Die Dynamik des fast vollen Bandes lässt sich durch die wenigen leeren Zustände beschreiben; das Vorzeichen der Hall-Spannung bestätigt die positive Ladung."),
        c(S, 2, "sc_bands", "Warum leuchtet Silizium kaum, GaAs aber gut?",
            "Silizium hat eine indirekte Bandlücke; für Rekombination ist ein Phonon nötig. GaAs hat eine direkte Lücke.",
            "Silizium ist nicht rein genug.", "Silizium hat eine zu kleine Bandlücke.", "GaAs enthält mehr Elektronen.",
            why = "Photonen tragen fast keinen Impuls. Bei indirekter Lücke liegen Leitungsband-Minimum und Valenzband-Maximum bei verschiedenem k; der Übergang braucht einen Dreierprozess."),
        c(S, 1, "sc_carriers", "Was bewirkt n-Dotierung (z. B. Phosphor in Silizium)?",
            "Zusätzliche Elektronen nahe am Leitungsband, die schon bei Raumtemperatur frei werden.", "Mehr Löcher im Valenzband.",
            "Eine größere Bandlücke.", "Der Kristall wird negativ geladen.",
            why = "Phosphor hat ein Valenzelektron mehr; es ist nur mit ~45 meV gebunden. Der Kristall bleibt neutral, denn die ionisierten Donatoren sind positiv."),
        c(S, 2, "sc_carriers", "Was besagt das Massenwirkungsgesetz n · p = n_i²?",
            "Im Gleichgewicht ist das Produkt der Ladungsträgerdichten unabhängig von der Dotierung.", "Elektronen und Löcher sind immer gleich viele.",
            "Die Dotierung erhöht beide Dichten.", "Es gilt nur in undotierten Halbleitern.",
            why = "Mehr Elektronen bedeuten mehr Rekombination, die Löcherdichte sinkt entsprechend. n_i hängt nur von Material und Temperatur ab (∝ e^{−E_g/2k_BT})."),
        c(S, 2, "sc_transport", "Was ist der Unterschied zwischen Drift- und Diffusionsstrom?",
            "Drift wird von einem elektrischen Feld getrieben, Diffusion von einem Konzentrationsgefälle.", "Drift gibt es nur für Löcher.",
            "Diffusion ist schneller als Drift.", "Es gibt keinen Unterschied.",
            why = "Im pn-Übergang im Gleichgewicht heben sich beide genau auf. Verknüpft sind sie über die Einstein-Relation D = μk_BT/e."),
        c(S, 2, "sc_pn", "Wie entsteht die Raumladungszone im pn-Übergang?",
            "Majoritätsträger diffundieren über die Grenze und rekombinieren; zurück bleiben ortsfeste ionisierte Dotieratome.",
            "Durch eine äußere Spannung beim Herstellen.", "Durch Verunreinigungen an der Grenzfläche.", "Weil sich Elektronen an der Grenze stauen.",
            why = "Die ionisierten Donatoren (+) und Akzeptoren (−) erzeugen ein Feld, das die weitere Diffusion stoppt: Gleichgewicht bei der Diffusionsspannung."),
        c(S, 2, "sc_pn", "Warum leitet eine Diode in Durchlassrichtung exponentiell besser?",
            "Die Spannung senkt die Potentialbarriere, und die Zahl der Träger, die sie überwinden, wächst wie e^{eU/k_BT}.",
            "Weil der Widerstand mit der Spannung linear sinkt.", "Weil die Diode warm wird.", "Weil die Raumladungszone breiter wird.",
            why = "Boltzmann-Faktor: Shockley-Gleichung I = I_s(e^{eU/k_BT} − 1). In Sperrrichtung bleibt nur der kleine Sättigungsstrom."),
        c(S, 2, "sc_opto", "Warum liefert eine Solarzelle maximal eine Leerlaufspannung unterhalb von E_g/e?",
            "Rekombination und die thermische Besetzung begrenzen die Aufspaltung der Quasi-Fermi-Niveaus.", "Weil Licht keine Energie über E_g hat.",
            "Weil die Elektronen zu langsam sind.", "Wegen des Widerstands der Kontakte allein.",
            why = "U_oc = (k_BT/e) ln(I_ph/I_s + 1) < E_g/e. Photonen über E_g geben den Überschuss als Wärme ab (Thermalisierung) — Teil der Shockley-Queisser-Grenze."),
        c(S, 3, "sc_transistor", "Wie schaltet ein MOSFET?",
            "Die Gate-Spannung erzeugt über das Oxid eine Inversionsschicht, die Source und Drain leitend verbindet.",
            "Durch einen Steuerstrom in die Basis.", "Durch Erwärmung des Kanals.", "Durch ein Magnetfeld am Gate.",
            why = "Feldeffekt: Ab der Schwellspannung sammeln sich Minoritätsträger unter dem Gate. Fast kein Gate-Strom — deshalb so sparsam in CMOS-Logik."),

        // ---------------- Kalorik ----------------
        c(C, 1, "ca_thermo", "Was ist der gemeinsame Kern aller kalorischen Effekte?",
            "Ein äußeres Feld ändert die Ordnung (Entropie) eines Freiheitsgrads; adiabatisch geht das als Temperaturänderung ins Gitter.",
            "Ein Feld erzeugt direkt Wärme durch Joulesche Verluste.", "Ein Feld ändert die Masse des Materials.", "Es sind chemische Reaktionen.",
            why = "Bei konstanter Gesamtentropie muss eine feldinduzierte Entropieänderung ΔS_Feld durch die Gitterentropie ausgeglichen werden: ΔT_ad ≈ −T ΔS_Feld/c."),
        c(C, 2, "ca_thermo", "Warum sind kalorische Effekte nahe einem Phasenübergang am größten?",
            "Dort ändert sich die Ordnung schon bei kleinen Feldern stark, die Entropieänderung pro Feld ist maximal.", "Weil das Material dort am kältesten ist.",
            "Weil die Wärmekapazität dort null ist.", "Weil dort keine Hysterese auftritt.",
            why = "Maxwell-Relationen wie (∂S/∂E)_T = (∂P/∂T)_E sind groß, wenn der Ordnungsparameter steil von T abhängt. Nachteil: Hysterese bei Übergängen 1. Ordnung."),
        c(C, 2, "ca_electro", "Was passiert beim elektrokalorischen Effekt, wenn man ein Feld adiabatisch anlegt?",
            "Die Dipole richten sich aus, ihre Entropie sinkt, das Material erwärmt sich.", "Das Material kühlt sich ab.",
            "Nichts, bis man das Feld wieder abschaltet.", "Es fließt ein Strom, der Wärme erzeugt.",
            why = "Abkühlung kommt beim Abschalten: Die Dipole verlieren ihre Ordnung und nehmen Entropie aus dem Gitter. Ein Kühlzyklus koppelt beides mit Wärmeübertragung."),
        c(C, 2, "ca_elasto", "Warum erwärmt sich ein Gummiband beim schnellen Dehnen?",
            "Die Polymerketten werden geordnet, ihre Konfigurationsentropie sinkt, die Energie geht in Gitterschwingungen.",
            "Durch Reibung zwischen den Molekülen.", "Weil die Bindungen gespannt werden und Energie speichern.", "Weil es Feuchtigkeit verliert.",
            why = "Entropieelastizität: Die Rückstellkraft ist überwiegend entropisch. Auch Formgedächtnislegierungen (NiTi) zeigen über die martensitische Umwandlung große elastokalorische Effekte."),
        c(C, 2, "ca_magneto_baro", "Wie funktioniert die adiabatische Entmagnetisierung zum Erreichen tiefer Temperaturen?",
            "Spins werden isotherm im Feld ausgerichtet, dann wird das Feld adiabatisch abgeschaltet; die Spins nehmen Entropie aus dem Gitter.",
            "Man erwärmt einen Magneten und kühlt ihn schnell.", "Ein starkes Feld bremst die Atome direkt ab.", "Durch Verdampfen von Helium im Magnetfeld.",
            why = "Mit paramagnetischen Salzen erreicht man Millikelvin, mit Kernspins Mikrokelvin. Der Kreisprozess ist das magnetische Gegenstück zur Gasexpansion."),
        c(C, 3, "ca_multi", "Was ist der Vorteil multikalorischer Materialien?",
            "Mehrere Felder (z. B. Magnetfeld und Druck) koppeln an dieselbe Umwandlung; man kann Hysterese umgehen und den Effekt vergrößern.",
            "Sie brauchen gar kein äußeres Feld.", "Sie sind billiger als Gase.", "Sie arbeiten ohne Wärmeübertragung.",
            why = "Mit zwei Feldern lässt sich der Zyklus so führen, dass die Umwandlung jeweils mit dem günstigeren Feld getrieben wird (Kreuzkopplung) — weniger Energieverlust pro Zyklus."),
        c(C, 2, "ca_calorimetry", "Warum unterscheiden sich direkt gemessene und über Maxwell-Relationen indirekt bestimmte ΔT oft?",
            "Die indirekte Methode setzt Gleichgewicht voraus und versagt bei Hysterese und Übergängen 1. Ordnung.", "Weil Thermometer ungenau sind.",
            "Weil Maxwell-Relationen nur für Gase gelten.", "Weil direkte Messungen immer zu groß sind.",
            why = "Maxwell-Relationen folgen aus der Existenz eines Gleichgewichtspotentials. Bei Hysterese hängt der Zustand von der Vorgeschichte ab; dann braucht man direkte oder quasi-direkte Messungen."),

        // ---------------- Quantenfeldtheorie ----------------
        c(F, 2, "qft_relativity", "Warum braucht man für relativistische Quantenmechanik Felder statt einer Ein-Teilchen-Wellenfunktion?",
            "Bei Energien ≳ mc² entstehen und vernichten sich Teilchen; die Teilchenzahl ist nicht erhalten.", "Weil die Schrödinger-Gleichung zu kompliziert ist.",
            "Weil Teilchen relativistisch keine Masse haben.", "Weil die Unschärferelation dort nicht gilt.",
            why = "Lokalisierung unter die Compton-Wellenlänge ħ/mc kostet genug Energie für Paarerzeugung. Felder mit Erzeugern und Vernichtern beschreiben variable Teilchenzahlen natürlich."),
        c(F, 2, "qft_classical", "Was liefert das Noether-Theorem für eine Feldtheorie mit globaler U(1)-Symmetrie?",
            "Einen erhaltenen Strom ∂_μ j^μ = 0 und damit eine erhaltene Ladung.", "Die Masse des Feldes.", "Die Kopplungskonstante.", "Eine Eichboson-Masse.",
            why = "Phasensymmetrie φ → e^{iα}φ ↔ Ladungserhaltung. Macht man die Symmetrie lokal, braucht man ein Eichfeld — so entsteht die QED."),
        c(F, 3, "qft_scalar", "Was ist der physikalische Inhalt der kanonischen Quantisierung eines freien Feldes?",
            "Jede Fourier-Mode ist ein harmonischer Oszillator; seine Anregungsquanten sind die Teilchen.", "Das Feld wird an jedem Punkt gemessen.",
            "Die Lichtgeschwindigkeit wird quantisiert.", "Teilchen sind kleine Kugeln im Feld.",
            why = "Erzeuger a†_p fügen ein Teilchen mit Impuls p hinzu. Die Nullpunktsenergien aller Moden sind die Vakuumenergie (in der Regel per Normalordnung abgezogen)."),
        c(F, 3, "qft_dirac", "Was sagte die Dirac-Gleichung vorher, das damals unbekannt war?",
            "Antiteilchen (das Positron).", "Das Neutrino.", "Die Masse des Protons.", "Die Feinstruktur ohne Spin.",
            why = "Die Lösungen negativer Energie werden als Antiteilchen interpretiert; 1932 fand Anderson das Positron. Außerdem folgen Spin ½ und g = 2 automatisch."),
        c(F, 2, "qft_feynman", "Was stellt eine innere Linie in einem Feynman-Diagramm dar?",
            "Einen Propagator — ein virtuelles Teilchen, das nicht auf der Massenschale liegen muss.", "Ein reales, messbares Teilchen.",
            "Die Bahn eines Teilchens im Raum.", "Eine Erhaltungsgröße.",
            why = "Diagramme sind Terme der Störungsreihe, keine Bahnen. Innere Linien tragen beliebige Viererimpulse (p² ≠ m²); an Vertizes gilt Impulserhaltung."),
        c(F, 3, "qft_renorm", "Was bedeutet es, dass die Kopplungskonstante „läuft“?",
            "Die effektive Stärke der Wechselwirkung hängt von der Energieskala ab, bei der man misst.", "Die Kopplung ändert sich mit der Zeit.",
            "Die Kopplung ist im Experiment nicht messbar.", "Die Theorie ist inkonsistent.",
            why = "Vakuumpolarisation: In der QED schirmt sie die Ladung ab (α wächst mit der Energie, 1/137 → 1/128 bei M_Z), in der QCD dominiert Anti-Abschirmung (asymptotische Freiheit)."),
        c(F, 3, "qft_sm", "Wie erhalten die W- und Z-Bosonen ihre Masse?",
            "Durch spontane Symmetriebrechung mit dem Higgs-Feld, dessen Vakuumerwartungswert nicht null ist.", "Sie sind von Natur aus schwer.",
            "Durch die starke Wechselwirkung.", "Durch Kopplung an das Photon.",
            why = "Ein expliziter Massenterm würde die Eichsymmetrie zerstören. Drei Goldstone-Moden werden zu den longitudinalen Freiheitsgraden von W± und Z; das Photon bleibt masselos."),

        // ---------------- Mechanik und Relativität ----------------
        c(K, 1, "me_newton", "Ein Astronaut auf der ISS schwebt. Warum?",
            "Er fällt zusammen mit der Station frei um die Erde; die Schwerkraft wirkt fast unvermindert.", "Im Orbit gibt es keine Schwerkraft.",
            "Die Zentrifugalkraft ist größer als die Schwerkraft.", "Der Luftdruck hebt ihn an.",
            why = "In 400 km Höhe ist g noch ≈ 90 % des Bodenwerts. Schwerelosigkeit bedeutet freien Fall: Station und Astronaut erfahren dieselbe Beschleunigung."),
        c(K, 2, "me_lagrange", "Was ist der praktische Vorteil des Lagrange-Formalismus gegenüber Newton?",
            "Zwangskräfte fallen heraus; man arbeitet direkt mit generalisierten Koordinaten und skalaren Energien.", "Er ist genauer als die Newtonschen Gesetze.",
            "Er gilt auch ohne Energieerhaltung nicht.", "Er braucht keine Anfangsbedingungen.",
            why = "Physikalisch gleichwertig, aber Zwangsbedingungen werden durch die Koordinatenwahl automatisch erfüllt; Symmetrien zeigen sich als zyklische Koordinaten."),
        c(K, 2, "me_hamilton", "Was beschreibt eine Bahn im Phasenraum?",
            "Den vollständigen Zustand (alle q und p) und seine Entwicklung; Bahnen kreuzen sich nie.", "Die räumliche Bahn eines Teilchens.",
            "Nur die Energie.", "Die Geschwindigkeit als Funktion der Zeit.",
            why = "Die Hamilton-Gleichungen sind erster Ordnung; durch jeden Phasenraumpunkt geht genau eine Lösung (Eindeutigkeit)."),
        c(K, 2, "me_rigid", "Warum kann eine Eiskunstläuferin ihre Pirouette beschleunigen, indem sie die Arme anzieht?",
            "Der Drehimpuls bleibt erhalten, das Trägheitsmoment sinkt, also steigt die Winkelgeschwindigkeit.", "Sie stößt sich vom Eis ab.",
            "Die Energie bleibt erhalten, also bleibt ω gleich.", "Weil die Luftreibung abnimmt.",
            why = "L = Iω konstant. Die Rotationsenergie L²/2I steigt dabei — die Arbeit leisten ihre Muskeln gegen die Zentrifugalkraft."),
        c(K, 2, "me_oscillation", "Warum ist Resonanz bei einer schwach gedämpften Schwingung gefährlich?",
            "Bei Anregung nahe der Eigenfrequenz wird die Amplitude etwa Q-mal größer als bei statischer Last.", "Weil sich dann die Eigenfrequenz ändert.",
            "Weil die Dämpfung bei Resonanz verschwindet.", "Weil die Schwingung dann chaotisch wird.",
            why = "A(ω₀) ≈ Q · f₀/ω₀². Brücken und Maschinen werden deshalb gedämpft oder ihre Eigenfrequenzen von Anregungsfrequenzen weggelegt."),
        c(K, 2, "me_sr", "Warum gibt es beim Zwillingsparadoxon keinen Widerspruch?",
            "Die Situation ist nicht symmetrisch: Nur der Reisende wechselt das Inertialsystem (Beschleunigung, Umkehr).",
            "Beide altern gleich schnell.", "Die Zeitdilatation ist nur scheinbar.", "Weil Licht beide Uhren gleich beeinflusst.",
            why = "Die Eigenzeit ist entlang der geraden (unbeschleunigten) Weltlinie maximal. Der Reisende hat zwischen denselben Ereignissen eine kürzere Weltlinie in der Minkowski-Metrik."),
        c(K, 2, "me_sr", "Warum kann ein Körper mit Masse die Lichtgeschwindigkeit nicht erreichen?",
            "Seine Energie γmc² würde unendlich; endliche Arbeit erhöht v nur asymptotisch gegen c.", "Weil der Luftwiderstand zu groß wird.",
            "Weil seine Masse dabei verschwindet.", "Weil es kein Bezugssystem mit v = c gibt, in dem Kraft wirkt.",
            why = "Für v → c divergiert γ = 1/√(1 − v²/c²). Teilchenbeschleuniger erhöhen die Energie, die Geschwindigkeit nähert sich c nur noch in den Nachkommastellen."),
        c(K, 3, "me_gr", "Warum gehen Uhren in einem stärkeren Gravitationsfeld langsamer?",
            "Die Metrik hängt vom Potential ab; die Eigenzeit dτ = √(1 + 2Φ/c²) dt ist bei tieferem Potential kleiner.",
            "Weil die Schwerkraft das Uhrwerk bremst.", "Weil Licht im Feld langsamer wird und die Uhr später abgelesen wird.", "Weil die Masse der Uhr zunimmt.",
            why = "Das gilt für jede Uhr, auch Atomuhren (Pound-Rebka, GPS). Es folgt schon aus dem Äquivalenzprinzip mit einem beschleunigten Fahrstuhl und dem Doppler-Effekt."),
        c(K, 2, "me_continuum", "Warum fliegt ein Flugzeug? Welche Aussage ist physikalisch korrekt?",
            "Die Tragfläche lenkt Luft nach unten; die Impulsänderung und der Druckunterschied (Bernoulli) sind zwei Beschreibungen desselben Auftriebs.",
            "Die Luft oben muss in derselben Zeit wie unten ankommen und ist deshalb schneller.", "Der Motor drückt das Flugzeug nach oben.",
            "Die Luft unter der Tragfläche ist dichter und trägt wie Wasser.",
            why = "Die „gleiche Laufzeit“-Erklärung ist falsch (oben ist die Luft sogar schneller). Auftrieb entsteht durch die Zirkulation um das Profil (Kutta-Joukowski)."),

        // ---------------- Mathematik ----------------
        c(M, 1, "ma_analysis", "Was bedeutet die Ableitung f'(x₀) geometrisch?",
            "Die Steigung der Tangente an den Graphen in x₀, also die lineare Näherung von f nahe x₀.", "Die Fläche unter dem Graphen bis x₀.",
            "Den Funktionswert in x₀.", "Die Krümmung des Graphen.",
            why = "f(x₀ + h) = f(x₀) + f'(x₀)h + o(h). Die Krümmung hängt mit der zweiten Ableitung zusammen."),
        c(M, 1, "ma_integral", "Was besagt der Hauptsatz der Differential- und Integralrechnung?",
            "Integrieren und Differenzieren sind zueinander inverse Operationen.", "Jede Funktion ist integrierbar.",
            "Das Integral ist immer positiv.", "Die Ableitung einer Konstanten ist eins.",
            why = "d/dx ∫ₐˣ f(t) dt = f(x) für stetiges f, und ∫ₐᵇ F'(x) dx = F(b) − F(a). Deshalb lassen sich Integrale über Stammfunktionen berechnen."),
        c(M, 2, "ma_series", "Warum konvergiert eine Potenzreihe innerhalb ihres Konvergenzradius und divergiert außerhalb?",
            "Sie verhält sich wie eine geometrische Reihe: Die Glieder fallen innen geometrisch ab und wachsen außen unbeschränkt.",
            "Weil Polynome immer konvergieren.", "Weil der Radius willkürlich festgelegt wird.", "Das gilt nur für reelle Zahlen.",
            why = "Wurzelkriterium mit limsup |aₙ|^{1/n} = 1/R. Auf dem Rand selbst ist alles möglich (Beispiel: Σxⁿ/n bei x = 1 und −1)."),
        c(M, 2, "ma_taylor", "Warum hat die Taylor-Reihe von 1/(1 + x²) um 0 nur den Konvergenzradius 1, obwohl die Funktion auf ganz ℝ glatt ist?",
            "Im Komplexen hat sie Pole bei ±i, also im Abstand 1 vom Entwicklungspunkt.", "Weil sie bei x = 1 nicht definiert ist.",
            "Weil Taylor-Reihen immer Radius 1 haben.", "Weil die Ableitungen bei 0 verschwinden.",
            why = "Der Konvergenzradius ist der Abstand zur nächsten Singularität in ℂ — ein schönes Beispiel, warum Funktionentheorie reelle Analysis erklärt."),
        c(M, 2, "ma_multidiff", "Was zeigt der Gradient einer Funktion f(x, y) an?",
            "Die Richtung des steilsten Anstiegs; er steht senkrecht auf den Höhenlinien.", "Die Richtung, in der f konstant bleibt.",
            "Den Funktionswert.", "Die zweite Ableitung.",
            why = "Richtungsableitung ∂_v f = ∇f · v ist für v ∥ ∇f maximal und für v ⊥ ∇f null (entlang der Höhenlinie)."),
        c(M, 2, "ma_implicit", "Was ist die geometrische Idee hinter Lagrange-Multiplikatoren?",
            "Im Extremum unter einer Nebenbedingung sind die Gradienten von Zielfunktion und Nebenbedingung parallel.",
            "Die Nebenbedingung wird einfach ignoriert.", "Die Zielfunktion muss linear sein.", "Der Gradient der Zielfunktion verschwindet immer.",
            why = "Längs der Nebenbedingungsfläche darf sich f in erster Ordnung nicht ändern: ∇f hat keine Komponente tangential zur Fläche, also ∇f = λ∇g."),
        c(M, 2, "ma_vector", "Was bedeutet div F > 0 in einem Punkt anschaulich?",
            "Der Punkt ist eine Quelle: Aus einem kleinen Volumen fließt netto mehr heraus als hinein.", "Das Feld wirbelt um den Punkt.",
            "Das Feld ist dort null.", "Das Feld ist konservativ.",
            why = "div F = lim (Fluss durch Oberfläche)/Volumen. Wirbel misst die Rotation; Gauß macht aus lokalen Quellen den Fluss durch beliebige Flächen."),
        c(M, 3, "ma_lebesgue", "Warum ist das Lebesgue-Integral für die Physik (z. B. L²-Räume der Quantenmechanik) wichtiger als das Riemann-Integral?",
            "Grenzwerte und Integrale lassen sich unter milden Bedingungen vertauschen, und L² wird vollständig (ein Hilbertraum).",
            "Es liefert für stetige Funktionen andere Werte.", "Es ist leichter auszurechnen.", "Weil Riemann-Integrale nur für Polynome existieren.",
            why = "Mit Riemann ist der Raum quadratintegrabler Funktionen nicht vollständig; Cauchy-Folgen von Wellenfunktionen hätten keinen Grenzwert. Für stetige Funktionen stimmen beide Integrale überein."),
        c(M, 2, "ma_linalg", "Was bedeutet det A = 0 für ein lineares Gleichungssystem Ax = b?",
            "A ist nicht invertierbar: Es gibt entweder keine oder unendlich viele Lösungen.", "Es gibt genau eine Lösung x = 0.",
            "Die Lösung ist x = b.", "A ist die Einheitsmatrix.",
            why = "det A = 0 ⇔ Kern nicht trivial ⇔ Spalten linear abhängig. Geometrisch drückt A Volumen auf null zusammen."),
        c(M, 2, "ma_linalg2", "Warum diagonalisiert man Matrizen in der Physik so gern?",
            "In der Eigenbasis entkoppeln die Gleichungen; jede Komponente entwickelt sich unabhängig (Normalmoden, stationäre Zustände).",
            "Damit die Determinante null wird.", "Weil Diagonalmatrizen immer symmetrisch sind.", "Weil sich dann die Eigenwerte ändern.",
            why = "ẋ = Ax wird zu ẏᵢ = λᵢyᵢ; Hauptachsen des Trägheitstensors, Normalmoden, Energieeigenzustände sind alle dieselbe Idee."),
        c(M, 2, "ma_ode", "Was garantiert, dass ein Anfangswertproblem eine eindeutige Lösung hat (Picard-Lindelöf)?",
            "Die rechte Seite ist stetig und lokal Lipschitz-stetig im Zustand.", "Die Lösung ist ein Polynom.",
            "Die DGL ist linear und von zweiter Ordnung.", "Es gibt keine Anfangsbedingungen.",
            why = "Gegenbeispiel ohne Lipschitz: y' = √|y|, y(0) = 0 hat y ≡ 0 und y = t²/4. Determinismus in der Mechanik beruht auf dieser Bedingung."),
        c(M, 3, "ma_complex", "Warum ist eine im Komplexen differenzierbare Funktion so viel „starrer“ als eine reell differenzierbare?",
            "Komplexe Differenzierbarkeit verlangt die Cauchy-Riemann-Gleichungen; daraus folgen Analytizität und der Identitätssatz.",
            "Weil komplexe Zahlen zweidimensional sind und dadurch weniger Funktionen existieren.", "Weil nur Polynome holomorph sind.", "Das stimmt nicht.",
            why = "Holomorphe Funktionen sind beliebig oft differenzierbar, durch Werte auf einer Kurve festgelegt und erfüllen den Cauchyschen Integralsatz — Grundlage des Residuenkalküls."),
        c(M, 2, "ma_fourier", "Warum sind Fourier-Reihen bei linearen PDGL wie der Wärmeleitung so nützlich?",
            "Sinus- und Kosinusfunktionen sind Eigenfunktionen der Ableitung; jede Mode entwickelt sich unabhängig.", "Weil jede Funktion periodisch ist.",
            "Weil man so Integrale vermeidet.", "Weil sie immer gleichmäßig konvergieren.",
            why = "∂ₓ² sin(kx) = −k² sin(kx): Die PDGL wird zu entkoppelten ODEs, hochfrequente Moden klingen wie e^{−Dk²t} schnell ab."),
        c(M, 3, "ma_functional", "Was unterscheidet unendlichdimensionale Hilberträume wesentlich von ℝⁿ?",
            "Beschränkte Folgen haben nicht immer konvergente Teilfolgen; die Einheitskugel ist nicht kompakt.", "Sie haben kein Skalarprodukt.",
            "Sie sind nicht vollständig.", "In ihnen gibt es keine Basis.",
            why = "Eine Orthonormalfolge eₙ hat Abstände √2, also keine konvergente Teilfolge. Deshalb braucht man schwache Konvergenz und Kompaktheitsargumente."),
        c(M, 2, "ma_prob", "Warum sind so viele Messgrößen näherungsweise normalverteilt?",
            "Zentraler Grenzwertsatz: Summen vieler unabhängiger kleiner Einflüsse nähern sich einer Normalverteilung.",
            "Weil die Natur Gauß-Kurven bevorzugt.", "Weil Messgeräte so kalibriert werden.", "Das gilt nur für ganzzahlige Größen.",
            why = "Voraussetzung: unabhängige Beiträge mit endlicher Varianz. Bei schweren Verteilungsrändern (Cauchy) versagt der Satz."),
        c(M, 2, "ma_numerics", "Warum wird ein numerisches Ableiten mit sehr kleiner Schrittweite h wieder ungenauer?",
            "Rundungsfehler wachsen wie ε/h, während der Abschneidefehler mit h fällt; es gibt ein optimales h.", "Weil Computer keine kleinen Zahlen speichern können.",
            "Weil die Ableitung dann null wird.", "Das passiert nicht.",
            why = "Für die zentrale Differenz ist der Gesamtfehler ≈ ε/h + h²f'''/6, minimal bei h ~ ε^{1/3} ≈ 10⁻⁵ in doppelter Genauigkeit."),
        c(M, 3, "ma_tensor", "Warum schreibt man physikalische Gesetze gern in Tensorform?",
            "Eine Tensorgleichung, die in einem Koordinatensystem gilt, gilt in allen — die Physik hängt nicht von der Koordinatenwahl ab.",
            "Weil Tensoren einfacher als Vektoren sind.", "Weil Tensoren immer symmetrisch sind.", "Damit man keine Indizes braucht.",
            why = "Beide Seiten transformieren gleich. Das ist der Kern des Kovarianzprinzips in SRT (Lorentz-Tensoren) und ART (allgemeine Koordinaten)."),
        c(M, 2, "ma_variation", "Was ist die Euler-Lagrange-Gleichung anschaulich?",
            "Die Bedingung, dass ein Funktional unter kleinen Variationen der Funktion stationär ist — analog zu f'(x) = 0.",
            "Eine Methode, Integrale numerisch zu berechnen.", "Eine spezielle Lösung der Wellengleichung.", "Die Definition der Ableitung.",
            why = "Aus δ∫L(y, y', x)dx = 0 für alle Variationen mit festen Rändern folgt d/dx ∂L/∂y' − ∂L/∂y = 0. Mechanik, Optik (Fermat) und Feldtheorie nutzen dasselbe Prinzip.")
    )
}
