package app.maximus.lab.domain

/**
 * Hand-written AI/ML questions for the learning path: understanding first, many scenario questions
 * ("which technique?") in the style of IBM's ML course, every one with an explanation.
 */
internal object QuizAi {
    private var n = 0
    private fun c(diff: Int, chapter: String, prompt: String, correct: String, vararg wrong: String, why: String) =
        Question("qai-${++n}", Topic.AI, diff, prompt, why, listOf(correct) + wrong, 0, chapterKey = chapter)

    val all: List<Question> = listOf(
        // ---------------- AI von Null ----------------
        c(1, "ai0_what", "Wie hängen KI, maschinelles Lernen und Deep Learning zusammen?",
            "Deep Learning ist ein Teil des maschinellen Lernens, das ein Teil der KI ist", "Es sind drei unabhängige Gebiete",
            "KI ist ein Teil des Deep Learnings", "Maschinelles Lernen ist der Oberbegriff für KI",
            why = "Die Begriffe sind ineinander geschachtelt: KI ⊃ ML ⊃ Deep Learning ⊃ generative KI."),
        c(1, "ai0_what", "Ein Schachprogramm durchsucht nach fest programmierten Regeln alle Züge. Ist das maschinelles Lernen?",
            "Nein – es ist KI, lernt aber nichts aus Daten", "Ja, jede KI ist maschinelles Lernen", "Ja, weil es gewinnt", "Nein, das ist gar keine KI",
            why = "Maschinelles Lernen heißt, dass Parameter aus Daten gelernt werden. Klassische Suche mit festen Bewertungsregeln ist KI ohne Lernen."),
        c(1, "ai0_what", "Was beschreibt den Unterschied zwischen klassischer Programmierung und ML am besten?",
            "Klassisch: Daten + Regeln → Antworten; ML: Daten + Antworten → Regeln", "ML braucht keine Daten",
            "Klassische Programme sind immer langsamer", "Bei ML schreibt der Mensch alle Regeln selbst",
            why = "Im ML liefert man Beispiele mit Antworten, und das Lernverfahren findet die Regel (das Modell) selbst."),
        c(1, "ai0_what", "Welche drei Zutaten lösten den Deep-Learning-Boom ab 2012 aus?",
            "Große Datensätze, GPUs und bessere Algorithmen", "Quantencomputer, Blockchain und 5G", "Nur ein neuer Algorithmus", "Schnellere Festplatten",
            why = "AlexNet 2012 nutzte ImageNet (Daten), Grafikkarten (Rechenleistung) und Tricks wie ReLU und Dropout (Algorithmen)."),
        c(1, "ai0_what", "Alle heutigen KI-Systeme, auch große Sprachmodelle, zählen zu …",
            "schwacher (enger) KI", "starker KI (AGI)", "Expertensystemen ohne Lernen", "symbolischer KI",
            why = "Sie sind in bestimmten Aufgaben stark, haben aber kein allgemeines Weltverständnis wie eine hypothetische AGI."),
        c(1, "ai0_data", "In einer Tabelle mit Häusern ist jede Zeile ein Haus. Wie nennt man eine Spalte wie ‚Wohnfläche‘?",
            "Merkmal (Feature)", "Label", "Epoche", "Hyperparameter",
            why = "Zeilen sind Beispiele, Spalten Merkmale; die Spalte, die vorhergesagt werden soll (Preis), ist das Label."),
        c(1, "ai0_data", "Was ist das Label beim Spamfilter?",
            "Die Markierung Spam oder kein Spam", "Die Länge der E-Mail", "Der Absender", "Die Lernrate",
            why = "Das Label ist die richtige Antwort, die das Modell aus den Merkmalen (Wörter, Absender, Länge) vorhersagen soll."),
        c(1, "ai0_data", "Warum kodiert man ‚Stadt ∈ {Berlin, Köln, Wien}‘ nicht einfach als 1, 2, 3?",
            "Die Zahlen täuschen eine Reihenfolge und Abstände vor, die es nicht gibt", "Weil Modelle keine Zahlen können",
            "Weil 3 zu groß ist", "Das wäre völlig in Ordnung",
            why = "Ein lineares Modell würde Wien als ‚dreimal Berlin‘ behandeln. One-Hot-Kodierung erzeugt stattdessen drei gleichberechtigte 0/1-Spalten."),
        c(1, "ai0_data", "Was bedeutet ‚Garbage in, garbage out‘?",
            "Mit schlechten Daten hilft auch der beste Algorithmus nicht", "Müllbilder kann man nicht klassifizieren",
            "Man soll Daten löschen", "Große Modelle filtern Fehler automatisch",
            why = "Fehlerhafte Labels, Verzerrungen und Lücken lernt das Modell mit. Datenqualität ist meist wichtiger als die Modellwahl."),
        c(2, "ai0_data", "Ein Hautkrebs-Modell wurde fast nur mit Fotos heller Haut trainiert. Welches Problem droht?",
            "Verzerrung (Bias): Es funktioniert bei dunkler Haut schlechter", "Underfitting auf heller Haut", "Kein Problem, Haut ist Haut",
            "Das Modell wird automatisch fair",
            why = "Die Trainingsdaten bilden die Einsatzpopulation nicht ab. Gegenmittel: repräsentative Daten, Güte getrennt nach Gruppen messen."),
        c(1, "ai0_model", "Was ist der Unterschied zwischen Parametern und Hyperparametern?",
            "Parameter lernt das Training, Hyperparameter legt der Mensch vorher fest", "Es gibt keinen", "Hyperparameter sind die gelernten Gewichte",
            "Parameter sind immer ganze Zahlen",
            why = "Gewichte und Bias werden gelernt; Lernrate, Baumtiefe, k bei KNN oder die Netzgröße stellt man ein und vergleicht auf Validierungsdaten."),
        c(1, "ai0_model", "Wozu dient die Verlustfunktion?",
            "Sie misst mit einer Zahl, wie falsch die Vorhersagen sind; das Training minimiert sie", "Sie speichert das Modell",
            "Sie zählt die Daten", "Sie legt die Lernrate fest",
            why = "Ohne Verlust wüsste der Optimierer nicht, ob eine Parametereinstellung besser oder schlechter ist."),
        c(1, "ai0_model", "Beim Gradientenabstieg wird die Lernrate viel zu groß gewählt. Was passiert typischerweise?",
            "Der Verlust springt hin und her oder wächst (Divergenz)", "Das Training wird nur langsamer", "Das Modell wird automatisch besser",
            "Nichts, die Lernrate ist egal",
            why = "Zu große Schritte überspringen das Tal und landen höher. Probier es im Spiel ‚Gradientenabstieg‘."),
        c(1, "ai0_model", "Was passiert bei der Inferenz?",
            "Das fertige Modell macht Vorhersagen für neue Daten", "Das Modell wird trainiert", "Die Daten werden gesäubert", "Die Lernrate wird gesucht",
            why = "Inferenz ist der Einsatz: fit ist vorbei, jetzt nur noch predict."),
        c(1, "ai0_model", "Welche Reihenfolge entspricht der scikit-learn-Grammatik?",
            "Modell erzeugen → fit → predict → bewerten", "predict → fit → erzeugen", "bewerten → fit → predict", "fit → erzeugen → predict",
            why = "Jeder Estimator hat fit (lernen) und predict (vorhersagen); danach misst man die Güte auf Testdaten."),
        c(1, "ai0_types", "Du willst aus Trainingsdaten die Zeit für einen 20-m-Yoke-Lauf vorhersagen. Welche Lernart und Aufgabe?",
            "Überwacht, Regression", "Überwacht, Klassifikation", "Unüberwacht, Clustering", "Bestärkend",
            why = "Die Zielgröße ist eine Zahl, und es gibt Beispiele mit bekannten Zeiten."),
        c(1, "ai0_types", "Ein Onlineshop will Kundengruppen entdecken, ohne sie vorher zu kennen. Welche Lernart?",
            "Unüberwachtes Lernen (Clustering)", "Überwachte Klassifikation", "Bestärkendes Lernen", "Regression",
            why = "Es gibt keine Labels; die Gruppen sollen aus der Ähnlichkeit der Kunden entstehen."),
        c(1, "ai0_types", "Wie bekommt ein Sprachmodell beim Vortraining seine Labels?",
            "Selbstüberwacht: das jeweils nächste Wort im Text ist das Label", "Menschen markieren jedes Wort",
            "Es gibt keine Labels und kein Ziel", "Durch Belohnungen aus Spielen",
            why = "Das richtige nächste Token steht im Text selbst. So kann auf riesigen Textmengen ohne Handarbeit trainiert werden."),
        c(1, "ai0_types", "Ein Roboter lernt Laufen, indem er für jeden Meter vorwärts Punkte bekommt. Welche Lernart?",
            "Bestärkendes Lernen", "Überwachtes Lernen", "Clustering", "Dimensionsreduktion",
            why = "Es gibt keine richtigen Aktionen als Labels, nur Belohnungen für das Ergebnis eines Verhaltens."),
        c(1, "ai0_math", "Welche Rechenoperation steckt in jedem Neuron, jeder linearen Regression und jeder Attention?",
            "Das Skalarprodukt", "Die Division durch null", "Das Kreuzprodukt", "Die Fakultät",
            why = "w·x = Σwᵢxᵢ. Matrixmultiplikationen sind viele Skalarprodukte – deshalb sind GPUs so wichtig."),
        c(1, "ai0_math", "In welche Richtung zeigt der Gradient des Verlusts?",
            "In Richtung des steilsten Anstiegs – deshalb geht man entgegengesetzt", "Immer zum Minimum", "Senkrecht zum Anstieg", "Er hat keine Richtung",
            why = "Gradientenabstieg macht θ ← θ − η∇L, also einen Schritt bergab."),
        c(2, "ai0_math", "Warum ist die Kettenregel für Deep Learning so zentral?",
            "Backpropagation berechnet Gradienten verketteter Schichten mit der Kettenregel", "Sie macht Netze kleiner",
            "Sie ersetzt die Aktivierungsfunktionen", "Sie wird nur bei Entscheidungsbäumen gebraucht",
            why = "Ein Netz ist eine Verkettung von Funktionen. Die Ableitung nach frühen Gewichten ist ein Produkt lokaler Ableitungen."),
        c(1, "ai0_math", "Was misst die Standardabweichung?",
            "Wie stark die Werte um den Mittelwert streuen", "Den größten Wert", "Den häufigsten Wert", "Die Anzahl der Werte",
            why = "σ = √Varianz. Standardisierte Merkmale haben σ = 1."),
        c(1, "ai0_workflow", "Was sollte man vor jedem komplizierten Modell messen?",
            "Eine einfache Basislinie, z. B. immer den Mittelwert oder die häufigste Klasse vorhersagen", "Gar nichts", "Die Testgenauigkeit des komplizierten Modells",
            "Die Anzahl der GPU-Kerne",
            why = "Nur wenn das Modell die Basislinie deutlich schlägt, hat es etwas gelernt."),
        c(1, "ai0_workflow", "Wo steckt in echten ML-Projekten meist der größte Teil der Arbeit?",
            "Daten sammeln, säubern und verstehen", "Die Wahl der Programmiersprache", "Das Drücken auf ‚fit‘", "Das Schreiben des Abschlussberichts",
            why = "Oft 60–80 % der Zeit. Gute Daten und Merkmale bringen meist mehr als ein raffinierteres Modell."),
        c(1, "ai0_workflow", "Wofür steht EDA?",
            "Explorative Datenanalyse: Verteilungen, Zusammenhänge und Auffälligkeiten ansehen", "Ein Optimierer", "Elektronische Datenarchivierung",
            "Ein neuronales Netz",
            why = "describe, Histogramme, Korrelationen und Streudiagramme – erst ansehen, dann modellieren."),
        c(2, "ai0_workflow", "Warum ist der ML-Prozess ein Kreis und keine gerade Linie?",
            "Bewertung und Betrieb zeigen Probleme, die zu neuer Datenaufbereitung oder neuen Merkmalen führen", "Weil Kreise schöner sind",
            "Weil man immer genau einmal trainiert", "Weil Daten nie veralten",
            why = "CRISP-DM und die IBM-Methodik sehen ausdrücklich Rücksprünge und Feedback aus dem Betrieb vor."),
        c(1, "ai0_tools", "Welche Bibliothek ist der Standard für klassisches ML (Regression, Klassifikation, Clustering) in Python?",
            "scikit-learn", "Matplotlib", "Flask", "Docker",
            why = "scikit-learn bietet einheitliche fit/predict-Schnittstellen, Vorverarbeitung, Metriken und Pipelines."),
        c(1, "ai0_tools", "Wofür nutzt man pandas?",
            "Tabellen laden, säubern, filtern und gruppieren", "Neuronale Netze auf der GPU trainieren", "Webseiten bauen", "Container starten",
            why = "Der DataFrame ist die Tabelle der Datenwissenschaft."),
        c(2, "ai0_tools", "Was ist ein Hauptunterschied zwischen Keras und PyTorch?",
            "In Keras trainiert man bequem mit fit, in PyTorch schreibt man die Trainingsschleife meist selbst", "Keras kann keine Netze",
            "PyTorch kann keine Gradienten", "Es gibt keinen Unterschied",
            why = "Die Konzepte (Schichten, Verlust, Optimierer, Backprop) sind identisch; PyTorch ist durchsichtiger, Keras kompakter."),

        // ---------------- Die sieben Techniken (Szenarien) ----------------
        c(1, "ml_techniques", "Ein Autohersteller will den CO₂-Ausstoß eines neuen Modells aus Motorgröße und Zylinderzahl schätzen.",
            "Regression", "Klassifikation", "Clustering", "Assoziation",
            why = "Die Zielgröße (g/km) ist eine kontinuierliche Zahl."),
        c(1, "ml_techniques", "Eine Bank will vorhersagen, ob ein Kreditnehmer seinen Kredit zurückzahlt oder ausfällt.",
            "Klassifikation", "Regression", "Clustering", "Sequenz-Mining",
            why = "Zwei Kategorien (zahlt / fällt aus) und historische Beispiele mit bekanntem Ausgang – binäre Klassifikation."),
        c(1, "ml_techniques", "Ein Supermarkt will wissen, welche Artikel häufig zusammen gekauft werden.",
            "Assoziation", "Regression", "Anomalieerkennung", "Dimensionsreduktion",
            why = "Klassische Warenkorbanalyse mit Support, Konfidenz und Lift."),
        c(1, "ml_techniques", "Ein Kartenanbieter will betrügerische Zahlungen in Echtzeit erkennen, obwohl Betrug sehr selten ist.",
            "Anomalieerkennung", "Clustering", "Assoziation", "Empfehlungssystem",
            why = "Seltene, ungewöhnliche Ereignisse; oft lernt man das ‚Normale‘ und meldet starke Abweichungen."),
        c(1, "ml_techniques", "Ein Streamingdienst will jedem Nutzer passende Serien vorschlagen.",
            "Empfehlungssystem", "Regression", "Anomalieerkennung", "Clustering ohne Nutzerdaten",
            why = "Nutzer, Objekte und Vorlieben – inhaltsbasiert oder kollaboratives Filtern."),
        c(1, "ml_techniques", "Ein Onlineshop will aus Klickpfaden vorhersagen, welche Seite ein Besucher als Nächstes öffnet.",
            "Sequenz-Mining", "Assoziation ohne Reihenfolge", "Clustering", "Dimensionsreduktion",
            why = "Die Reihenfolge der Klicks ist die Information – sequentielle Muster oder Markov-Modelle."),
        c(1, "ml_techniques", "Ein Mobilfunkanbieter will seine Kunden in Gruppen mit ähnlichem Verhalten einteilen, ohne Gruppen vorzugeben.",
            "Clustering", "Klassifikation", "Regression", "Assoziation",
            why = "Keine Labels, Gruppen sollen entstehen – Kundensegmentierung."),
        c(1, "ml_techniques", "Ein Arzt will anhand von Messwerten entscheiden, ob ein Tumor gutartig oder bösartig ist.",
            "Klassifikation", "Regression", "Clustering", "Assoziation",
            why = "Zwei Klassen, historische Fälle mit bekannter Diagnose."),
        c(1, "ml_techniques", "Ein Labor misst 2000 Gene pro Probe und will die Daten in 2D anschauen.",
            "Dimensionsreduktion", "Regression", "Assoziation", "Empfehlungssystem",
            why = "PCA, t-SNE oder UMAP fassen viele Merkmale auf wenige zusammen."),
        c(1, "ml_techniques", "Ein Stromversorger will den Verbrauch für morgen stündlich vorhersagen.",
            "Regression auf einer Zeitreihe", "Assoziation", "Clustering", "Klassifikation in Spam/kein Spam",
            why = "Zahlenwerte in zeitlicher Folge – Zeitreihenprognose (Sequenz plus Regression)."),
        c(1, "ml_techniques", "Ein Sensor in einer Fabrik soll melden, wenn eine Maschine sich ungewöhnlich verhält.",
            "Anomalieerkennung", "Empfehlungssystem", "Assoziation", "Regression",
            why = "Normales Verhalten lernen und Abweichungen melden – etwa per Autoencoder oder Isolation Forest."),
        c(1, "ml_techniques", "Welche Technik ist typischerweise überwacht?",
            "Klassifikation", "Clustering", "Assoziation", "Dimensionsreduktion mit PCA",
            why = "Klassifikation braucht Beispiele mit bekannten Klassen; die anderen kommen ohne Labels aus."),
        c(2, "ml_techniques", "Eine E-Mail soll gleichzeitig mehrere Schlagwörter (Rechnung, dringend, Kunde X) bekommen. Welche Variante?",
            "Mehrfach-Label-Klassifikation (multilabel)", "Binäre Klassifikation", "Regression", "Clustering",
            why = "Mehrere Klassen können gleichzeitig zutreffen – im Gegensatz zur Mehrklassen-Klassifikation mit genau einer."),
        c(2, "ml_techniques", "Wie wird bei einem Hauspreis-Modell ‚Haus kostet über 500 000 €: ja/nein‘ aus einem Regressionsproblem?",
            "Durch Schwellenbildung wird daraus eine Klassifikation", "Gar nicht, das ist unmöglich", "Durch Clustering", "Durch Assoziation",
            why = "Ob Regression oder Klassifikation, entscheidet die Form der Zielgröße – man kann sie umdefinieren."),

        // ---------------- Regression ----------------
        c(1, "ml_regression", "Was minimiert die Methode der kleinsten Quadrate?",
            "Die Summe der quadrierten senkrechten Abstände zwischen Punkten und Gerade", "Die Anzahl der Punkte",
            "Den größten Fehler", "Die Steigung",
            why = "OLS: Σ(yᵢ − ŷᵢ)² minimal; das ergibt die geschlossene Lösung θ = (XᵀX)⁻¹Xᵀy."),
        c(1, "ml_regression", "Was bedeutet R² = 0?",
            "Das Modell ist nicht besser, als immer den Mittelwert vorherzusagen", "Das Modell ist perfekt", "Es gibt keine Daten", "Der Fehler ist null",
            why = "R² = 1 − SS_res/SS_tot. Bei R² = 0 ist der Restfehler so groß wie die Gesamtstreuung."),
        c(2, "ml_regression", "Kann R² auf Testdaten negativ werden?",
            "Ja, wenn das Modell schlechter ist als der Mittelwert", "Nein, nie", "Nur bei Klassifikation", "Nur mit Regularisierung",
            why = "Auf neuen Daten kann ein schlecht generalisierendes Modell größere Fehler machen als die konstante Vorhersage ȳ."),
        c(1, "ml_regression", "Welche Fehlermetrik ist in der Einheit der Zielgröße und bestraft große Fehler stärker?",
            "RMSE", "R²", "Accuracy", "Lift",
            why = "RMSE = √MSE; durch das Quadrieren zählen große Fehler überproportional."),
        c(2, "ml_regression", "Ein Datensatz hat einige extreme Ausreißer. Welche Fehlermetrik ist robuster?",
            "MAE", "MSE", "RMSE", "R²",
            why = "MAE wächst linear mit dem Fehler, MSE quadratisch – Ausreißer dominieren MSE und RMSE."),
        c(1, "ml_regression", "Wann nimmt man polynomiale Regression?",
            "Wenn der Zusammenhang gekrümmt ist; man ergänzt Potenzen der Merkmale", "Nur bei Klassifikation",
            "Wenn es keine Daten gibt", "Immer mit Grad 20",
            why = "Mit x², x³ als neue Merkmale bleibt das Modell linear in den Parametern. Zu hoher Grad überanpasst."),
        c(2, "ml_regression", "Was heißt ein Koeffizient θ₁ = 30 bei ‚Preis in € pro m² Wohnfläche‘ in einer multiplen Regression?",
            "Bei gleichen übrigen Merkmalen steigt der vorhergesagte Preis um 30 € pro zusätzlichem m²", "Jedes Haus kostet 30 €",
            "Die Wohnfläche verursacht garantiert den Preis", "R² ist 30",
            why = "Koeffizienten sind partielle Effekte. Kausalität folgt daraus nicht."),
        c(2, "ml_regression", "Zwei Merkmale sind fast perfekt korreliert (Wohnfläche in m² und in ft²). Welches Problem entsteht?",
            "Multikollinearität: Koeffizienten werden instabil und schwer deutbar", "Das Modell wird automatisch besser",
            "Underfitting", "Der Datensatz wird kleiner",
            why = "XᵀX wird fast singulär. Regularisierung (Ridge) oder Weglassen eines Merkmals helfen."),
        c(2, "ml_regression", "Ein Modell wurde mit Häusern von 50–200 m² trainiert. Wie verlässlich ist die Vorhersage für 900 m²?",
            "Unzuverlässig – Extrapolation außerhalb des Trainingsbereichs", "Sehr genau", "Genauso gut wie innerhalb", "Genauer als innerhalb",
            why = "Das Modell hat dort nie Daten gesehen; der lineare Zusammenhang kann dort längst nicht mehr gelten."),

        // ---------------- Klassifikation ----------------
        c(1, "ml_classification", "Was ist eine Entscheidungsgrenze?",
            "Die Fläche im Merkmalsraum, an der die Vorhersage die Klasse wechselt", "Die maximale Datenmenge", "Die Lernrate", "Der Testdatensatz",
            why = "Lineare Klassifikatoren haben gerade Grenzen (Ebenen), KNN, Bäume und Kernel-SVMs gekrümmte."),
        c(2, "ml_classification", "Wie viele binäre Modelle braucht One-vs-One bei 5 Klassen?",
            "10", "5", "25", "4",
            why = "Ein Modell je Klassenpaar: K(K−1)/2 = 5·4/2 = 10."),
        c(2, "ml_classification", "Wie viele binäre Modelle braucht One-vs-Rest bei 5 Klassen?",
            "5", "10", "1", "25",
            why = "Ein Modell pro Klasse gegen alle anderen."),
        c(2, "ml_classification", "Bei einer Krebs-Vorsorge sollen möglichst wenige Erkrankungen übersehen werden. Wie verschiebt man die Schwelle?",
            "Nach unten – mehr Fälle werden positiv, der Recall steigt", "Nach oben", "Gar nicht", "Auf genau 0,5",
            why = "Eine niedrigere Schwelle findet mehr Kranke (höherer Recall), erzeugt aber mehr Fehlalarme (niedrigere Precision)."),
        c(2, "ml_classification", "Was bewertet der Log-Loss im Gegensatz zur Accuracy?",
            "Auch, wie sicher und gut kalibriert die vorhergesagten Wahrscheinlichkeiten sind", "Nur die Anzahl richtiger Klassen",
            "Die Rechenzeit", "Die Größe des Modells",
            why = "Eine richtige Vorhersage mit p = 0,51 ist schlechter als mit 0,99; ein sicherer Fehler (p → 0) ist extrem teuer."),
        c(1, "ml_classification", "Welcher Klassifikator ist ein ‚fauler Lerner‘, der beim Training nur speichert?",
            "k-nächste Nachbarn", "Logistische Regression", "Entscheidungsbaum", "Neuronales Netz",
            why = "KNN rechnet erst bei der Vorhersage – die Abstände zu allen gespeicherten Beispielen."),
        c(2, "ml_classification", "Was ist der Jaccard-Index für vorhergesagte Menge {A, B, C} und wahre Menge {B, C, D}?",
            "0,5", "0,75", "1", "0,25",
            why = "Schnitt {B, C} hat 2 Elemente, Vereinigung {A, B, C, D} hat 4: J = 2/4."),

        // ---------------- Clustering ----------------
        c(1, "ml_clustering", "Was braucht k-Means als Eingabe, das DBSCAN nicht braucht?",
            "Die Anzahl der Cluster k", "Labels", "Eine Lernrate", "Einen Testdatensatz",
            why = "DBSCAN bestimmt die Clusterzahl aus der Dichte (Parameter ε und minPts)."),
        c(2, "ml_clustering", "Die Daten bilden zwei ineinanderliegende Ringe. Welches Verfahren trennt sie?",
            "DBSCAN (dichtebasiert)", "k-Means", "Lineare Regression", "PCA",
            why = "k-Means nimmt kugelförmige Cluster um Zentren an; DBSCAN folgt dichten Regionen beliebiger Form."),
        c(1, "ml_clustering", "Warum muss man vor k-Means meist standardisieren?",
            "Sonst dominiert das Merkmal mit den größten Zahlen die Distanz", "Weil k-Means nur negative Zahlen kann",
            "Damit es Labels gibt", "Gar nicht nötig",
            why = "Einkommen in € (Zehntausende) würde Alter in Jahren (Zehner) völlig überdecken."),
        c(2, "ml_clustering", "Was zeigt die Ellbogenmethode?",
            "Ab welchem k weitere Cluster die Inertia kaum noch senken", "Welches Merkmal am wichtigsten ist", "Die beste Lernrate", "Die Zahl der Ausreißer",
            why = "Die Inertia sinkt mit k immer; der Knick markiert ein sinnvolles Gleichgewicht."),
        c(2, "ml_clustering", "Ein Silhouettenkoeffizient nahe −1 bedeutet …",
            "der Punkt liegt wahrscheinlich im falschen Cluster", "perfekte Trennung", "der Punkt ist ein Zentrum", "k ist richtig gewählt",
            why = "s = (b − a)/max(a, b): negativ heißt, das Nachbarcluster ist im Mittel näher als das eigene."),

        // ---------------- Assoziation ----------------
        c(2, "ml_association", "1000 Körbe, 200 mit Chips, 100 mit Chips und Bier. Konfidenz der Regel Chips ⇒ Bier?",
            "50 %", "10 %", "20 %", "100 %",
            why = "conf = supp(Chips ∪ Bier)/supp(Chips) = 100/200."),
        c(2, "ml_association", "Eine Regel hat Konfidenz 90 %, aber Lift 1,0. Was folgt?",
            "B wird ohnehin in 90 % aller Körbe gekauft – die Regel sagt nichts Neues", "Starker Zusammenhang", "Negativer Zusammenhang",
            "Die Regel ist falsch berechnet",
            why = "Lift = Konfidenz/Support(B) = 1 bedeutet statistische Unabhängigkeit."),
        c(2, "ml_association", "Was besagt das Apriori-Prinzip?",
            "Jede Teilmenge einer häufigen Artikelmenge ist ebenfalls häufig", "Häufige Mengen haben seltene Teilmengen",
            "Man muss alle 2ⁿ Kombinationen prüfen", "Nur Paare sind wichtig",
            why = "Deshalb kann man Kandidaten mit einer seltenen Teilmenge sofort verwerfen und spart enorm Rechenzeit."),
        c(1, "ml_association", "Was misst der Support einer Artikelmenge?",
            "Wie häufig die Menge in allen Transaktionen vorkommt", "Wie teuer die Artikel sind", "Wie viele Kunden es gibt", "Die Konfidenz",
            why = "supp = Anzahl Körbe mit der Menge / alle Körbe."),

        // ---------------- Anomalie ----------------
        c(1, "ml_anomaly", "Ein Wert liegt 4 Standardabweichungen über dem Mittelwert. Was sagt der z-Score?",
            "z = 4, bei Normalverteilung extrem selten – ein Ausreißerkandidat", "z = 0,4", "Der Wert ist typisch", "z = −4",
            why = "|z| > 3 tritt bei Normalverteilung nur in etwa 0,27 % der Fälle auf."),
        c(2, "ml_anomaly", "Wie erkennt ein Isolation Forest Anomalien?",
            "Anomalien lassen sich mit wenigen zufälligen Schnitten isolieren – kurze Pfadlänge", "Er zählt Duplikate",
            "Er misst die Länge der Texte", "Er braucht Labels für jede Anomalie",
            why = "In dichten Regionen braucht man viele Schnitte, ein abgelegener Punkt ist schnell allein."),
        c(2, "ml_anomaly", "Ein Autoencoder wurde nur auf normalen Maschinendaten trainiert. Woran erkennt er einen Defekt?",
            "Am großen Rekonstruktionsfehler", "Am kleinen Rekonstruktionsfehler", "An der Lernrate", "Gar nicht",
            why = "Er hat nur Normales komprimieren gelernt; Ungewöhnliches rekonstruiert er schlecht."),
        c(2, "ml_anomaly", "Warum ist Accuracy bei Betrugserkennung mit 0,1 % Betrug fast wertlos?",
            "‚Nie Betrug‘ wäre schon zu 99,9 % richtig", "Weil Accuracy immer 50 % ist", "Weil Betrug keine Klasse ist", "Weil man keine Daten hat",
            why = "Man schaut auf Recall, Precision und die Precision-Recall-Kurve."),
        c(2, "ml_anomaly", "30 °C im Juli sind normal, 30 °C im Januar in Berlin nicht. Welche Art Anomalie?",
            "Kontextanomalie", "Punktanomalie", "Kollektivanomalie", "Gar keine",
            why = "Der Wert ist nur in seinem Zusammenhang (Jahreszeit) ungewöhnlich."),

        // ---------------- Sequenzen ----------------
        c(1, "ml_sequence", "Was ist die Markov-Eigenschaft?",
            "Der nächste Zustand hängt nur vom aktuellen ab, nicht von der ganzen Vorgeschichte", "Alle Zustände sind gleich wahrscheinlich",
            "Die Folge ist immer periodisch", "Es gibt keine Zustände",
            why = "P(x_{t+1} | x_t, …, x_1) = P(x_{t+1} | x_t). Ein Bigramm-Sprachmodell ist eine Markov-Kette."),
        c(2, "ml_sequence", "Warum darf man Zeitreihen nicht zufällig in Training und Test teilen?",
            "Das Modell würde aus der Zukunft lernen – ein Datenleck", "Weil Zeitreihen zu kurz sind", "Weil Testdaten nie nötig sind",
            "Das ist erlaubt und üblich",
            why = "Richtig: auf der Vergangenheit trainieren, auf dem späteren Zeitraum testen (TimeSeriesSplit)."),
        c(1, "ml_sequence", "Was ist Saisonalität in einer Zeitreihe?",
            "Ein regelmäßig wiederkehrendes Muster, etwa jeden Montag oder jeden Winter", "Ein einmaliger Ausreißer", "Der Mittelwert", "Ein Messfehler",
            why = "Zeitreihen zerlegt man gedanklich in Trend, Saisonalität und Rest."),

        // ---------------- Empfehlungen ----------------
        c(1, "ml_recommender", "„Nutzer, die ähnlich bewerten wie du, mochten auch …“ – welche Art Empfehlung?",
            "Kollaboratives Filtern", "Inhaltsbasiert", "Assoziationsregeln", "Regression",
            why = "Es nutzt nur die Bewertungsmatrix, keine Merkmale der Objekte."),
        c(2, "ml_recommender", "Ein ganz neuer Film hat noch keine Bewertungen. Welches Problem, welche Abhilfe?",
            "Kaltstart; inhaltsbasiert über Genre, Darsteller usw. empfehlen", "Overfitting; mehr Epochen", "Datenleck; Test löschen", "Kein Problem",
            why = "Kollaboratives Filtern braucht Bewertungen. Inhaltsmerkmale überbrücken die Anfangsphase."),
        c(2, "ml_recommender", "Was lernt Matrixfaktorisierung für jeden Nutzer und jedes Objekt?",
            "Einen Vektor versteckter Faktoren; die Bewertung ist ihr Skalarprodukt", "Eine Liste aller Bewertungen", "Einen Entscheidungsbaum",
            "Nur einen Mittelwert",
            why = "R ≈ PQᵀ – Vorläufer heutiger Embedding-Verfahren."),

        // ---------------- Dimensionsreduktion ----------------
        c(2, "ml_dimred", "Was sind die Hauptkomponenten der PCA mathematisch?",
            "Die Eigenvektoren der Kovarianzmatrix, sortiert nach ihren Eigenwerten", "Die größten Datenpunkte", "Die Spalten mit den meisten Nullen",
            "Zufällige Richtungen",
            why = "Wie die Hauptachsentransformation eines Trägheitstensors: Die Eigenwerte sind die Varianzen entlang der Achsen."),
        c(2, "ml_dimred", "Eigenwerte 6, 3, 1 der Kovarianzmatrix. Welchen Varianzanteil erklärt die erste Hauptkomponente?",
            "60 %", "30 %", "6 %", "100 %",
            why = "λ₁/Σλ = 6/10."),
        c(2, "ml_dimred", "Was sollte man aus einem t-SNE-Bild NICHT ablesen?",
            "Abstände zwischen weit entfernten Clustern und Clustergrößen", "Dass es Gruppen gibt", "Dass ähnliche Punkte nah liegen", "Dass es 2D ist",
            why = "t-SNE erhält lokale Nachbarschaften, verzerrt aber globale Abstände und Dichten."),
        c(2, "ml_dimred", "Was beschreibt den Fluch der Dimensionalität?",
            "In vielen Dimensionen werden Daten dünn und Distanzen ähnlich groß", "Mehr Merkmale verbessern immer das Modell",
            "Hohe Dimensionen sind schneller", "PCA funktioniert nur in 1D",
            why = "Das Volumen wächst exponentiell; KNN und Clustering verlieren an Aussagekraft."),

        // ---------------- Algorithmen im Detail ----------------
        c(2, "alg_knn", "Was passiert bei KNN mit k = 1?",
            "Die Grenze folgt jedem einzelnen Punkt – hohe Varianz, Overfitting", "Starkes Underfitting", "Das Modell sagt immer dieselbe Klasse",
            "Das Training dauert länger",
            why = "Großes k glättet (Bias steigt), kleines k folgt dem Rauschen (Varianz steigt)."),
        c(1, "alg_knn", "Warum wählt man bei zwei Klassen gern ein ungerades k?",
            "Damit es keinen Gleichstand bei der Abstimmung gibt", "Weil gerade Zahlen verboten sind", "Für schnellere GPUs", "Ohne Grund",
            why = "Bei k = 4 könnte es 2 : 2 stehen."),
        c(2, "alg_knn", "Warum ist KNN bei der Vorhersage langsam?",
            "Es muss den Abstand zu allen gespeicherten Beispielen berechnen", "Es trainiert bei jeder Vorhersage ein Netz", "Es nutzt keine Daten",
            "Es rechnet Integrale",
            why = "O(N·d) pro Anfrage; KD-Bäume oder approximative Nachbarsuche beschleunigen."),
        c(2, "alg_trees", "Ein Knoten enthält 50 % Klasse A und 50 % Klasse B. Seine Entropie (log₂) ist …",
            "1 Bit", "0", "0,5 Bit", "2 Bit",
            why = "H = −0,5·log₂0,5 − 0,5·log₂0,5 = 1 – maximale Unsicherheit bei zwei Klassen."),
        c(1, "alg_trees", "Nach welchem Kriterium wählt ein Entscheidungsbaum die nächste Frage?",
            "Die Frage, die den größten Informationsgewinn (oder die größte Gini-Abnahme) bringt", "Zufällig", "Die erste Spalte", "Die Spalte mit den meisten Nullen",
            why = "Gierig: an jedem Knoten die sauberste Trennung."),
        c(2, "alg_trees", "Ein unbeschränkter Entscheidungsbaum erreicht 100 % auf Training und 65 % auf Validierung. Gegenmittel?",
            "Tiefe begrenzen, Mindestblattgröße, Pruning oder Random Forest", "Mehr Tiefe", "Lernrate erhöhen", "Testdaten ins Training",
            why = "Klassisches Overfitting eines Baums, der jedes Rauschen auswendig lernt."),
        c(2, "alg_trees", "Gini-Unreinheit eines Knotens mit Klassenanteilen 0,8 und 0,2?",
            "0,32", "0,2", "0,64", "0,5",
            why = "G = 1 − (0,8² + 0,2²) = 1 − 0,68 = 0,32."),
        c(2, "alg_ensembles", "Was macht Random Forest zusätzlich zum normalen Bagging?",
            "An jedem Knoten nur eine zufällige Teilmenge der Merkmale zulassen", "Bäume nacheinander auf Residuen trainieren",
            "Nur einen einzigen Baum bauen", "Merkmale löschen",
            why = "Das macht die Bäume unterschiedlicher (geringere Korrelation ρ) und das Mittel genauer."),
        c(2, "alg_ensembles", "Welcher Ansatz baut Modelle nacheinander, die jeweils die Fehler der Vorgänger korrigieren?",
            "Boosting", "Bagging", "k-Means", "PCA",
            why = "AdaBoost gewichtet Fehler hoch, Gradient Boosting fittet die Residuen."),
        c(2, "alg_ensembles", "Wie groß ist etwa der Anteil der Daten, den ein Baum im Bootstrap nicht sieht (Out-of-Bag)?",
            "Rund 37 %", "0 %", "50 %", "90 %",
            why = "(1 − 1/N)^N → 1/e ≈ 0,368. Diese Beispiele dienen als eingebaute Validierung."),
        c(2, "alg_ensembles", "Bagging senkt vor allem …, Boosting vor allem …",
            "die Varianz … den Bias", "den Bias … die Varianz", "die Rechenzeit … den Speicher", "die Datenmenge … die Merkmale",
            why = "Mitteln vieler tiefer Bäume glättet Schwankungen; sequentielles Korrigieren flacher Bäume senkt systematische Fehler."),
        c(2, "alg_logreg", "Eine logistische Regression hat θⱼ = ln 2 ≈ 0,69. Was passiert, wenn xⱼ um 1 steigt?",
            "Die Odds verdoppeln sich", "Die Wahrscheinlichkeit verdoppelt sich genau", "Nichts", "Die Odds halbieren sich",
            why = "Linear in den Log-Odds: Odds-Verhältnis e^{θⱼ} = 2. Die Wahrscheinlichkeit selbst ändert sich nichtlinear."),
        c(1, "alg_logreg", "Welche Funktion bildet bei der logistischen Regression z = θᵀx auf eine Wahrscheinlichkeit ab?",
            "Die Sigmoidfunktion", "ReLU", "Die Exponentialfunktion allein", "Der Absolutbetrag",
            why = "σ(z) = 1/(1 + e^{−z}) liegt immer zwischen 0 und 1."),
        c(2, "alg_logreg", "Warum findet Gradientenabstieg bei der logistischen Regression das globale Minimum?",
            "Der Log-Loss ist in θ konvex", "Weil es nur einen Parameter gibt", "Weil Sigmoid linear ist", "Das stimmt nicht",
            why = "Konvexität garantiert: jedes lokale Minimum ist global (bei Regularisierung eindeutig)."),
        c(2, "alg_logreg", "In scikit-learn bedeutet ein kleines C bei LogisticRegression …",
            "stärkere Regularisierung, ein einfacheres Modell", "schwächere Regularisierung", "mehr Klassen", "eine größere Lernrate",
            why = "C ist die inverse Regularisierungsstärke."),
        c(2, "alg_svm", "Welche Trainingspunkte bestimmen die Lösung einer SVM?",
            "Nur die Stützvektoren am Rand der Margin", "Alle Punkte gleich", "Nur die Ausreißer", "Die Punkte im Zentrum jeder Klasse",
            why = "Punkte weit hinter der Margin könnte man entfernen, ohne dass sich die Grenze ändert."),
        c(2, "alg_svm", "Was ermöglicht der Kernel-Trick?",
            "Lineare Trennung in einem höherdimensionalen Raum, ohne ihn explizit zu berechnen", "Schnelleres Laden der Daten",
            "Clustering ohne k", "Das Weglassen von Labels",
            why = "Nur Skalarprodukte werden gebraucht; K(x, z) berechnet sie direkt im großen Raum."),
        c(3, "alg_svm", "Beim RBF-Kernel wird γ sehr groß gewählt. Was passiert?",
            "Jeder Punkt wirkt nur sehr lokal – zackige Grenze, Overfitting", "Die Grenze wird eine Gerade", "Das Modell ignoriert alle Daten",
            "Die Margin wird unendlich breit",
            why = "K = exp(−γ|x − z|²): großes γ = kleine Reichweite."),
        c(2, "alg_svm", "Was bewirkt ein großes C bei einer Soft-Margin-SVM?",
            "Fehler werden stark bestraft – schmale Margin, Gefahr von Overfitting", "Breite Margin, viele Fehler erlaubt", "Kein Einfluss",
            "Der Kernel wird abgeschaltet",
            why = "min ½|w|² + C Σξᵢ: großes C macht Verletzungen teuer."),
        c(2, "alg_bayes", "Warum heißt Naive Bayes ‚naiv‘?",
            "Es nimmt an, dass die Merkmale innerhalb einer Klasse unabhängig sind", "Weil es für Anfänger ist", "Weil es keine Wahrscheinlichkeiten nutzt",
            "Weil es nur zwei Klassen kann",
            why = "P(x | c) = Π P(xⱼ | c). Die Annahme ist meist falsch, die Klassifikation trotzdem oft gut."),
        c(2, "alg_bayes", "Wozu dient die Laplace-Glättung?",
            "Damit ein im Training ungesehenes Wort nicht die ganze Wahrscheinlichkeit auf null setzt", "Zum Skalieren von Bildern",
            "Zum Entfernen von Ausreißern", "Zum Beschleunigen der GPU",
            why = "Man addiert zu jeder Zählung 1: (n + 1)/(N + |V|)."),
        c(2, "alg_bayes", "Prior P(Spam) = 0,5, P(‚Gratis‘ | Spam) = 0,4, P(‚Gratis‘ | kein Spam) = 0,1. P(Spam | ‚Gratis‘)?",
            "0,8", "0,4", "0,5", "0,2",
            why = "0,5·0,4 = 0,2 gegen 0,5·0,1 = 0,05 ⇒ 0,2/0,25 = 0,8."),
        c(2, "alg_kmeans", "Garantiert k-Means das global beste Clustering?",
            "Nein, nur ein lokales Minimum – deshalb mehrere Starts", "Ja, immer", "Nur bei k = 1 nicht", "Nur mit Labels",
            why = "Das Ergebnis hängt von den Startzentren ab; k-means++ und n_init helfen."),
        c(2, "alg_kmeans", "Ein Cluster enthält die Punkte 2, 4 und 9 (1D). Wo liegt das neue Zentrum?",
            "Bei 5", "Bei 4", "Bei 9", "Bei 2",
            why = "Das Zentrum ist der Mittelwert: (2 + 4 + 9)/3 = 5."),
        c(2, "alg_kmeans", "Warum endet der Lloyd-Algorithmus immer?",
            "Jeder Schritt senkt die Inertia oder lässt sie gleich, und es gibt nur endlich viele Zuordnungen", "Er hat ein festes Zeitlimit",
            "Weil k klein ist", "Er endet nicht immer",
            why = "Monotone Abnahme auf einer endlichen Menge erzwingt Konvergenz (in endlich vielen Schritten)."),
        c(2, "alg_hier_dbscan", "Was ist ein Dendrogramm?",
            "Der Baum der Verschmelzungen beim hierarchischen Clustering", "Eine Konfusionsmatrix", "Ein Entscheidungsbaum für Regression", "Ein Lernkurven-Diagramm",
            why = "Schneidet man ihn auf einer bestimmten Höhe, erhält man eine Clusterzahl."),
        c(2, "alg_hier_dbscan", "Wie markiert DBSCAN Punkte in dünnen Regionen?",
            "Als Rauschen (Label −1)", "Als eigenes Cluster je Punkt", "Gar nicht, sie werden gelöscht", "Als Kernpunkte",
            why = "Punkte ohne genug Nachbarn im Radius ε, die auch kein Randpunkt sind, gelten als Rauschen."),
        c(2, "alg_hier_dbscan", "Welche Linkage ähnelt am meisten k-Means?",
            "Ward", "Single", "Complete", "Zufällig",
            why = "Ward verschmilzt die beiden Cluster, deren Vereinigung die Varianz am wenigsten erhöht."),

        // ---------------- Bewertung ----------------
        c(1, "ev_split", "Wozu dient die Validierungsmenge?",
            "Hyperparameter und Modelle auswählen", "Die Gewichte lernen", "Die Schlussnote vergeben", "Daten speichern",
            why = "Die Testmenge bleibt bis zum Ende unberührt."),
        c(2, "ev_split", "Ein Skalierer wird auf allen Daten gefittet, danach wird geteilt. Was ist das?",
            "Ein Datenleck – Informationen aus den Testdaten stecken in der Vorverarbeitung", "Gute Praxis", "Underfitting", "Kreuzvalidierung",
            why = "Mittelwerte und Streuungen der Testdaten fließen ein. Pipelines fitten Vorverarbeitung nur auf dem Training."),
        c(2, "ev_split", "Warum stratifiziert man die Kreuzvalidierung bei seltenen Klassen?",
            "Damit jeder Fold das gleiche Klassenverhältnis hat", "Damit es schneller geht", "Damit es mehr Daten gibt", "Damit Labels verschwinden",
            why = "Sonst kann ein Fold kaum oder gar keine Beispiele der seltenen Klasse enthalten."),
        c(2, "ev_split", "Fotos derselben Person landen in Training und Test. Welches Problem?",
            "Datenleck – das Modell erkennt die Person wieder statt zu generalisieren", "Underfitting", "Kein Problem", "Zu wenige Klassen",
            why = "Abhilfe: nach Personen gruppiert teilen (GroupKFold)."),
        c(2, "ev_split", "Ein Modell zur Vorhersage von Kündigungen nutzt das Merkmal ‚Kündigungsdatum‘. Ergebnis: 99,9 %. Was ist los?",
            "Ein Datenleck – das Merkmal verrät die Antwort", "Ein hervorragendes Modell", "Underfitting", "Zu viele Epochen",
            why = "Zum Vorhersagezeitpunkt kennt man das Kündigungsdatum noch nicht."),
        c(2, "ev_metrics", "Precision = 0,9, Recall = 0,1. Wie groß ist F1 ungefähr?",
            "0,18", "0,5", "0,9", "0,1",
            why = "F1 = 2·0,9·0,1/(0,9 + 0,1) = 0,18. Das harmonische Mittel wird von der kleineren Zahl dominiert."),
        c(2, "ev_metrics", "Was bedeutet eine ROC-AUC von 0,5?",
            "Das Modell trennt nicht besser als Raten", "Perfekte Trennung", "Die Hälfte der Daten fehlt", "Recall ist 0,5",
            why = "AUC = Wahrscheinlichkeit, dass ein zufälliges Positives einen höheren Score bekommt als ein zufälliges Negatives."),
        c(2, "ev_metrics", "Bei einem Spamfilter ist eine wichtige Mail im Spamordner schlimmer als Spam im Posteingang. Welche Metrik priorisieren?",
            "Precision der Klasse Spam", "Recall der Klasse Spam", "Accuracy", "MSE",
            why = "Hohe Precision: Was als Spam markiert wird, ist auch Spam – wenige Falsch-Positive."),
        c(2, "ev_metrics", "Welche Metrik ist die Spezifität?",
            "TN/(TN + FP): Anteil der Negativen, die korrekt als negativ erkannt werden", "TP/(TP + FN)", "TP/(TP + FP)", "(TP + TN)/N",
            why = "Recall misst die Positiven, Spezifität die Negativen; 1 − Spezifität ist die Falsch-Positiv-Rate."),
        c(3, "ev_metrics", "Bei 0,01 % Positiven: ROC- oder Precision-Recall-Kurve?",
            "Precision-Recall – sie ignoriert die riesige Zahl richtig Negativer", "ROC ist immer besser", "Beide sind gleich aussagekräftig", "Keine von beiden",
            why = "Die FPR bleibt bei vielen TN winzig, obwohl die Precision miserabel sein kann."),
        c(2, "ev_metrics", "Was ist beim Makro-Mittel einer Mehrklassen-Metrik besonders?",
            "Jede Klasse zählt gleich, auch seltene", "Große Klassen zählen mehr", "Es zählt nur die größte Klasse", "Es ist immer gleich der Accuracy",
            why = "Makro: Metrik je Klasse berechnen, dann ungewichtet mitteln."),
        c(1, "ev_features", "Welches Verfahren braucht KEINE Skalierung der Merkmale?",
            "Entscheidungsbaum", "KNN", "SVM", "k-Means",
            why = "Bäume teilen an Schwellen eines Merkmals; die Größenordnung spielt keine Rolle."),
        c(2, "ev_features", "Ein Merkmal hat starke Ausreißer. Welche Skalierung ist robust?",
            "Robust-Skalierung mit Median und IQR", "Min-Max", "Gar keine", "Multiplikation mit 1000",
            why = "Min-Max wird von einem einzigen Extremwert bestimmt; Median und IQR sind unempfindlich."),
        c(2, "ev_features", "Was ist der Vorteil einer Pipeline in scikit-learn?",
            "Vorverarbeitung und Modell werden gemeinsam und nur auf Trainingsdaten gefittet – kein Leck", "Sie macht Modelle größer",
            "Sie ersetzt das Testset", "Sie erzeugt Labels",
            why = "Auch in der Kreuzvalidierung wird so in jedem Fold korrekt neu gefittet."),
        c(1, "ev_features", "Welches neue Merkmal wäre für Hauspreise wohl nützlich?",
            "Preis pro m² im Stadtteil oder Alter des Hauses aus dem Baujahr", "Die Zeilennummer", "Die Farbe der Tabelle", "Eine Zufallszahl",
            why = "Fachwissen in Merkmale gießen ist oft wirksamer als ein komplexeres Modell."),
        c(2, "ev_tuning", "Trainingsfehler hoch, Validierungsfehler genauso hoch. Diagnose?",
            "Hoher Bias (Underfitting) – Modell zu einfach", "Hohe Varianz (Overfitting)", "Datenleck", "Perfektes Modell",
            why = "Mehr Daten helfen hier kaum; man braucht ein ausdrucksstärkeres Modell oder bessere Merkmale."),
        c(2, "ev_tuning", "Trainingsfehler sehr klein, Validierungsfehler groß, die Lücke schrumpft mit mehr Daten. Diagnose?",
            "Hohe Varianz – mehr Daten und Regularisierung helfen", "Hoher Bias", "Datenleck", "Falsche Metrik",
            why = "Die Lernkurven nähern sich mit wachsender Datenmenge."),
        c(2, "ev_tuning", "Warum ist Random Search oft effizienter als Grid Search?",
            "Meist sind nur wenige Hyperparameter wichtig; zufällige Punkte probieren davon mehr verschiedene Werte", "Weil es deterministisch ist",
            "Weil es keine Kreuzvalidierung braucht", "Das stimmt nicht",
            why = "Bergstra & Bengio 2012: Im Gitter wiederholen sich die Werte der wichtigen Achse."),
        c(1, "ev_tuning", "Was macht Early Stopping?",
            "Es beendet das Training, wenn der Validierungsfehler wieder steigt", "Es startet das Training später", "Es löscht Daten", "Es erhöht die Lernrate",
            why = "Eine billige und sehr wirksame Regularisierung für Boosting und neuronale Netze."),
        c(2, "ev_fair", "Wo darf man Oversampling (z. B. SMOTE) anwenden?",
            "Nur auf den Trainingsdaten", "Auf Test- und Trainingsdaten", "Nur auf den Testdaten", "Vor dem Aufteilen auf allen Daten",
            why = "Sonst landen synthetische Verwandte von Testbeispielen im Training – ein Leck mit geschönten Werten."),
        c(2, "ev_fair", "Was misst die Permutation Importance eines Merkmals?",
            "Wie stark die Modellgüte sinkt, wenn man die Spalte zufällig durchmischt", "Wie viele Werte fehlen", "Die Varianz der Spalte", "Die Korrelation mit dem Index",
            why = "Modellunabhängig und auf Validierungsdaten aussagekräftiger als die Unreinheits-Importance von Bäumen."),
        c(2, "ev_fair", "Ein Kreditmodell nutzt kein Merkmal ‚Herkunft‘, aber die Postleitzahl. Warum kann es trotzdem diskriminieren?",
            "Die Postleitzahl kann als Stellvertreter für die Herkunft wirken", "Postleitzahlen sind zufällig", "Ohne das Merkmal ist Fairness garantiert",
            "Modelle können nicht diskriminieren",
            why = "Deshalb Güte und Fehlerraten je Gruppe prüfen, nicht nur sensible Spalten entfernen."),

        // ---------------- Neuronale Netze ----------------
        c(1, "dl_neuron", "Was berechnet ein künstliches Neuron?",
            "Eine gewichtete Summe der Eingänge plus Bias, dann eine Aktivierungsfunktion", "Den Mittelwert aller Daten", "Eine Sortierung",
            "Eine Entropie",
            why = "a = φ(wᵀx + b)."),
        c(2, "dl_neuron", "Warum scheitert ein einzelnes Perzeptron an XOR?",
            "Die XOR-Punkte sind nicht durch eine Gerade trennbar", "XOR hat zu viele Daten", "Die Lernrate ist zu klein", "XOR ist nicht berechenbar",
            why = "Mit einer versteckten Schicht (z. B. OR und NAND, verknüpft mit AND) gelingt es."),
        c(2, "dl_neuron", "Was würde ein tiefes Netz ganz ohne nichtlineare Aktivierungen berechnen?",
            "Nur eine lineare Abbildung – so ausdrucksstark wie eine einzige Schicht", "Beliebige Funktionen", "Gar nichts", "Nur Konstanten",
            why = "W₂(W₁x) = (W₂W₁)x – die Verkettung linearer Abbildungen bleibt linear."),
        c(1, "dl_neuron", "Welche Aktivierung ist Standard in versteckten Schichten klassischer Netze?",
            "ReLU", "Stufenfunktion", "Identität", "Sinus",
            why = "max(0, z) ist billig und hat im aktiven Bereich Ableitung 1 – kein Sättigen."),
        c(1, "dl_neuron", "Welche Ausgabeschicht nimmt man für 10 sich ausschließende Klassen?",
            "10 Neuronen mit Softmax", "1 Neuron mit ReLU", "10 Neuronen ohne Aktivierung und MSE", "Ein Sigmoid-Neuron",
            why = "Softmax liefert 10 Wahrscheinlichkeiten mit Summe 1; Verlust: kategorische Kreuzentropie."),
        c(2, "dl_backprop_numbers", "Mini-Netz: ŷ = w₂·h, h = 0,5, ŷ = 1, y = 3, L = ½(ŷ − y)². Wie groß ist ∂L/∂w₂?",
            "−1", "−2", "2", "0,5",
            why = "∂L/∂w₂ = (ŷ − y)·h = −2·0,5 = −1."),
        c(2, "dl_backprop_numbers", "Was bewirkt Gradient Clipping?",
            "Es begrenzt zu große Gradienten gegen explodierende Updates", "Es vergrößert kleine Gradienten", "Es löscht Schichten", "Es ersetzt die Lernrate",
            why = "Besonders bei RNNs und großen Transformern üblich."),
        c(2, "dl_backprop_numbers", "Warum verschwinden Gradienten in tiefen Sigmoid-Netzen?",
            "σ′ ist höchstens 0,25; viele kleine Faktoren multiplizieren sich gegen null", "Weil Sigmoid negativ ist", "Wegen zu großer Datensätze",
            "Weil Backpropagation nicht funktioniert",
            why = "0,25²⁰ ≈ 10⁻¹². ReLU, gute Initialisierung, Normalisierung und Residualverbindungen helfen."),
        c(1, "dl_backprop_numbers", "Was macht loss.backward() in PyTorch?",
            "Es berechnet per Kettenregel die Gradienten aller Parameter", "Es aktualisiert die Gewichte", "Es lädt Daten", "Es setzt die Gradienten auf null",
            why = "Die Gewichte ändert erst optimizer.step()."),
        c(1, "dl_keras", "Welche Verlustfunktion passt in Keras zu binärer Klassifikation mit Sigmoid-Ausgang?",
            "binary_crossentropy", "mse", "sparse_categorical_crossentropy", "hinge mit 10 Klassen",
            why = "Für K Klassen mit Labels als Zahlen: sparse_categorical_crossentropy mit Softmax."),
        c(2, "dl_keras", "Wie viele Parameter hat Dense(32) nach einer Schicht mit 64 Ausgängen?",
            "2080", "2048", "96", "32",
            why = "64·32 Gewichte + 32 Bias = 2080."),
        c(1, "dl_keras", "Was ist eine Epoche?",
            "Ein vollständiger Durchlauf durch alle Trainingsdaten", "Ein einzelner Gradientenschritt", "Eine Schicht", "Ein Batch von 32 Beispielen",
            why = "Pro Epoche gibt es ⌈N/B⌉ Schritte bei Batchgröße B."),
        c(2, "dl_keras", "Wozu dient der Callback EarlyStopping(restore_best_weights=True)?",
            "Training stoppen, wenn sich die Validierung nicht mehr verbessert, und die besten Gewichte zurückholen", "Das Modell löschen",
            "Die Lernrate erhöhen", "Daten mischen",
            why = "So vermeidet man Overfitting durch zu viele Epochen."),
        c(1, "dl_pytorch", "Welche fünf Schritte hat die PyTorch-Trainingsschleife pro Batch?",
            "Vorwärts, Verlust, zero_grad, backward, step", "Laden, speichern, drucken, löschen, schließen", "fit, predict, score, save, load",
            "Nur backward",
            why = "Ohne zero_grad addieren sich Gradienten über die Batches."),
        c(2, "dl_pytorch", "Warum rechnet man bei der Auswertung in torch.no_grad()?",
            "Es werden keine Gradienten gebraucht – das spart Speicher und Zeit", "Damit das Modell lernt", "Damit Dropout aktiv bleibt", "Weil es Pflicht für die GPU ist",
            why = "Zusätzlich schaltet model.eval() Dropout ab und lässt BatchNorm feste Statistiken nutzen."),
        c(1, "dl_pytorch", "Was liefert ein DataLoader?",
            "Gemischte Batches aus einem Dataset", "Fertige Modelle", "Grafiken", "Gradienten",
            why = "batch_size und shuffle steuern Größe und Mischung."),
        c(2, "dl_cnn", "Eingabe 32×32, Filter 5×5, kein Padding, Stride 1. Ausgabegröße?",
            "28×28", "32×32", "27×27", "16×16",
            why = "(32 + 0 − 5)/1 + 1 = 28."),
        c(2, "dl_cnn", "Warum haben CNNs viel weniger Parameter als vollverbundene Netze für Bilder?",
            "Gewichtsteilung: Derselbe kleine Filter wird an allen Bildpositionen verwendet", "Weil Bilder klein sind", "Weil sie keine Gewichte haben",
            "Weil sie nur Graustufen nutzen",
            why = "Eine 3×3×3-Faltung mit 16 Filtern hat 448 Parameter, unabhängig von der Bildgröße."),
        c(1, "dl_cnn", "Was macht Max-Pooling 2×2?",
            "Es nimmt aus jedem 2×2-Feld den größten Wert und halbiert Höhe und Breite", "Es verdoppelt das Bild", "Es entfernt Farben",
            "Es mittelt über alle Kanäle",
            why = "Verkleinert, spart Rechenzeit und macht unempfindlicher gegen kleine Verschiebungen."),
        c(2, "dl_cnn", "Was ist Datenaugmentation?",
            "Trainingsbilder zufällig spiegeln, drehen, zuschneiden, um mehr Vielfalt zu erzeugen", "Mehr Schichten hinzufügen",
            "Testbilder ins Training kopieren", "Die Lernrate erhöhen",
            why = "Eine der wirksamsten Regularisierungen bei Bildern."),
        c(2, "dl_cnn", "Welche Neuerung ermöglichte ResNets mit über 100 Schichten?",
            "Residualverbindungen y = x + F(x)", "Sigmoid-Aktivierungen", "Größere Filter", "Weniger Daten",
            why = "Der Gradient fließt über die Identität ungeschwächt zurück."),
        c(2, "dl_rnn", "Wofür steht das Vergessenstor eines LSTM?",
            "Es entscheidet, welcher Teil des Zellzustands gelöscht wird", "Es löscht das ganze Modell", "Es entscheidet über die Lernrate",
            "Es steuert die Batchgröße",
            why = "cₜ = fₜ ⊙ cₜ₋₁ + iₜ ⊙ c̃ₜ; fₜ ∈ (0, 1) wird per Sigmoid berechnet."),
        c(2, "dl_rnn", "Warum haben Transformer RNNs bei Sprache weitgehend abgelöst?",
            "Attention sieht alle Positionen direkt und lässt sich parallel trainieren", "RNNs können keine Zahlen", "Transformer brauchen keine Daten",
            "RNNs sind immer größer",
            why = "RNNs arbeiten sequentiell und vergessen bei sehr langen Folgen."),
        c(1, "dl_rnn", "Ein Netz soll aus den letzten 30 Tageswerten den nächsten Wert vorhersagen. Welche Form?",
            "Viele-zu-eins", "Eins-zu-viele", "Eins-zu-eins", "Viele-zu-viele mit Übersetzung",
            why = "30 Eingaben in Folge, eine Ausgabe."),
        c(2, "dl_transfer", "Du hast nur 300 eigene Bilder in 5 Klassen. Bester Ansatz?",
            "Vortrainiertes Netz einfrieren und nur einen neuen Klassifikationskopf trainieren", "Ein großes Netz von null trainieren",
            "KNN auf Rohpixeln", "Gar nicht möglich",
            why = "Die allgemeinen Merkmale des vortrainierten Netzes tragen; nur der Kopf muss neu gelernt werden."),
        c(2, "dl_transfer", "Warum nimmt man beim Feinabstimmen eine sehr kleine Lernrate?",
            "Damit das vortrainierte Wissen nicht zerstört wird", "Damit das Training schneller ist", "Weil große Lernraten verboten sind",
            "Damit mehr Parameter entstehen",
            why = "Große Schritte würden die guten Gewichte überschreiben (katastrophales Vergessen)."),
        c(2, "dl_autoencoder", "Was zwingt einen Autoencoder, Wesentliches zu lernen?",
            "Der Flaschenhals: Der Code ist kleiner als die Eingabe", "Eine große Lernrate", "Labels", "Dropout allein",
            why = "Ohne Flaschenhals könnte er einfach kopieren."),
        c(3, "dl_autoencoder", "Was macht ein VAE im Unterschied zum normalen Autoencoder generativ?",
            "Der latente Raum wird per KL-Term zu einer glatten Normalverteilung, aus der man neue Codes ziehen kann", "Er hat mehr Schichten",
            "Er nutzt keine Decoder", "Er braucht Labels",
            why = "Zieht man z ~ N(0, 1) und decodiert, entstehen neue plausible Beispiele."),
        c(2, "dl_generative", "Wer sind die beiden Gegenspieler in einem GAN?",
            "Generator und Diskriminator", "Encoder und Decoder", "Agent und Umgebung", "Query und Key",
            why = "Der Generator fälscht, der Diskriminator prüft – ein Minimax-Spiel."),
        c(2, "dl_generative", "Was lernt das Netz in einem Diffusionsmodell?",
            "Das in einem Schritt hinzugefügte Rauschen vorherzusagen und damit zu entfernen", "Bilder zu klassifizieren", "Text zu übersetzen",
            "Q-Werte",
            why = "Generieren: von reinem Rauschen aus schrittweise entrauschen."),
        c(3, "dl_generative", "Was ist Mode Collapse?",
            "Ein GAN erzeugt nur noch wenige, sehr ähnliche Ausgaben", "Das Modell vergisst die Lernrate", "Die GPU stürzt ab", "Ein Fehler in Diffusionsmodellen",
            why = "Der Generator hat einen Trick gefunden, den Diskriminator mit wenigen Beispielen zu täuschen."),
        c(3, "dl_generative", "Warum arbeitet Stable Diffusion im latenten Raum eines Autoencoders statt auf Pixeln?",
            "Der Code ist viel kleiner – das Entrauschen wird dadurch viel billiger", "Pixel sind verboten", "Für schönere Farben", "Weil Text Pixel braucht",
            why = "Latente Diffusion: entrauschen auf komprimierten Darstellungen, am Ende einmal decodieren."),

        // ---------------- Reinforcement Learning ----------------
        c(1, "rl_basics", "Was lernt ein Agent im bestärkenden Lernen?",
            "Eine Strategie (Policy), die die Summe der Belohnungen maximiert", "Labels für Bilder", "Cluster", "Assoziationsregeln",
            why = "Belohnungen bewerten Ergebnisse, nicht die einzelnen Aktionen direkt."),
        c(2, "rl_basics", "Belohnungen 0, 0, 10 in den nächsten drei Schritten, γ = 0,9. Return?",
            "8,1", "10", "9", "0",
            why = "G = 0 + 0,9·0 + 0,9²·10 = 8,1."),
        c(2, "rl_basics", "Was bewirkt ein Diskontfaktor γ nahe 0?",
            "Der Agent wird kurzsichtig und zählt fast nur sofortige Belohnungen", "Er plant sehr weit voraus", "Er erkundet mehr", "Er lernt schneller",
            why = "Spätere Belohnungen werden mit γᵏ gewichtet."),
        c(1, "rl_basics", "Was ist das Dilemma zwischen Exploration und Ausbeutung?",
            "Bekannt Gutes nutzen oder Neues ausprobieren, das vielleicht besser ist", "Ob man GPU oder CPU nimmt", "Ob man Daten löscht", "Ob man Labels nutzt",
            why = "ε-greedy ist die einfachste Lösung."),
        c(2, "rl_qlearning", "Q(s,a) = 2, r = 1, max Q(s′,·) = 5, γ = 0,9, α = 0,5. Neuer Q-Wert?",
            "3,75", "5,5", "2", "6,5",
            why = "Ziel = 1 + 0,9·5 = 5,5; TD-Fehler 3,5; 2 + 0,5·3,5 = 3,75."),
        c(2, "rl_qlearning", "Warum heißt Q-Learning ‚off-policy‘?",
            "Es lernt die optimale Strategie, auch wenn die Erfahrung mit einer anderen (z. B. zufälligen) Strategie gesammelt wird", "Weil es keine Strategie hat",
            "Weil es nur offline läuft", "Weil es keine Belohnungen braucht",
            why = "Das Update nutzt max Q(s′, ·), nicht die tatsächlich gewählte nächste Aktion (wie SARSA)."),
        c(3, "rl_deep", "Welche beiden Tricks machten DQN stabil?",
            "Experience Replay und ein langsam aktualisiertes Zielnetz", "Dropout und Pooling", "k-Means und PCA", "Größere Lernrate und weniger Daten",
            why = "Replay bricht Korrelationen zwischen aufeinanderfolgenden Erfahrungen; das Zielnetz verhindert ein ‚Jagen des eigenen Schwanzes‘."),
        c(3, "rl_deep", "Was ist RLHF?",
            "Ein Belohnungsmodell lernt menschliche Vorlieben, das Sprachmodell wird per RL darauf optimiert", "Ein Clustering-Verfahren",
            "Ein Bildformat", "Ein Datensatz für Robotik",
            why = "So werden Chatbots hilfreicher; DPO erreicht Ähnliches ohne explizites RL."),

        // ---------------- Generative KI ----------------
        c(1, "gen_prompting", "Welche Prompt-Technik zeigt dem Modell einige Beispiele des gewünschten Musters?",
            "Few-Shot-Prompting", "Zero-Shot", "Fine-Tuning", "Quantisierung",
            why = "Das Modell lernt das Muster im Kontext, ohne dass Gewichte geändert werden."),
        c(2, "gen_prompting", "Warum hilft ‚Denke Schritt für Schritt‘ bei Rechenaufgaben?",
            "Das Modell nutzt die ausgeschriebenen Zwischenschritte als Arbeitsgedächtnis", "Es wird dadurch größer", "Es schaltet einen Taschenrechner ein",
            "Es hilft gar nicht",
            why = "Chain of Thought: Jeder Zwischenschritt ist Kontext für den nächsten."),
        c(2, "gen_prompting", "Für Code und Fakten wählt man die Temperatur eher …",
            "niedrig, nahe 0", "sehr hoch, über 2", "egal", "negativ",
            why = "Niedrige Temperatur macht die Ausgabe nahezu deterministisch; hohe für kreative Texte."),
        c(1, "gen_prompting", "Ein LLM soll nach etwas Aktuellem gefragt werden, das nach seinem Training geschah. Was hilft?",
            "RAG oder ein Suchwerkzeug, das aktuelle Informationen in den Kontext bringt", "Höhere Temperatur", "Längerer Prompt ohne Daten", "Gar nichts",
            why = "Das Modell kennt nur seine Trainingsdaten und den aktuellen Kontext."),
        c(2, "gen_vector", "Zwei normierte Embeddings haben Kosinusähnlichkeit 1. Was heißt das?",
            "Sie zeigen in dieselbe Richtung – sehr ähnliche Bedeutung", "Sie sind senkrecht", "Sie sind entgegengesetzt", "Sie sind leer",
            why = "cos = 1: gleiche Richtung, 0: unabhängig, −1: entgegengesetzt."),
        c(2, "gen_vector", "Warum nutzen Vektordatenbanken approximative Nachbarsuche (z. B. HNSW)?",
            "Exakte Suche über Millionen Vektoren ist zu langsam; ANN tauscht minimal Genauigkeit gegen enormes Tempo", "Weil exakte Suche falsch ist",
            "Weil Vektoren keine Abstände haben", "Für kleinere Embeddings",
            why = "HNSW hangelt sich durch einen mehrschichtigen Nachbarschaftsgraphen."),
        c(2, "gen_vector", "Eine Suche nach der Artikelnummer ‚XJ-4471‘ findet mit Embeddings nichts Passendes. Was hilft?",
            "Hybride Suche mit Stichwortsuche (BM25)", "Höhere Temperatur", "Größere Chunks", "Weniger Daten",
            why = "Exakte Begriffe, Namen und Nummern findet die klassische Stichwortsuche zuverlässiger."),
        c(2, "gen_frameworks", "Wie läuft ein Funktionsaufruf (Tool Calling) ab?",
            "Das Modell gibt strukturiert Werkzeug und Argumente aus, die Anwendung führt es aus und gibt das Ergebnis zurück", "Das Modell führt selbst Code auf dem Server aus",
            "Das Werkzeug trainiert das Modell", "Gar nicht",
            why = "Die Anwendung behält die Kontrolle über die Ausführung – wichtig für Sicherheit."),
        c(2, "gen_frameworks", "Ein Chatbot ‚vergisst‘ den Anfang eines langen Gesprächs. Warum?",
            "Das Kontextfenster ist begrenzt; ältere Nachrichten fallen heraus oder werden zusammengefasst", "Das Modell löscht seine Gewichte",
            "Die Temperatur ist zu hoch", "Weil es zu wenig GPU hat",
            why = "Das Modell selbst ist zustandslos; Gedächtnis heißt: Verlauf wieder in den Prompt packen."),
        c(2, "gen_finetune", "Welche Faustregel gilt für RAG gegen Fine-Tuning?",
            "RAG für Wissen, Fine-Tuning für Verhalten und Stil", "Fine-Tuning für aktuelles Wissen, RAG für Stil", "Beides ist identisch", "Immer zuerst Fine-Tuning",
            why = "Wissen ändert sich und braucht Quellen; Verhalten lässt sich gut antrainieren."),
        c(3, "gen_finetune", "Warum spart LoRA so viele trainierbare Parameter?",
            "Es lernt nur eine Niedrigrang-Korrektur ΔW = BA mit kleinem Rang r", "Es löscht Schichten", "Es quantisiert die Daten", "Es trainiert nur den Bias",
            why = "r(d + k) statt d·k Parameter, z. B. 0,1–1 %."),
        c(3, "gen_finetune", "Was ist QLoRA?",
            "LoRA auf einem 4-bit-quantisierten, eingefrorenen Basismodell", "Ein Quantencomputer-Verfahren", "Ein Clustering", "Eine Metrik",
            why = "Damit passt die Feinabstimmung großer Modelle auf eine einzelne GPU."),
        c(2, "gen_eval", "Eine RAG-Antwort ist falsch. Was prüft man zuerst?",
            "Ob das Retrieval die richtigen Abschnitte gefunden hat", "Die Temperatur", "Die Bildschirmhelligkeit", "Die Farbe des Logos",
            why = "Die meisten RAG-Fehler entstehen bei der Suche, nicht beim Formulieren."),
        c(2, "gen_eval", "Was ist Prompt-Injection?",
            "Untergeschobener Text in Daten, der dem Modell neue Anweisungen erteilen will", "Ein besonders guter Prompt", "Ein Trainingsverfahren", "Ein Speicherformat",
            why = "Daten nie als Anweisungen behandeln, Werkzeugrechte minimieren, gefährliche Aktionen bestätigen lassen."),
        c(2, "gen_eval", "Was misst ‚Treue‘ (Faithfulness) bei RAG?",
            "Ob alles in der Antwort durch die gefundenen Quellen gedeckt ist", "Wie schnell die Antwort kommt", "Wie lang die Antwort ist", "Die Anzahl der Quellen",
            why = "Untreue Antworten sind Halluzinationen trotz vorhandener Quellen."),

        // ---------------- Engineering ----------------
        c(1, "eng_deploy", "Was muss man beim Speichern eines scikit-learn-Modells unbedingt mitspeichern?",
            "Die ganze Pipeline inklusive Vorverarbeitung", "Nur die Koeffizienten", "Nur die Testdaten", "Nichts weiter",
            why = "Sonst werden neue Daten im Betrieb anders skaliert oder kodiert als im Training."),
        c(2, "eng_deploy", "Wozu dient Docker beim Deployment?",
            "Code, Bibliotheken und Modell in einem überall gleich laufenden Container zu verpacken", "Zum Trainieren schneller Modelle",
            "Zum Labeln von Daten", "Zum Visualisieren",
            why = "Schluss mit ‚bei mir funktioniert es‘."),
        c(2, "eng_deploy", "Nächtliche Bewertung aller Kunden gegen Echtzeit-Betrugsprüfung: Wie heißen die beiden Arten?",
            "Batch- und Echtzeit-(Online-)Vorhersage", "Training und Test", "Bagging und Boosting", "Prompting und RAG",
            why = "Die Wahl bestimmt Architektur, Latenzanforderungen und Kosten."),
        c(2, "eng_spark", "Was bedeutet Lazy Evaluation in Spark?",
            "Transformationen werden erst geplant und bei einer Aktion wie count oder show ausgeführt", "Spark rechnet absichtlich langsam",
            "Spark speichert nichts", "Daten werden nie geladen",
            why = "So optimiert Spark den gesamten Rechenplan auf einmal."),
        c(2, "eng_spark", "Wozu dient der VectorAssembler in Spark MLlib?",
            "Er fasst mehrere Spalten zu einer einzigen Merkmalsvektor-Spalte zusammen", "Er trainiert Modelle", "Er löscht Duplikate", "Er visualisiert Daten",
            why = "MLlib-Modelle erwarten die Merkmale in einer Vektorspalte."),
        c(1, "eng_spark", "Wann lohnt sich Spark eher nicht?",
            "Wenn die Daten bequem in den Speicher eines Rechners passen", "Bei Terabytes in einem Data Lake", "Bei großen ETL-Jobs", "Bei verteilten Daten",
            why = "Dann sind pandas und scikit-learn einfacher und oft schneller."),
        c(2, "eng_mlops", "Betrüger ändern ihre Methoden, das Modell wird schlechter, obwohl die Eingaben ähnlich aussehen. Was liegt vor?",
            "Konzeptdrift", "Datendrift", "Underfitting beim Training", "Ein Tippfehler",
            why = "Der Zusammenhang zwischen Eingabe und Ziel hat sich geändert."),
        c(2, "eng_mlops", "Was speichert Experiment-Tracking (z. B. MLflow)?",
            "Parameter, Metriken, Datenversion und Artefakte jedes Trainingslaufs", "Nur das Endergebnis", "Die Bildschirmfotos", "Passwörter",
            why = "Damit jedes Ergebnis reproduzierbar und vergleichbar ist."),
        c(2, "eng_mlops", "Wie bringt man ein neues Modell vorsichtig in den Betrieb?",
            "Erst im Schattenbetrieb oder für einen kleinen Nutzeranteil (Canary), mit Rollback-Möglichkeit", "Sofort für alle ohne Prüfung",
            "Nur auf dem Testset", "Gar nicht",
            why = "So erkennt man Probleme, bevor sie alle betreffen."),
        c(1, "eng_capstone", "Was zählt bei einem Abschlussprojekt am meisten?",
            "Sauberes Vorgehen: kein Datenleck, passende Metrik, Vergleich mit Basislinie, ehrliche Grenzen", "Die höchste Nachkommastelle",
            "Das größte Modell", "Möglichst viele Bibliotheken",
            why = "Ein erklärbares, sauber bewertetes Modell schlägt ein unverstandenes kompliziertes.")
    )
}
