package app.maximus.lab.domain

/** Second set of concept questions: caloric physics and P(VDF-TrFE-CFE) at defense level, polymers, EE/chips, AI engineering. */
internal object QuizConcepts2 {
    private var n = 0
    private fun c(topic: Topic, diff: Int, chapter: String, prompt: String, correct: String, vararg wrong: String, why: String) =
        Question("cq2-${topic.short}-${++n}", topic, diff, prompt, why, listOf(correct) + wrong, 0, chapterKey = chapter)

    private val C = Topic.CALORIC
    private val P = Topic.POLYMER
    private val E = Topic.ELECTRICAL
    private val A = Topic.AI

    val all: List<Question> = listOf(
        // ================= Kalorik / P(VDF-TrFE-CFE) =================
        c(C, 1, "ca_pvdf_structure", "Welche Konformation ist für die Ferroelektrizität von PVDF verantwortlich?",
            "All-trans (TTTT), weil sich dann alle CF₂-Dipole addieren", "TGTG′, weil sie am stabilsten ist", "Helikale Konformation wie in PTFE", "Völlig ungeordnete Gauche-Sequenzen",
            why = "In der all-trans-Zickzackkette zeigen alle C–F-Dipole auf dieselbe Seite (β-Phase). TGTG′ (α-Phase) ist zwar thermodynamisch bevorzugt, aber in antiparalleler Packung unpolar."),
        c(C, 2, "ca_pvdf_structure", "Wozu dient TrFE im Copolymer P(VDF-TrFE)?",
            "Es stabilisiert die polare all-trans-Phase direkt aus der Schmelze und ermöglicht eine Curie-Umwandlung unter dem Schmelzpunkt",
            "Es erhöht die Leitfähigkeit", "Es macht das Material amorph", "Es senkt die Durchschlagfestigkeit gezielt",
            why = "Der sperrigere TrFE-Baustein verhindert die TGTG′-Packung; ab ≈ 20 mol-% kristallisiert das Polymer polar. Die Gitteraufweitung erlaubt eine echte ferro-paraelektrische Umwandlung, deren T_C mit dem TrFE-Gehalt sinkt."),
        c(C, 2, "ca_pvdf_structure", "Welche Rolle spielt CFE im Terpolymer P(VDF-TrFE-CFE)?",
            "Statistisch eingebaute sperrige Defekte zerlegen die langreichweitige polare Ordnung in polare Nanobereiche (Relaxorverhalten)",
            "CFE ist der ferroelektrische Hauptbestandteil", "CFE vernetzt die Ketten chemisch", "CFE erhöht die Kristallinität auf nahezu 100 %",
            why = "Das große Cl-Atom weitet das Gitter auf und wirkt als Zufallsfeld/Störstelle. Ergebnis: breites, frequenzabhängiges ε-Maximum nahe Raumtemperatur, schlanke P(E)-Schleife, hohe Permittivität."),
        c(C, 2, "ca_pvdf_structure", "Warum ist die gemessene remanente Polarisation von PVDF-Filmen deutlich kleiner als der ideale Kristallwert (≈ 0,13 C/m²)?",
            "Nur der kristalline, orientierte Anteil trägt bei; amorphe Bereiche und Fehlorientierung verdünnen die Polarisation",
            "Weil die Dipole bei Raumtemperatur verschwinden", "Weil Fluor kein Dipolmoment erzeugt", "Weil Elektroden die Polarisation absorbieren",
            why = "P_r ≈ X_c · ⟨cos θ⟩ · P_s,ideal. Bei 50 % Kristallinität und unvollständiger Ausrichtung landet man bei 0,05–0,08 C/m²."),
        c(C, 2, "ca_pvdf_structure", "Mit welchen Methoden belegt man Phase und Kristallinität eines PVDF-basierten Films?",
            "FTIR (charakteristische Banden), XRD (Netzebenenabstände), DSC (Schmelz- und Curie-Peaks)", "Nur mit der P(E)-Schleife",
            "Mit dem Leckstrom", "Mit Rasterelektronenmikroskopie allein",
            why = "FTIR unterscheidet α und β (z. B. 763/975 cm⁻¹ vs. 840/1280 cm⁻¹), XRD zeigt die Gitterabstände und Phasen, DSC liefert X_c = ΔH_m/ΔH_m⁰ und die Curie-Umwandlung. Die P(E)-Schleife ist ein Funktionsnachweis, keine Strukturanalyse."),
        c(C, 2, "ca_relaxor", "Was kennzeichnet ein Relaxor-Ferroelektrikum im Unterschied zu einem normalen Ferroelektrikum?",
            "Ein breites, frequenzabhängiges Permittivitätsmaximum ohne makroskopische Symmetriebrechung", "Ein scharfer Curie-Peak bei fester Temperatur",
            "Eine besonders große remanente Polarisation", "Keine Polarisation unter Feld",
            why = "Relaxoren haben polare Nanobereiche mit einem Spektrum von Relaxationszeiten; T_m verschiebt sich mit der Messfrequenz (Vogel-Fulcher). Normale Ferroelektrika zeigen einen scharfen, frequenzunabhängigen Curie-Punkt."),
        c(C, 3, "ca_relaxor", "Was beschreibt die Vogel-Fulcher-Beziehung in Relaxoren?",
            "Die Frequenzabhängigkeit von T_m mit einer Einfriertemperatur T_f, bei der die Relaxationszeit divergiert",
            "Den linearen Anstieg der Polarisation mit dem Feld", "Die Durchschlagstatistik", "Den Zusammenhang zwischen ΔT und E²",
            why = "f = f₀ exp[−E_a/(k_B(T_m − T_f))]. Unterhalb T_f ist der Relaxor nichtergodisch: PNR sind eingefroren, Feldinduzierung erzeugt bleibende Ordnung."),
        c(C, 3, "ca_relaxor", "Warum ist die indirekte Maxwell-Methode im nichtergodischen Relaxorzustand fragwürdig?",
            "Maxwell-Relationen setzen Gleichgewicht und eindeutige Zustandsfunktionen voraus, die bei Ergodizitätsbruch und Hysterese fehlen",
            "Weil der Relaxor dort keine Polarisation hat", "Weil Maxwell-Relationen nur für Gase gelten", "Weil die Wärmekapazität dort null ist",
            why = "Unterhalb T_f hängt P von der Vorgeschichte ab; (∂P/∂T)_E aus Schleifen bei verschiedenen Temperaturen ist keine Gleichgewichtsableitung. Ergebnisse können über- oder unterschätzt und sogar vorzeichenfalsch sein — direkte Messung ist Pflicht."),
        c(C, 3, "ca_relaxor", "Warum liegen besonders große EC-Effekte oft nahe einem kritischen Endpunkt im E-T-Phasendiagramm?",
            "Dort ist (∂P/∂T)_E maximal und die Polarisation reagiert extrem empfindlich auf Feld und Temperatur, ohne Hysterese eines Übergangs 1. Ordnung",
            "Weil dort die Durchschlagfestigkeit maximal ist", "Weil die Dichte dort null wird", "Weil dort keine Entropie existiert",
            why = "Am kritischen Punkt endet die Linie der 1.-Ordnung-Übergänge; Suszeptibilitäten divergieren, die latente Wärme geht gegen null. Man erhält große, reversible Entropieänderungen — das Ideal für Kühlzyklen."),
        c(C, 2, "ca_pvdf_ece", "Wie skaliert der elektrokalorische Temperaturhub eines linearen Dielektrikums bei kleinen Feldern?",
            "Quadratisch mit dem Feld, ΔT ∝ E²", "Linear mit dem Feld", "Exponentiell mit dem Feld", "Unabhängig vom Feld",
            why = "ΔS = ∫(∂P/∂T)dE mit P = ε₀χ(T)E ⇒ ΔS = ½ε₀(∂χ/∂T)E². Bei hohen Feldern flacht die Kurve ab, weil die Polarisation sättigt."),
        c(C, 2, "ca_pvdf_ece", "Warum ist die hohe Durchschlagfestigkeit von Polymerfilmen ein entscheidender Vorteil für die Elektrokalorik?",
            "ΔT wächst stark mit dem Feld; Polymere vertragen Felder von einigen 100 MV/m, Keramiken meist nur einen Bruchteil davon",
            "Weil Polymere dadurch besser Wärme leiten", "Weil dann keine Polarisation nötig ist", "Weil der Durchschlag selbst kühlt",
            why = "Die erreichbare Polarisationsänderung ΔP und damit ΔS hängen vom maximalen Feld ab. Dünne Polymerfilme halten sehr hohe Felder aus und gleichen die kleinere EC-Stärke pro MV/m mehr als aus."),
        c(C, 2, "ca_pvdf_ece", "Woran erkennt man im Experiment, dass eine Temperaturänderung elektrokalorisch und nicht Joulesche Wärme ist?",
            "Beim Einschalten erwärmt, beim Ausschalten kühlt die Probe um nahezu denselben Betrag; Joulesche Wärme heizt in beiden Fällen",
            "Am Vorzeichen der Spannung", "Daran, dass sich die Probe nur beim Einschalten erwärmt", "Am Elektrodenmaterial",
            why = "Der EC-Effekt ist reversibel (ΔT_on ≈ −ΔT_off). Leitungs- und Hysteresewärme sind dissipativ und liefern immer Erwärmung; ihre Größe lässt sich aus Leckstrom und Schleifenfläche abschätzen."),
        c(C, 3, "ca_pvdf_ece", "Was gibt die Schleifenfläche ∮E dP pro Zyklus an?",
            "Die pro Volumen dissipierte Energie (Hysteresverlust), die als Wärme anfällt", "Den reversiblen elektrokalorischen Effekt",
            "Die gespeicherte, rückgewinnbare Energie", "Die Wärmekapazität",
            why = "Eine geschlossene Schleife bedeutet Netto-Arbeit, die irreversibel in Wärme übergeht. Schlanke Schleifen (Relaxoren) sind deshalb für effiziente Kühlung zentral."),
        c(C, 2, "ca_pvdf_ece", "Warum ist ein über einen breiten Temperaturbereich ausgedehntes EC-Maximum (Terpolymer) praktisch vorteilhaft?",
            "Ein Kühlgerät arbeitet über eine Temperaturspanne; ein scharfer Peak liefert nur in einem schmalen Fenster große Effekte",
            "Weil dann keine Elektroden nötig sind", "Weil breite Peaks immer größer sind", "Weil sich dadurch die Dichte erhöht",
            why = "Regeneratoren und Kaskaden verteilen das Material über verschiedene Temperaturen. Ein breiter, um Raumtemperatur liegender Effekt nutzt das Material überall."),
        c(C, 3, "ca_ec_measure", "Ein 10 μm dicker EC-Film liegt auf einem dicken Substrat. Warum misst man ohne Korrektur einen zu kleinen Temperaturhub?",
            "Die Wärme fließt innerhalb weniger Millisekunden (τ ≈ d²/α) ins Substrat ab und die thermische Masse von Sensor/Elektroden verdünnt das Signal",
            "Weil dünne Filme keine EC-Effekte haben", "Weil das Substrat das Feld abschirmt", "Weil das Thermometer zu genau ist",
            why = "Mit α ≈ 10⁻⁷ m²/s ist τ ≈ 1 ms. Ohne schnelle Messung und Wärmeübergangsmodell sieht man nur einen Bruchteil von ΔT_ad. Freistehende Filme oder Kalorimetrie mit Wärmestromintegration umgehen das."),
        c(C, 2, "ca_ec_measure", "Was misst die quasi-direkte Methode (DSC mit Feld) eigentlich?",
            "Die beim isothermen Feldschalten ausgetauschte Wärme Q = TΔS", "Direkt den adiabatischen Temperaturhub",
            "Die Polarisation", "Den Leckstrom",
            why = "Die DSC hält die Temperatur konstant und integriert den Wärmestrom. Mit der Wärmekapazität folgt ΔT_ad ≈ −TΔS/c_E. Vorteil: echte Wärme statt Maxwell-Annahme."),
        c(C, 2, "ca_ec_measure", "Warum muss man in einer Publikation zu ΔT immer Feld, Temperatur und Methode angeben?",
            "ΔT hängt stark von allen drei ab; ohne sie sind Werte nicht vergleichbar und indirekte Werte oft systematisch verfälscht",
            "Weil es formal vorgeschrieben ist, physikalisch aber egal", "Weil ΔT unabhängig vom Feld ist", "Nur wegen der Einheiten",
            why = "Gerade in der EC-Literatur unterscheiden sich direkte und indirekte Werte teils um Faktoren. Gute Praxis ist zusätzlich die Angabe der Probengeometrie und der Feldform."),
        c(C, 2, "ca_ec_devices", "Warum liefert ein einzelner EC-Film als Kühler nur eine Temperaturspanne in der Größenordnung von ΔT_ad?",
            "Ohne Regeneration oder Kaskade pumpt jeder Zyklus Wärme nur über den eigenen adiabatischen Hub",
            "Weil Polymere keine Wärme leiten", "Weil die Spanne immer genau Carnot entspricht", "Weil das Feld nach einem Zyklus verschwindet",
            why = "Größere Spannen erfordern Regeneration (z. B. Fluid, das Wärme zwischen Zyklen zurückführt) oder mehrere Stufen mit gestaffelten Temperaturen."),
        c(C, 3, "ca_ec_devices", "Welcher Faktor begrenzt die Kühlleistungsdichte eines Filmgeräts typischerweise zuerst?",
            "Der Wärmeübertrag (Kontaktwiderstand, Diffusionszeit) begrenzt die Zyklusfrequenz", "Die Lichtgeschwindigkeit",
            "Die Zahl der Elektronen im Film", "Der magnetische Fluss",
            why = "Q̇ ≈ f·ρcΔT·V. Die Frequenz kann nur so hoch sein, dass der Film in jeder Halbperiode Wärme abgeben bzw. aufnehmen kann; deshalb sind dünne Filme und gute Kontakte entscheidend."),
        c(C, 3, "ca_ec_devices", "Warum ist die Rückgewinnung der elektrischen Energie für die Leistungszahl eines EC-Kühlers so wichtig?",
            "Der Film ist ein Kondensator; die meiste beim Laden aufgewendete Energie ist gespeichert und kann zurückgeführt werden — ohne Rückgewinnung wäre der COP klein",
            "Weil die Energie sonst den Film beschädigt", "Weil sie die Wärmekapazität erhöht", "Weil Rückgewinnung den EC-Effekt verdoppelt",
            why = "Nur der Anteil, der der gepumpten Wärme und den Verlusten entspricht, wird wirklich verbraucht. Mit > 90 % Rückgewinnung werden Leistungszahlen konkurrenzfähig."),
        c(C, 2, "ca_ec_devices", "Wie definiert man den exergetischen (Carnot-bezogenen) Wirkungsgrad eines Kühlers?",
            "η_II = COP/COP_Carnot mit COP_Carnot = T_k/(T_w − T_k)", "η = Q_w/Q_k", "η = ΔT/T", "η = W_el/Q_k",
            why = "Er zeigt, wie nah ein Gerät an die thermodynamische Grenze kommt — fairer Vergleich zwischen Technologien bei unterschiedlichen Temperaturspannen."),
        c(C, 3, "ca_electromech", "Welches Vorzeichen hat der Elektrostriktionskoeffizient Q₃₃ PVDF-basierter Polymere, und was bedeutet das?",
            "Negativ: Der Film wird in Feldrichtung dünner und dehnt sich in der Ebene", "Positiv: Der Film wird in Feldrichtung dicker",
            "Null: Polymere zeigen keine Elektrostriktion", "Er wechselt mit jedem Zyklus",
            why = "Feldinduzierte Konformationsänderungen (Gauche → trans) und Ausrichtung verkürzen die Dimension parallel zum Feld. Für EC-Experimente heißt das: mechanische Randbedingungen beeinflussen P(E) und ΔT."),
        c(C, 2, "ca_electromech", "Warum erwärmt sich Naturkautschuk beim schnellen Recken besonders stark?",
            "Zusätzlich zur Entropieabnahme der Ketten setzt dehnungsinduzierte Kristallisation latente Wärme frei",
            "Weil Reibung zwischen Molekülen Wärme erzeugt", "Weil die Dichte abnimmt", "Weil Elektronen angeregt werden",
            why = "Der Gough-Joule-Effekt ist entropisch; bei großen Dehnungen kristallisiert Naturkautschuk und liefert einen großen elastokalorischen Effekt — mit dem Nachteil großer Dehnungen und Hysterese."),
        c(C, 3, "ca_multi_theory", "Welche Kreuz-Maxwell-Relation verbindet Elektrostriktion/Piezoeffekt mit dem Spannungseinfluss auf die Polarisation?",
            "(∂P/∂σ)_{T,E} = (∂ε/∂E)_{T,σ}", "(∂S/∂E)_T = (∂P/∂T)_E", "(∂S/∂σ)_T = (∂V/∂T)_p", "(∂M/∂T)_H = (∂S/∂H)_T",
            why = "Sie folgt aus der Gibbs-Funktion G(T, E, σ) durch Vertauschen der gemischten Ableitungen. Sie erklärt, warum eine mechanische Spannung die feldinduzierte Polarisation und damit den EC-Effekt verändert."),
        c(C, 3, "ca_multi_theory", "Was kann man mit einem zweiten Feld in einem multikalorischen Zyklus erreichen, was mit einem Feld allein schwierig ist?",
            "Die Hysterese eines Übergangs 1. Ordnung umgehen, indem Hin- und Rückumwandlung mit unterschiedlichen Feldern getrieben werden",
            "Den zweiten Hauptsatz umgehen", "Unendliche Temperaturspannen erzeugen", "Die Wärmekapazität auf null setzen",
            why = "Im Feldraum lassen sich Pfade wählen, die die Hystereseschleife eines Feldes nicht vollständig durchlaufen. Zusätzlich kann ein Hilfsfeld die Übergangstemperatur an die Arbeitstemperatur anpassen."),
        c(C, 3, "ca_defense", "Ein Prüfer fragt: „Ist Ihr Material besser als BaTiO₃-Vielschichtkondensatoren?“ Was ist die physikalisch saubere Antwort?",
            "Kommt auf die Gütezahl an: pro Feld oft nein, pro Masse und bei maximalem Feld oft ja; dazu Wärmeleitfähigkeit, Zuverlässigkeit und Temperaturbereich vergleichen",
            "Ja, Polymere sind in jeder Hinsicht überlegen", "Nein, Polymere zeigen keinen EC-Effekt", "Das lässt sich nicht vergleichen",
            why = "Gute Verteidigung heißt: Kriterium nennen. Keramiken haben größere ΔT/ΔE und bessere Wärmeleitung, Polymere höhere Felder, Flexibilität und große ΔS pro Masse. Systemgrößen (COP, Leistungsdichte, Lebensdauer) entscheiden."),
        c(C, 3, "ca_defense", "Wie begegnet man dem Einwand, die gemessene Kühlung sei durch Leckstrom verfälscht?",
            "Leckstrom messen, Joule-Wärme σE²·t mit ρcΔT vergleichen, Ein-/Ausschaltasymmetrie auswerten und ggf. Feldform variieren",
            "Indem man die Messung bei höherer Temperatur wiederholt", "Indem man das Feld verdoppelt", "Gar nicht, das ist unvermeidbar",
            why = "Quantitative Abschätzung plus Symmetrietest ist das stärkste Argument. Höhere Temperaturen vergrößern die Leitfähigkeit sogar."),
        c(C, 2, "ca_defense", "Was ist der wichtigste Grund für die Forschung an kalorischer Kühlung?",
            "Kältemittelfreie Kühlung ohne Treibhausgase mit potenziell hohem Wirkungsgrad und kompakter, geräuschloser Bauweise",
            "Weil Kompressoren physikalisch unmöglich sind", "Weil sie niedrigere Temperaturen als Heliumkühlung erreicht", "Weil sie keine Energie benötigt",
            why = "Klassische Dampfkompression nutzt Kältemittel mit oft hohem Treibhauspotential. Festkörperkühlung vermeidet das und eignet sich für Mikrosysteme und Elektronikkühlung."),
        c(C, 3, "ca_defense", "Welche offene Grundlagenfrage zur Elektrokalorik in Polymeren ist wissenschaftlich am interessantesten?",
            "Welcher Anteil der feldinduzierten Entropieänderung aus Dipolorientierung und welcher aus Kettenkonformationen stammt",
            "Ob Polymere elektrisch geladen sind", "Ob der EC-Effekt Energie erzeugt", "Ob die Elektroden aus Gold sein müssen",
            why = "Die mikroskopische Herkunft der polaren Entropie bestimmt, wie man Materialien gezielt verbessern kann. Simulationen (MD, Monte Carlo) und temperaturabhängige Spektroskopie adressieren diese Frage."),

        // ================= Polymerphysik =================
        c(P, 1, "po_chain", "Wie skaliert die Größe einer idealen Polymerkette mit der Zahl der Segmente N?",
            "R ∝ √N", "R ∝ N", "R ∝ N²", "R unabhängig von N",
            why = "Zufallsweg: ⟨R²⟩ = Nb². Die Kette ist viel kompakter als ihre Konturlänge Nb — ein Knäuel."),
        c(P, 2, "po_chain", "Warum ist die Rückstellkraft einer idealen Kette proportional zur Temperatur?",
            "Sie ist entropisch: Strecken reduziert die Zahl der Konformationen, F = −TS dominiert", "Weil Bindungen bei Wärme steifer werden",
            "Weil die Kette bei Wärme schrumpft", "Das stimmt nicht; die Kraft ist temperaturunabhängig",
            why = "F(R) = 3k_BT R²/(2Nb²) ⇒ f = 3k_BT R/(Nb²). Mehr thermische Bewegung bedeutet stärkeres „Zurückziehen“ in wahrscheinlichere Knäuelzustände."),
        c(P, 1, "po_chain", "Was beschreibt die Dispersität Đ = M_w/M_n?",
            "Die Breite der Molmassenverteilung (Đ = 1: alle Ketten gleich lang)", "Die Kristallinität", "Die Glasübergangstemperatur", "Die Kettensteifigkeit",
            why = "M_w gewichtet schwere Ketten stärker als M_n, daher Đ ≥ 1. Lebende Polymerisationen erreichen Đ ≈ 1,05, radikalische Polymerisationen oft ≈ 2."),
        c(P, 2, "po_real", "Was passiert mit einer Polymerkette am Theta-Punkt?",
            "Abstoßung und Anziehung der Monomere heben sich auf; die Kette verhält sich ideal (R ∝ N^{1/2})", "Sie kristallisiert",
            "Sie zerfällt in Monomere", "Sie streckt sich vollständig",
            why = "Das effektive ausgeschlossene Volumen v ∝ (1 − θ/T) verschwindet bei T = θ. Darüber quillt sie (ν ≈ 0,588), darunter kollabiert sie (ν = 1/3)."),
        c(P, 2, "po_real", "Warum gibt die Flory-Theorie trotz grober Näherungen einen fast richtigen Exponenten?",
            "Sie überschätzt sowohl die Abstoßungs- als auch die Elastizitätsenergie, und die Fehler kompensieren sich weitgehend",
            "Weil sie exakt ist", "Weil sie Quanteneffekte berücksichtigt", "Weil der Exponent zufällig universell 1/2 ist",
            why = "ν_Flory = 3/5 gegen ν ≈ 0,588 aus Renormierung. Ein berühmtes Beispiel dafür, dass einfache Skalenargumente in der Polymerphysik sehr weit tragen."),
        c(P, 2, "po_solutions", "Warum mischen sich zwei verschiedene langkettige Polymere fast nie?",
            "Die Mischungsentropie pro Volumen ist um 1/N reduziert; schon ein kleines positives χ führt zur Entmischung",
            "Weil Polymere keine Entropie haben", "Weil sie sich chemisch zersetzen", "Weil die Ketten zu leicht sind",
            why = "Flory-Huggins: ΔF/kT = (φ/N_A)lnφ + ((1−φ)/N_B)ln(1−φ) + χφ(1−φ). Für N_A = N_B = N liegt χ_c = 2/N — winzig für große N."),
        c(P, 2, "po_solutions", "Was ist die Überlappungskonzentration c*?",
            "Die Konzentration, bei der die Knäuel den Raum gerade füllen und sich zu durchdringen beginnen", "Die Löslichkeitsgrenze",
            "Die Konzentration am Glasübergang", "Die Konzentration, bei der Ketten kristallisieren",
            why = "c* ≈ N/R³. Darüber (halbverdünnt) hängen Eigenschaften nur noch von c ab (Korrelationslänge ξ ∝ c^{−3/4}), nicht mehr von N."),
        c(P, 3, "po_solutions", "Warum bilden Blockcopolymere Nanostrukturen statt makroskopischer Phasen?",
            "Die unverträglichen Blöcke sind kovalent verbunden; sie können nur auf der Skala der Kettengröße entmischen",
            "Weil sie Kristalle bilden", "Weil sie elektrisch geladen sind", "Weil χ bei ihnen negativ ist",
            why = "Mikrophasenseparation: Lamellen, Zylinder, Gyroid oder Kugeln je nach Volumenanteil, ab χN ≳ 10,5 (symmetrisch, Mittelfeld)."),
        c(P, 2, "po_rubber", "Warum wird ein gespannter Gummi beim Erwärmen (bei fester Länge) straffer, während ein Metall eher nachgibt?",
            "Gummielastizität ist entropisch, G = nk_BT steigt mit T; Metalle sind energieelastisch",
            "Weil Gummi bei Wärme kristallisiert", "Weil Gummi sich bei Wärme ausdehnt und dadurch straffer wird", "Weil Metalle keine Elastizität haben",
            why = "Die Kraft eines gedehnten Netzwerks ist ∝ T. Bei sehr kleinen Dehnungen überlagert die thermische Ausdehnung (thermoelastische Inversion)."),
        c(P, 2, "po_rubber", "Wie hängt der Schermodul eines Gummis von der Vernetzungsdichte ab?",
            "Proportional zur Dichte der elastisch wirksamen Netzketten (G = ρRT/M_x)", "Umgekehrt proportional", "Gar nicht", "Exponentiell",
            why = "Jede Netzkette ist eine entropische Feder mit k_BT Energieskala. Mehr Vernetzung (kleineres M_x) bedeutet steiferen Gummi."),
        c(P, 3, "po_dynamics", "Warum steigt die Viskosität verschlaufter Schmelzen etwa mit M^{3,4}?",
            "Ketten können sich nur entlang ihrer Röhre bewegen (Reptation); die Ausreptationszeit wächst mit ≈ N³, Fluktuationen ergeben 3,4",
            "Weil längere Ketten chemisch reagieren", "Weil die Dichte mit M steigt", "Weil hydrodynamische Wechselwirkungen dominieren",
            why = "Unterhalb der kritischen Molmasse gilt η ∝ M (Rouse). Darüber verhindern Verschlaufungen Querbewegungen; Doi-Edwards sagen M³, Röhrenlängenfluktuationen und constraint release erklären den beobachteten Exponenten."),
        c(P, 2, "po_dynamics", "Was beschreibt der Verlustfaktor tan δ = G″/G′?",
            "Das Verhältnis von dissipierter zu gespeicherter Energie pro Schwingungszyklus", "Die Dichte", "Die Kristallinität", "Den Brechungsindex",
            why = "Am Glasübergang hat tan δ ein Maximum — daher ist dynamisch-mechanische Analyse (DMA) eine empfindliche Methode zur T_g-Bestimmung."),
        c(P, 3, "po_dynamics", "Was erlaubt die Zeit-Temperatur-Superposition?",
            "Messungen bei verschiedenen Temperaturen durch Verschieben um a_T zu einer Masterkurve über viele Zeitdekaden zu kombinieren",
            "Die Temperatur aus der Zeit zu berechnen", "Kristallisation zu verhindern", "Die Molmasse zu bestimmen",
            why = "Wenn alle Relaxationsprozesse dieselbe Temperaturabhängigkeit haben (thermorheologisch einfach), entspricht eine höhere Temperatur einer schnelleren Zeitskala; a_T folgt oberhalb T_g der WLF-Gleichung."),
        c(P, 2, "po_glass", "Warum hängt die gemessene Glasübergangstemperatur von der Kühlrate ab?",
            "Der Glasübergang ist kinetisch: Das System fällt aus dem Gleichgewicht, wenn die Relaxationszeit die Zeitskala des Experiments übersteigt",
            "Weil es ein Phasenübergang erster Ordnung ist", "Weil Thermometer ungenau sind", "Weil die Molmasse sich ändert",
            why = "Schnelleres Kühlen friert früher (bei höherer Temperatur) ein. Typisch ≈ 3 K Verschiebung pro Dekade Kühlrate."),
        c(P, 1, "po_glass", "Wie wirkt ein Weichmacher auf die Glasübergangstemperatur?",
            "Er senkt T_g, indem er das freie Volumen und die Kettenbeweglichkeit erhöht", "Er erhöht T_g stark", "Er hat keinen Einfluss", "Er macht das Polymer kristallin",
            why = "Klassisches Beispiel: Weich-PVC. Fox- und Gordon-Taylor-Gleichung beschreiben T_g von Mischungen."),
        c(P, 2, "po_cryst", "Warum schmelzen Polymerkristalle deutlich unter dem Gleichgewichtsschmelzpunkt T_m⁰?",
            "Die Lamellen sind dünn (gefaltete Ketten), die Faltflächenenergie senkt die Schmelztemperatur (Gibbs-Thomson)",
            "Weil Polymere keine Kristalle bilden", "Weil sie Wasser enthalten", "Weil der Druck zu hoch ist",
            why = "T_m = T_m⁰(1 − 2σ_e/(Δh_v ℓ)). Dickere Lamellen (Tempern) schmelzen höher; aus T_m gegen T_c erhält man T_m⁰ (Hoffman-Weeks)."),
        c(P, 2, "po_cryst", "Warum hat die Kristallisationsgeschwindigkeit eines Polymers ein Maximum zwischen T_g und T_m?",
            "Nahe T_m fehlt die Triebkraft (Unterkühlung), nahe T_g die Kettenbeweglichkeit", "Weil die Dichte dort maximal ist",
            "Weil dort die Molmasse am größten ist", "Das stimmt nicht, sie steigt monoton",
            why = "Wachstumsrate = Beweglichkeitsterm (sinkt zu T_g hin) × Keimbildungsterm (sinkt zu T_m hin). Deshalb lassen sich manche Polymere durch schnelles Abschrecken amorph einfrieren (z. B. PET)."),
        c(P, 3, "po_electroactive", "Was zeigt ein Anstieg von ε″ ∝ 1/ω bei tiefen Frequenzen in der dielektrischen Spektroskopie?",
            "Gleichstromleitfähigkeit (ε″ = σ/(ε₀ω)), keine Dipolrelaxation", "Eine besonders große Polarisation", "Die Kristallisation", "Den Glasübergang",
            why = "Leitfähigkeit verdeckt oft die α-Relaxation; man trennt sie über die Ableitungsmethode oder den Modulformalismus. Für EC-Materialien bedeutet starke Leitfähigkeit Joulesche Verluste."),
        c(P, 2, "po_electroactive", "Warum leiten konjugierte Polymere erst nach Dotierung gut?",
            "Die Peierls-Lücke macht sie intrinsisch halbleitend; Dotierung erzeugt Ladungsträger (Polaronen, Bipolaronen)",
            "Weil Dotierung die Ketten verlängert", "Weil sie Metallatome enthalten", "Weil die Ketten dabei kristallisieren",
            why = "Alternierende Bindungslängen öffnen eine Lücke von 1–3 eV. Oxidation oder Reduktion verändert die Elektronenzahl; die Leitfähigkeit steigt um viele Größenordnungen."),
        c(P, 3, "po_electroactive", "Was begrenzt die Dehnung dielektrischer Elastomeraktoren?",
            "Elektromechanische Instabilität (Pull-in) und Durchschlag, weil der dünner werdende Film das Feld weiter erhöht",
            "Die Lichtgeschwindigkeit", "Der Mangel an Elektronen", "Die Kristallisation der Elektroden",
            why = "Der Maxwell-Druck p = ε₀ε_rE² wächst, wenn der Film dünner wird (E = U/d). Ohne Gegenmaßnahmen (Vorspannung, versteifende Elastomere) kollabiert der Film."),

        // ================= Elektrotechnik und Chips =================
        c(E, 1, "ee_dc", "Was ist die Aussage des Thevenin-Theorems?",
            "Jedes lineare Netzwerk wirkt an zwei Klemmen wie eine Spannungsquelle mit Innenwiderstand", "Jeder Widerstand rauscht",
            "Ströme addieren sich nur in Reihenschaltung", "Spannungen sind immer positiv",
            why = "U_th ist die Leerlaufspannung, R_th = U_Leerlauf/I_Kurzschluss. Das vereinfacht die Analyse von Lasten an komplizierten Schaltungen enorm."),
        c(E, 2, "ee_dc", "Warum betreibt man Kraftwerke nicht bei Leistungsanpassung?",
            "Bei Anpassung geht die Hälfte der Energie im Innenwiderstand verloren (η = 50 %)", "Weil dann keine Leistung fließt",
            "Weil Generatoren keinen Innenwiderstand haben", "Weil Anpassung nur bei Gleichstrom gilt",
            why = "Leistungsanpassung maximiert die übertragene Leistung, nicht den Wirkungsgrad. In der Energietechnik will man R_L ≫ R_i, in der Signalübertragung dagegen Anpassung (Reflexionen, maximale Signalleistung)."),
        c(E, 1, "ee_ac", "Wie verhält sich ein Kondensator für sehr hohe und sehr tiefe Frequenzen?",
            "Hohe Frequenz: fast Kurzschluss; tiefe Frequenz und Gleichstrom: Unterbrechung", "Umgekehrt", "Immer wie ein Widerstand", "Er ist frequenzunabhängig",
            why = "Z_C = 1/(iωC). Deshalb blockt ein Koppelkondensator Gleichspannung und lässt Signale durch, und ein Stützkondensator schließt Störungen kurz."),
        c(E, 2, "ee_ac", "Was bedeutet ein Abfall von −20 dB/Dekade im Bode-Diagramm?",
            "Eine Polstelle (Filter 1. Ordnung): Die Amplitude fällt pro Frequenzverzehnfachung auf ein Zehntel", "Eine Verstärkung um 20",
            "Eine Resonanz", "Einen Kurzschluss",
            why = "|H| ∝ 1/ω oberhalb der Grenzfrequenz. Filter n-ter Ordnung fallen mit −20n dB/Dekade; die Phase dreht pro Pol um −90°."),
        c(E, 2, "ee_ac", "Was passiert im Serienschwingkreis bei der Resonanzfrequenz?",
            "Die Blindwiderstände von L und C heben sich auf; der Strom ist maximal und nur durch R begrenzt", "Der Strom wird null",
            "Die Spannung an C wird null", "Die Frequenz verdoppelt sich",
            why = "Bei ω₀ = 1/√(LC) ist Z = R. Die Spannungen an L und C sind dabei Q-mal so groß wie die Eingangsspannung (Spannungsüberhöhung)."),
        c(E, 1, "ee_opamp", "Warum ist am gegengekoppelten OPV die Differenzspannung zwischen den Eingängen nahezu null?",
            "Die riesige Leerlaufverstärkung regelt den Ausgang so, dass die Eingänge fast gleich sind (virtueller Kurzschluss)",
            "Weil die Eingänge intern verbunden sind", "Weil kein Strom fließt", "Das gilt nur ohne Gegenkopplung",
            why = "U_a = A(U₊ − U₋) mit A ~ 10⁵–10⁶: Für endliche U_a muss die Differenz winzig sein. Ohne Gegenkopplung geht der Ausgang in die Sättigung (Komparator)."),
        c(E, 2, "ee_opamp", "Was bedeutet ein konstantes Verstärkungs-Bandbreite-Produkt?",
            "Mehr Verstärkung kostet proportional Bandbreite", "Die Bandbreite ist unabhängig von der Verstärkung", "Der OPV ist nichtlinear", "Die Verstärkung ist frequenzunabhängig",
            why = "Ein dominanter Pol gibt A(f) ≈ GBW/f. Bei A = 100 und GBW = 10 MHz bleiben 100 kHz Bandbreite."),
        c(E, 2, "ee_devices", "Warum kann ein MOSFET bei Raumtemperatur nicht schneller als ≈ 60 mV pro Dekade Strom ein- und ausschalten?",
            "Der Unterschwellstrom wird von der Boltzmann-Verteilung der Ladungsträger über eine Barriere bestimmt (k_BT/e · ln 10)",
            "Weil das Gateoxid zu dick ist", "Wegen der Lichtgeschwindigkeit", "Weil Silizium ein Isolator ist",
            why = "S = n(k_BT/e)ln 10 ≥ 60 mV/Dek. Diese „Boltzmann-Tyrannei“ begrenzt die minimale Versorgungsspannung; Tunnel-FETs und negative Kapazität wollen sie umgehen."),
        c(E, 2, "ee_devices", "Was beschreibt die Steilheit g_m eines Transistors?",
            "Wie stark der Ausgangsstrom auf eine Änderung der Steuerspannung reagiert (∂I/∂U)", "Den Leckstrom", "Die Durchbruchspannung", "Die Gatekapazität",
            why = "g_m bestimmt die Verstärkung (A_v ≈ −g_m R). Für Bipolartransistoren ist g_m = I_C/U_T, für MOSFETs in Sättigung 2I_D/U_ov."),
        c(E, 1, "ee_digital", "Warum verbraucht eine statische CMOS-Schaltung im Ruhezustand fast keine Leistung?",
            "Entweder Pull-up- oder Pull-down-Netz sperrt; es gibt keinen Querstrom, nur Leckströme", "Weil die Spannung null ist",
            "Weil Transistoren dann nicht existieren", "Weil Strom nur in Widerständen fließt",
            why = "Leistung fällt beim Umladen der Kapazitäten an (P = αCU²f). Bei modernen Prozessen wird der Leckstrom aber zu einem relevanten Anteil."),
        c(E, 2, "ee_digital", "Warum ist eine Hold-Verletzung gefährlicher als eine Setup-Verletzung?",
            "Sie hängt nicht von der Taktfrequenz ab und lässt sich nicht durch langsameren Takt beheben", "Weil sie häufiger ist",
            "Weil sie nur im Labor auftritt", "Weil sie Strom spart",
            why = "Setup-Probleme verschwinden bei niedrigerer Frequenz; Hold-Probleme entstehen durch zu schnelle Pfade zwischen zwei Flanken und machen den Chip unbrauchbar."),
        c(E, 2, "ee_digital", "Was ist der stärkste Hebel, um die dynamische Leistung eines Chips zu senken?",
            "Die Versorgungsspannung, weil P ∝ U²", "Die Taktfrequenz verdoppeln", "Mehr Kapazität einbauen", "Den Leckstrom erhöhen",
            why = "Spannungs- und Frequenzskalierung (DVFS) senkt die Leistung kubisch, wenn f mit U mitgeht. Daher laufen Handy-Kerne bei Teillast mit niedriger Spannung."),
        c(E, 2, "ee_digital", "Warum endete um 2005 der Anstieg der CPU-Taktfrequenzen weitgehend?",
            "Die Versorgungsspannung ließ sich wegen Leckströmen kaum weiter senken (Ende des Dennard-Scaling); die Leistungsdichte wurde zu groß",
            "Weil Transistoren nicht mehr kleiner wurden", "Weil Software es nicht brauchte", "Wegen der Lichtgeschwindigkeit auf dem Chip",
            why = "Transistoren wurden weiter kleiner (Moore), aber nicht mehr sparsamer pro Fläche. Die Antwort waren Mehrkernprozessoren, Spezialbeschleuniger und Dark Silicon."),
        c(E, 2, "ee_fab", "Welche drei Hebel verbessern die Auflösung der Lithografie?",
            "Kürzere Wellenlänge, größere numerische Apertur, kleinerer Prozessfaktor k₁", "Mehr Licht, dickerer Lack, längere Belichtung",
            "Größere Wafer, mehr Metalllagen, Kupfer statt Aluminium", "Höhere Temperatur, mehr Druck, schnellere Rotation",
            why = "CD = k₁λ/NA. EUV (13,5 nm), Immersion und High-NA sowie Mehrfachbelichtung und OPC reduzieren die Strukturbreite."),
        c(E, 2, "ee_fab", "Warum wurden FinFETs und später Gate-All-Around-Transistoren eingeführt?",
            "Damit das Gate den Kanal von mehreren Seiten kontrolliert und Kurzkanaleffekte und Leckströme klein bleiben",
            "Weil sie billiger zu fertigen sind", "Weil planare Transistoren zu langsam leuchten", "Um die Wafer größer zu machen",
            why = "Je kürzer der Kanal, desto stärker beeinflusst die Drainspannung die Barriere (DIBL). Ein umschließendes Gate behält die elektrostatische Kontrolle."),
        c(E, 3, "ee_fab", "Warum sinkt die Ausbeute großer Chips überproportional?",
            "Zufällige Defekte treffen größere Flächen häufiger: Y = e^{−D₀A} fällt exponentiell mit der Fläche",
            "Weil große Chips langsamer sind", "Weil Lithografie nur kleine Chips kann", "Weil Kupfer bei großen Chips schmilzt",
            why = "Deshalb setzen Hersteller auf Chiplets: mehrere kleine Dies mit hoher Ausbeute, verbunden über Interposer oder 3D-Stapelung."),
        c(E, 2, "ee_design", "Was prüft die statische Timing-Analyse (STA)?",
            "Ob alle Pfade zwischen Registern die Setup- und Hold-Bedingungen in allen Prozess-Spannungs-Temperatur-Ecken einhalten",
            "Ob der Chip richtig rechnet (Funktion)", "Ob die Masken fehlerfrei sind", "Wie viel der Chip kostet",
            why = "STA ist vektorlos und vollständig über alle Pfade. Die Funktion prüft man getrennt durch Simulation und formale Verifikation."),
        c(E, 2, "ee_design", "Wozu dienen Scan-Ketten im Chipentwurf?",
            "Um nach der Fertigung Testmuster in alle Flipflops zu schieben und Fertigungsfehler zu erkennen", "Um den Takt zu verteilen",
            "Um die Leistung zu senken", "Um den Chip zu verschlüsseln",
            why = "Design-for-Test macht sequentielle Logik testbar wie kombinatorische. ATPG erzeugt Muster für Fehlermodelle wie stuck-at oder Übergangsfehler."),
        c(E, 2, "ee_design", "Warum sind KI-Beschleuniger um Datenbewegung herum gebaut?",
            "Ein Speicherzugriff kostet viel mehr Energie als eine Multiplikation; Daten lokal wiederzuverwenden spart Energie",
            "Weil Rechenwerke teuer sind", "Weil Software es verlangt", "Weil Taktfrequenzen beliebig steigen",
            why = "Systolische Arrays und große On-Chip-SRAMs maximieren die arithmetische Intensität (Operationen pro geladenem Byte) — siehe Roofline-Modell."),
        c(E, 2, "ee_analog", "Was passiert, wenn man ein Signal mit weniger als der doppelten Maximalfrequenz abtastet?",
            "Aliasing: hohe Frequenzen erscheinen als falsche tiefe Frequenzen", "Das Signal wird nur leiser", "Nichts", "Das Signal wird verstärkt",
            why = "Nyquist-Shannon verlangt f_s > 2f_max. Ein analoges Anti-Aliasing-Filter vor dem ADC entfernt Anteile oberhalb f_s/2."),
        c(E, 3, "ee_analog", "Warum kann man den Abtastkondensator eines präzisen ADC nicht beliebig klein machen?",
            "Das kT/C-Rauschen wächst mit kleiner Kapazität und begrenzt die Auflösung", "Weil kleine Kondensatoren leiten",
            "Weil die Spannung sonst steigt", "Weil kleine Kondensatoren nicht herstellbar sind",
            why = "u_rms = √(k_BT/C): Bei 1 pF etwa 64 μV. Für mehr Bits braucht man größere Kapazitäten — und mehr Treiberleistung."),

        // ================= AI Engineering =================
        c(A, 1, "ai_intro", "Was unterscheidet maschinelles Lernen von klassischer Programmierung?",
            "Die Regeln werden aus Beispielen gelernt, statt von Hand geschrieben zu werden", "ML-Programme brauchen keinen Computer",
            "ML kann nur Bilder verarbeiten", "Bei ML gibt es keine Fehler",
            why = "Man wählt eine Modellklasse und einen Verlust; ein Optimierungsverfahren passt die Parameter an Daten an. Das Ziel ist Generalisierung auf neue Daten."),
        c(A, 1, "ai_intro", "Wozu dient die Testmenge?",
            "Für eine einmalige, ehrliche Abschätzung der Leistung auf ungesehenen Daten am Ende", "Zum Trainieren der Gewichte",
            "Zum Einstellen der Lernrate", "Um mehr Trainingsdaten zu haben",
            why = "Hyperparameter wählt man mit der Validierungsmenge. Wer auf der Testmenge optimiert, überschätzt die Leistung systematisch."),
        c(A, 1, "ai_intro", "Ein Modell hat 99 % Trainings-, aber 70 % Validierungsgenauigkeit. Was liegt vor?",
            "Overfitting: Das Modell hat Trainingsdetails auswendig gelernt", "Underfitting", "Perfekte Generalisierung", "Ein Fehler im Datensatz ist ausgeschlossen",
            why = "Gegenmittel: mehr Daten, Augmentation, Regularisierung, kleineres Modell, Early Stopping. Auch ein Datenleck oder eine Verteilungsverschiebung sollte geprüft werden."),
        c(A, 2, "ai_intro", "Warum ist Accuracy bei sehr unausgewogenen Klassen irreführend?",
            "Ein Modell, das immer die Mehrheitsklasse vorhersagt, erreicht hohe Accuracy, ohne etwas zu können", "Weil Accuracy immer 50 % ist",
            "Weil Accuracy nur für Regression gilt", "Weil sie negativ werden kann",
            why = "Bei 1 % Positiven liefert „immer negativ“ 99 % Accuracy bei 0 % Recall. Precision, Recall, F1 oder PR-AUC sind aussagekräftiger."),
        c(A, 1, "ai_linear", "Was passiert bei zu großer Lernrate im Gradientenabstieg?",
            "Die Updates überschießen das Minimum, der Verlust oszilliert oder divergiert", "Das Training wird nur langsamer", "Das Modell wird automatisch besser", "Nichts",
            why = "Für eine quadratische Mulde ist der Abstieg nur für η < 2/λ_max stabil. Zu kleine Lernraten sind stabil, aber langsam."),
        c(A, 2, "ai_linear", "Warum nimmt man für Klassifikation Kreuzentropie statt quadratischem Fehler?",
            "Sie entspricht der Log-Likelihood, bestraft sichere Fehlvorhersagen stark und liefert gut skalierte Gradienten mit Softmax",
            "Weil quadratischer Fehler nicht differenzierbar ist", "Weil Kreuzentropie immer null ist", "Aus Tradition",
            why = "Mit Softmax ist ∂ℓ/∂z = p − y — einfach und nicht gesättigt, wenn das Modell falsch liegt. MSE mit Sigmoid hat bei falschen, sicheren Vorhersagen winzige Gradienten."),
        c(A, 2, "ai_linear", "Was bewirkt L2-Regularisierung (Weight Decay)?",
            "Sie zieht Gewichte zur Null und bevorzugt glattere, einfachere Lösungen", "Sie setzt viele Gewichte exakt auf null",
            "Sie erhöht die Lernrate", "Sie vergrößert das Modell",
            why = "Exakte Nullen erzeugt L1. L2 entspricht einem gaußschen Prior auf den Gewichten und verringert die Varianz des Modells."),
        c(A, 1, "ai_nn", "Warum braucht ein neuronales Netz nichtlineare Aktivierungsfunktionen?",
            "Ohne sie wäre eine Hintereinanderschaltung linearer Schichten wieder nur eine lineare Abbildung", "Damit es schneller rechnet",
            "Damit die Gewichte positiv bleiben", "Damit kein Speicher nötig ist",
            why = "W₂(W₁x) = (W₂W₁)x. Erst ReLU, GELU usw. machen tiefe Netze ausdrucksstark genug für komplexe Funktionen."),
        c(A, 2, "ai_nn", "Was ist Backpropagation mathematisch?",
            "Die Kettenregel, rückwärts durch den Rechengraphen angewandt (Reverse-Mode-Autodiff)", "Ein spezieller Optimierer",
            "Eine Methode zur Datenaugmentation", "Ein Zufallsverfahren",
            why = "Sie berechnet alle Gradienten mit etwa dem doppelten Aufwand eines Vorwärtsdurchlaufs — egal wie viele Parameter es gibt. Ohne sie wäre Deep Learning nicht praktikabel."),
        c(A, 2, "ai_nn", "Wozu dienen Residualverbindungen (y = x + F(x))?",
            "Gradienten fließen direkt durch viele Schichten; sehr tiefe Netze werden trainierbar", "Sie halbieren die Parameterzahl",
            "Sie ersetzen die Aktivierungsfunktion", "Sie machen das Netz linear",
            why = "Die Identität sorgt für einen ungehinderten Gradientenpfad. Transformer bestehen im Kern aus einem Residualstrom, in den Attention- und MLP-Blöcke schreiben."),
        c(A, 2, "ai_training", "Warum ist Adam bei Transformern der Standardoptimierer?",
            "Er passt die Schrittweite pro Parameter an die Gradientengröße an und kombiniert das mit Momentum", "Weil er keine Lernrate braucht",
            "Weil er Backpropagation ersetzt", "Weil er immer das globale Minimum findet",
            why = "Parameter mit großen bzw. kleinen Gradienten bekommen angepasste Schritte; das stabilisiert Training mit sehr unterschiedlich skalierten Gewichten (Embeddings, Attention, Normen)."),
        c(A, 2, "ai_training", "Warum beginnt man das Training großer Modelle oft mit einem Lernraten-Warmup?",
            "Zu Beginn sind Gradienten und Adam-Statistiken unzuverlässig; große Schritte würden das Training destabilisieren",
            "Um die GPU aufzuwärmen", "Weil Daten erst geladen werden müssen", "Um Overfitting zu erzeugen",
            why = "Lineares Aufwärmen über einige hundert bis tausend Schritte, danach ein Cosinus-Abfall, ist ein robustes Standardrezept."),
        c(A, 1, "ai_training", "Was ist der beste erste Schritt beim Debuggen eines neuen Modells?",
            "Ein winziges Teilset perfekt überanpassen — klappt das nicht, ist etwas im Code oder Setup kaputt", "Sofort das größte Modell trainieren",
            "Die Lernrate maximal erhöhen", "Die Validierungsmenge weglassen",
            why = "Wenn ein Modell nicht einmal 10 Beispiele auswendig lernen kann, liegen Fehler bei Labels, Verlust, Datenpipeline oder Optimierer vor."),
        c(A, 2, "ai_arch", "Warum haben Faltungsnetze bei Bildern so viel weniger Parameter als vollverbundene Netze?",
            "Derselbe kleine Filter wird an jeder Position wiederverwendet (Gewichtsteilung, Lokalität)", "Weil Bilder klein sind",
            "Weil sie keine Gewichte haben", "Weil sie nur schwarz-weiß verarbeiten",
            why = "Ein 3×3-Filter mit 64 Ein- und Ausgabekanälen hat ≈ 37 000 Parameter, unabhängig von der Bildgröße. Zudem sind Faltungen translationsäquivariant."),
        c(A, 2, "ai_arch", "Was ist ein Embedding?",
            "Ein gelernter Vektor für ein diskretes Objekt, dessen Lage Bedeutung trägt (Ähnliches liegt nah)", "Eine Kompressionsmethode für Bilder",
            "Ein Hardwarebaustein", "Eine Verlustfunktion",
            why = "Embeddings für Token, Sätze, Bilder oder Nutzer sind die Grundlage von Sprachmodellen, semantischer Suche und Empfehlungssystemen."),
        c(A, 2, "ai_transformer", "Was berechnet Self-Attention anschaulich?",
            "Für jedes Token eine gewichtete Mischung der Informationen aller anderen Token, gewichtet nach Query-Key-Ähnlichkeit",
            "Die Wortfrequenz im Text", "Eine Faltung mit festem Fenster", "Die Länge des Textes",
            why = "softmax(QKᵀ/√d)V: Jedes Token sucht (Query) passende Informationen (Keys) und übernimmt deren Inhalte (Values) — direkt über beliebige Distanzen."),
        c(A, 3, "ai_transformer", "Warum teilt man in der Attention durch √d_k?",
            "Damit die Skalarprodukte bei großer Dimension nicht zu groß werden und die Softmax nicht in die Sättigung geht",
            "Um Speicher zu sparen", "Weil d_k immer 1 ist", "Um negative Werte zu vermeiden",
            why = "Für zufällige Vektoren wächst die Varianz von q·k linear mit d_k. Ohne Skalierung würde die Softmax fast one-hot und Gradienten verschwänden."),
        c(A, 2, "ai_transformer", "Warum brauchen Transformer Positionsinformation (z. B. RoPE)?",
            "Attention ist von sich aus reihenfolgeunabhängig; ohne Positionen wäre „Hund beißt Mann“ gleich „Mann beißt Hund“",
            "Damit sie schneller rechnen", "Weil Token sonst zu groß sind", "Nur für Bilder",
            why = "Attention operiert auf einer Menge. RoPE dreht Query und Key positionsabhängig, sodass ihr Skalarprodukt vom relativen Abstand abhängt."),
        c(A, 2, "ai_transformer", "Warum ist ein sehr langer Kontext teuer?",
            "Attention vergleicht alle Tokenpaare: Rechenaufwand wächst quadratisch, der KV-Cache linear mit der Länge",
            "Weil Token teuer gekauft werden", "Weil lange Texte mehr Wörter haben", "Er ist nicht teurer",
            why = "O(n²d) pro Schicht. FlashAttention senkt den Speicherbedarf, ändert aber die quadratische Rechenlast nicht."),
        c(A, 2, "ai_llm", "Was lernt ein Sprachmodell im Vortraining?",
            "Das nächste Token aus dem vorherigen Text vorherzusagen", "Fragen korrekt zu beantworten", "Bilder zu klassifizieren", "Programme auszuführen",
            why = "Selbstüberwachte Vorhersage auf riesigen Textmengen. Gutes Vorhersagen erzwingt Grammatik, Fakten und Muster des Schließens; Anweisungsbefolgung kommt erst durch Feinabstimmung."),
        c(A, 3, "ai_llm", "Was besagen die Chinchilla-Skalierungsgesetze?",
            "Bei festem Rechenbudget sollten Parameter und Trainingstoken etwa gleichmäßig wachsen, rund 20 Token pro Parameter",
            "Größere Modelle brauchen weniger Daten", "Nur die Datenmenge zählt", "Ab 1 Mrd. Parametern wird jedes Modell intelligent",
            why = "Frühere Modelle waren „untertrainiert“. Für den Einsatz trainiert man kleine Modelle heute oft weit über 20 Token/Parameter, weil sie bei der Inferenz billiger sind."),
        c(A, 2, "ai_llm", "Was ist der Vorteil von LoRA beim Feinabstimmen?",
            "Nur eine kleine niedrigrangige Korrektur wird trainiert; Speicher und Rechenaufwand sinken drastisch", "Das Modell wird kleiner",
            "Das Modell braucht keine Daten mehr", "Es ersetzt das Vortraining",
            why = "ΔW = BA mit Rang r ≪ d: oft unter 1 % der Parameter. Mehrere LoRA-Adapter können für verschiedene Aufgaben ausgetauscht werden."),
        c(A, 2, "ai_llm", "Wozu dient RLHF bzw. DPO nach dem Vortraining?",
            "Das Modell an menschliche Präferenzen anzupassen: hilfreich, ehrlich, sicher", "Das Modell schneller zu machen",
            "Neue Sprachen hinzuzufügen", "Die Parameterzahl zu verringern",
            why = "Menschen vergleichen Antworten; RLHF optimiert gegen ein Belohnungsmodell, DPO direkt auf den Vergleichspaaren."),
        c(A, 2, "ai_inference", "Wozu dient der KV-Cache bei der Textgenerierung?",
            "Keys und Values früherer Token werden gespeichert, damit jedes neue Token nicht den ganzen Text neu berechnen muss",
            "Er speichert die Gewichte", "Er komprimiert den Text", "Er verhindert Halluzinationen",
            why = "Ohne Cache wäre jedes Token O(n) Vorwärtsdurchläufe teuer. Maximus nutzt das über Gesprächsrunden hinweg, damit Folgefragen schnell starten."),
        c(A, 2, "ai_inference", "Warum ist die Token-Generierung auf dem Handy meist durch die Speicherbandbreite begrenzt?",
            "Für jedes Token müssen alle Gewichte einmal aus dem Speicher gelesen werden, die Rechenarbeit pro Byte ist gering",
            "Weil die CPU zu wenige Kerne hat", "Weil der Bildschirm zu klein ist", "Weil Token sehr groß sind",
            why = "Token/s ≲ Bandbreite/Modellgröße. Deshalb hilft Quantisierung (weniger Bytes) direkt bei der Geschwindigkeit."),
        c(A, 1, "ai_inference", "Was bewirkt eine niedrige Sampling-Temperatur?",
            "Die Verteilung wird schärfer; das Modell wählt fast immer die wahrscheinlichsten Token (präziser, weniger kreativ)",
            "Das Modell wird kreativer", "Das Modell läuft kühler", "Es wird mehr Text erzeugt",
            why = "p ∝ e^{z/T}. Für Code und Fakten T ≈ 0,1–0,3, für kreatives Schreiben T ≈ 0,7–1."),
        c(A, 2, "ai_inference", "Warum halluzinieren Sprachmodelle?",
            "Sie optimieren die Wahrscheinlichkeit plausibler Texte, nicht die Wahrheit; fehlt Wissen, entsteht trotzdem flüssiger Text",
            "Weil sie absichtlich lügen", "Weil die GPU Fehler macht", "Nur bei falscher Temperatur",
            why = "Gegenmittel: Quellen per RAG, Werkzeuge für exakte Rechnungen, Unsicherheit erfragen, Antworten prüfen."),
        c(A, 2, "ai_rag_agents", "Was ist Retrieval-Augmented Generation (RAG)?",
            "Passende Textstücke aus einer Wissensbasis werden gesucht und dem Modell im Prompt mitgegeben", "Ein Trainingsverfahren für Bilder",
            "Eine Methode zur Quantisierung", "Ein Ersatz für Tokenisierung",
            why = "So bleibt Wissen aktuell und überprüfbar (Quellen), ohne das Modell neu zu trainieren. Qualität hängt stark von Chunking und Suche ab."),
        c(A, 3, "ai_rag_agents", "Warum kombiniert man in RAG oft Schlüsselwort- (BM25) und Vektorsuche?",
            "BM25 findet exakte Begriffe und Namen zuverlässig, Vektorsuche semantisch ähnliche Formulierungen; zusammen sind sie robuster",
            "Weil Vektorsuche nicht funktioniert", "Weil BM25 neuronale Netze braucht", "Um Speicher zu sparen",
            why = "Hybride Suche plus Reranking ist heute Standard. Fachbegriffe, Formeln und Eigennamen sind für Embeddings oft schwierig."),
        c(A, 3, "ai_rag_agents", "Was ist Prompt-Injection?",
            "Fremder Text (Webseite, Dokument, Tool-Ausgabe) enthält Anweisungen, die das Modell fälschlich befolgt",
            "Ein Trainingsverfahren", "Eine Methode, Prompts zu komprimieren", "Ein Hardwarefehler",
            why = "Besonders gefährlich bei Agenten mit Werkzeugen. Gegenmittel: Inhalte als Daten kennzeichnen, minimale Rechte, Bestätigung kritischer Aktionen."),
        c(A, 2, "ai_rag_agents", "Was macht einen Agenten aus?",
            "Eine Schleife aus Planen, Werkzeug benutzen und Beobachten, bis ein Ziel erreicht ist", "Ein besonders großes Modell",
            "Ein Modell ohne Prompt", "Eine Datenbank",
            why = "Zuverlässigkeit hängt an klaren Werkzeugen, begrenzten Schritten, Protokollierung und Evaluation — nicht nur an der Modellgröße."),
        c(A, 2, "ai_mlops", "Warum sollte man vor dem Optimieren eines KI-Systems eine Evaluationsmenge bauen?",
            "Ohne reproduzierbare Messung lässt sich nicht feststellen, ob eine Änderung hilft oder schadet", "Weil Gesetze es verlangen",
            "Um mehr Trainingsdaten zu haben", "Weil Modelle sonst nicht laufen",
            why = "Evaluation zuerst: echte Nutzungsfälle, klare Kriterien, automatisierte Auswertung, Stichprobenprüfung durch Menschen."),
        c(A, 2, "ai_mlops", "Was ist ein Vorteil lokaler (On-Device-)Modelle wie Maximus?",
            "Datenschutz und Offline-Betrieb ohne laufende Kosten", "Sie sind immer klüger als Cloud-Modelle",
            "Sie brauchen keinen Speicher", "Sie laufen ohne Strom",
            why = "Der Preis sind kleinere Modelle. Werkzeuge, Retrieval und gute Prompts gleichen einen Teil davon aus."),
        c(A, 3, "ai_mlops", "Was bedeutet Daten-Drift im Betrieb?",
            "Die Verteilung der echten Eingaben weicht mit der Zeit von den Trainingsdaten ab, die Leistung sinkt unbemerkt",
            "Dass Daten physisch verschoben werden", "Dass das Modell schneller wird", "Dass Gewichte zufällig wandern",
            why = "Monitoring von Eingabeverteilungen und Stichproben-Evaluation erkennen Drift; dann helfen neue Daten, Nachtraining oder Anpassung der Prompts."),
        // ================= Zusatzkapitel bestehender Gebiete =================
        c(Topic.THERMO, 3, "th_noneq", "Was besagen die Onsager-Reziprozitätsrelationen?",
            "Die Matrix der linearen Transportkoeffizienten ist symmetrisch (Lᵢⱼ = Lⱼᵢ), eine Folge mikroskopischer Zeitumkehrinvarianz",
            "Alle Transportkoeffizienten sind gleich groß", "Wärme fließt immer von kalt nach warm", "Die Entropie bleibt im Nichtgleichgewicht konstant",
            why = "Deshalb sind etwa Seebeck- und Peltier-Effekt verknüpft (Π = ST). Mit Magnetfeld gilt Lᵢⱼ(B) = Lⱼᵢ(−B)."),
        c(Topic.THERMO, 3, "th_noneq", "Was verbindet das Fluktuations-Dissipations-Theorem?",
            "Die Antwort eines Systems auf kleine Störungen mit seinen spontanen Gleichgewichtsfluktuationen", "Druck und Volumen",
            "Energie und Masse", "Teilchenzahl und Spin",
            why = "Beispiele: Einstein-Relation D = μk_BT und Johnson-Nyquist-Rauschen 4k_BTR. Reibung und Rauschen haben dieselbe mikroskopische Ursache."),
        c(Topic.ELECTRO, 2, "el_optics", "Warum gibt es bei Glasfasern kaum Verluste an der Mantelgrenze?",
            "Totalreflexion: Licht im Kern trifft oberhalb des Grenzwinkels auf den Mantel mit kleinerem Brechungsindex",
            "Weil Glas Licht verstärkt", "Weil der Mantel verspiegelt ist", "Weil Licht in Glas langsamer ist und deshalb nicht austritt",
            why = "sin θ_c = n_Mantel/n_Kern. Verluste entstehen vor allem durch Absorption und Rayleigh-Streuung im Glas, minimal bei 1550 nm."),
        c(Topic.ELECTRO, 2, "el_optics", "Was begrenzt grundsätzlich die Auflösung eines Lichtmikroskops?",
            "Die Beugung: Strukturen unter etwa λ/(2NA) lassen sich nicht trennen (Abbe)", "Die Pixelzahl der Kamera", "Die Helligkeit der Lampe", "Die Vergrößerung des Okulars",
            why = "Mehr Vergrößerung ohne höhere NA oder kürzere Wellenlänge zeigt nur ein größeres, unscharfes Bild. Superauflösungsmethoden (STED, PALM) umgehen die Grenze mit Fluoreszenztricks."),
        c(Topic.QUANTUM, 3, "qm_scattering", "Was ist die Bornsche Näherung anschaulich?",
            "Die Streuamplitude ist die Fourier-Transformierte des Potentials beim Impulsübertrag — gültig für schwache Streuer",
            "Eine Näherung für sehr starke Potentiale", "Die klassische Bahnberechnung", "Eine Methode für gebundene Zustände",
            why = "f(q) ∝ ∫V(r)e^{−iq·r}d³r. Daher messen Streuexperimente (Röntgen, Neutronen, Elektronen) die Fourier-Komponenten von Strukturen."),
        c(Topic.QUANTUM, 2, "qm_scattering", "Woran erkennt man eine Resonanz in einem Streuexperiment?",
            "Ein scharfes Maximum im Wirkungsquerschnitt mit Breit-Wigner-Form; die Breite Γ entspricht der Lebensdauer ħ/Γ",
            "Am Verschwinden aller Streuung", "Am Vorzeichen der Ladung", "An einer konstanten Streuphase",
            why = "Die Streuphase durchläuft π/2. So wurden etwa das Z-Boson und viele Hadronen entdeckt."),
        c(Topic.SEMICONDUCTOR, 3, "sc_hetero", "Warum ist der Hall-Widerstand im Quanten-Hall-Effekt so exakt quantisiert?",
            "Er ist eine topologische Größe (Chern-Zahl) und hängt nicht von Probendetails, Unordnung oder Geometrie ab",
            "Weil die Proben extrem rein sind", "Weil das Magnetfeld exakt eingestellt wird", "Weil Elektronen keine Masse haben",
            why = "R_xy = h/(νe²) auf besser als 10⁻⁹. Unordnung hilft sogar: Sie lokalisiert Zustände zwischen den Landau-Niveaus und erzeugt die Plateaus."),
        c(Topic.SEMICONDUCTOR, 2, "sc_hetero", "Was bewirkt Modulationsdotierung in einer GaAs/AlGaAs-Heterostruktur?",
            "Dotieratome und Elektronen werden räumlich getrennt; das 2DEG streut kaum an ionisierten Störstellen und hat sehr hohe Beweglichkeit",
            "Sie erhöht die Bandlücke von GaAs", "Sie macht das Material magnetisch", "Sie verhindert jeden Stromfluss",
            why = "Grundlage von HEMT-Transistoren und der Entdeckung des fraktionalen Quanten-Hall-Effekts."),
        c(Topic.MECHANICS, 2, "me_chaos", "Warum lässt sich das Wetter trotz deterministischer Gleichungen nicht langfristig vorhersagen?",
            "Chaos: Kleine Anfangsfehler wachsen exponentiell mit dem Lyapunov-Exponenten", "Weil die Gleichungen zufällig sind",
            "Weil Computer zu langsam sind", "Weil die Atmosphäre keine Energie erhält",
            why = "Die Vorhersagbarkeit endet nach etwa (1/λ) ln(Toleranz/Anfangsfehler). Lorenz entdeckte das 1963 an einem einfachen Konvektionsmodell."),
        c(Topic.MECHANICS, 3, "me_chaos", "Was sagt das KAM-Theorem?",
            "Bei kleinen Störungen eines integrablen Systems bleiben die meisten invarianten Tori erhalten; resonante zerfallen in chaotische Bereiche",
            "Jede Störung macht ein System vollständig chaotisch", "Hamilton-Systeme sind immer integrabel", "Energie ist in gestörten Systemen nicht erhalten",
            why = "Erklärt die Stabilität des Sonnensystems über lange Zeiten und das Nebeneinander von regulären und chaotischen Bahnen im Phasenraum."),
        c(Topic.MATH, 3, "ma_groups", "Warum erzeugen Symmetrien Entartungen von Energieniveaus?",
            "Eigenräume des Hamilton-Operators tragen Darstellungen der Symmetriegruppe; ihre Dimension ist mindestens die einer irreduziblen Darstellung",
            "Weil Symmetrien die Energie halbieren", "Weil symmetrische Systeme keine Energie haben", "Das ist Zufall",
            why = "Kommutiert H mit allen Gruppenelementen, bildet jedes Gruppenelement Eigenzustände in denselben Eigenraum ab (Schursches Lemma). Beispiel: (2l + 1)-fache Entartung durch Drehsymmetrie."),
        c(Topic.MATH, 3, "ma_groups", "Woher kommen die Dipolauswahlregeln Δl = ±1?",
            "Aus dem Wigner-Eckart-Theorem: Der Dipoloperator ist ein Vektoroperator (k = 1), Clebsch-Gordan-Koeffizienten verschwinden sonst",
            "Aus der Energieerhaltung allein", "Aus der Masse des Elektrons", "Aus dem Pauli-Prinzip",
            why = "Zusätzlich erzwingt die Parität des Dipoloperators einen Paritätswechsel, deshalb ist Δl = 0 verboten.")
    )
}
